'use strict';
const app=document.getElementById('app'),modal=document.getElementById('modal'),modalBody=document.getElementById('modal-body');
const offline=Game.init();
let page='city',selectedNode='field',trainId='',toastTimer,autoLast=0;
const BATTLE_ROUND_MS=30000;
function battleTimerText(){const b=Game.state.battle;return b?.auto&&!b.finished?`下一回合倒计时：${Math.max(0,Math.ceil((BATTLE_ROUND_MS-(Date.now()-autoLast))/1000))} 秒`:'已暂停计时，可手动进入下一回合。';}
function advanceBattleRound(){if(!Game.state.battle||Game.state.battle.finished)return;autoLast=Date.now();Game.battleRound();render();}
const S=()=>Game.state;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Math.floor(n).toLocaleString('zh-CN');
const duration=seconds=>seconds>=3600?`${Math.floor(seconds/3600)} 小时 ${Math.floor(seconds%3600/60)} 分`:seconds>=60?`${Math.floor(seconds/60)} 分 ${Math.ceil(seconds%60)} 秒`:`${Math.max(0,Math.ceil(seconds))} 秒`;
const btn=(label,action,arg='',cls='',disabled=false)=>`<button class="btn ${cls}" data-action="${action}" data-id="${arg}" ${disabled?'disabled':''}>${label}</button>`;
const lootHtml=loot=>`<div class="loot">${Object.entries(loot).map(([k,v])=>`<span>${resourceIcon(k)}${Game.resources[k].name} +${num(v)}</span>`).join('')}</div>`;
const costs=cost=>`<div class="cost">${Object.entries(cost).map(([k,v])=>`<span class="${S().res[k]<v?'short':''}">${resourceIcon(k)}${Game.resources[k].name} ${num(v)}</span>`).join('')}</div>`;
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');if(modal.open){let message=modalBody.querySelector('[data-modal-status]');if(!message){message=document.createElement('p');message.dataset.modalStatus='';message.setAttribute('role','status');message.className='notice';message.style.marginTop='16px';modalBody.append(message);}message.textContent=text;}clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function showModal(title,body,actions=''){manualModalContext=null;modalBody.innerHTML=`<div class="modal-top"><h2>${title}</h2><button class="close" data-action="close" aria-label="关闭">×</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}`;if(!modal.open)modal.showModal();}
function actResult(error,success){if(error){toast(error);return false;}if(success)toast(success);render();return true;}
function clock(end,start){return `<span data-clock="${end}">${duration((end-Date.now())/1000)}</span>${start?`<div class="progress"><i data-progress-end="${end}" data-progress-start="${start}" style="width:${Math.min(100,Math.max(0,(Date.now()-start)/(end-start)*100))}%"></i></div>`:''}`;}
function queueHTML(q,type){const name=type==='build'?`${q.auto?'自动 · ':''}${q.plot!==undefined?'城外 '+(q.plot+1)+'号 · ':''}${Game.buildings[q.id].name} → ${q.level} 级`:`${Game.units[q.id].name} ×${q.count}`;return `<div class="queue"><div class="queue-head">${name}${clock(q.end)}</div>${clock(q.end,q.start).replace(/<span[\s\S]*?<\/span>/,'')}<div class="queue-tools">${speedupQueueButton(type==='build'?'build':'train',q)}</div></div>`;}
function missionHTML(){const m=Game.currentMission();return m?`<div class="mission"><span class="mark">${S().missionClaims.length}/${Game.missions.length}</span><div class="copy"><strong>${m.title}</strong><p>${m.desc}</p></div>${btn(Game.missionReady(m)?'领取奖励':'查看任务',Game.missionReady(m)?'mission':'classicMission',m.id,'small')}</div>`:`<div class="mission"><span class="mark">✓</span><div class="copy"><strong>首章任务已完成</strong><p>依靠掠夺和战利品继续扩建、练兵与攻城。</p></div>${btn('任务册','classicMission','','small secondary')}</div>`;}
function render(){const previousMain=document.getElementById('main'),scrollTop=previousMain?.dataset.page===page?previousMain.scrollTop:0;app.innerHTML=classicShell();const main=document.getElementById('main');main.dataset.page=page;main.scrollTop=scrollTop;if(page==='world'&&S().battle)document.getElementById('battle-log')?.scrollTo(0,99999);if(page==='world'&&!S().battle)drawWorldMiniMap();}
// Original SVG scenery; no source-game screenshots or proprietary assets are used.
function roof(x,y,scale=1,color='#344b40'){return `<g transform="translate(${x} ${y}) scale(${scale})"><path d="M-34 0L0-20 34 0 43 3H-43Z" fill="${color}" stroke="#9aaa83" stroke-width="1"/><path d="M-27 4h54v24h-54z" fill="#b8b391"/><path d="M-17 7v21m34-21v21" stroke="#64765a" stroke-width="4"/><path d="M-5 13h10v15H-5z" fill="#405847"/><path d="M-32 30h64" stroke="#607758" stroke-width="5"/></g>`;}
function innerCityPage(){return manualInnerCityPage();}
function buildingModal(id){manualBuildingModal(id);}
function armyPage(){return `<div class="page-head"><div><h2>厉兵秣马</h2><p class="sub">枪克骑 · 骑克弓 · 盾抗箭，胜负从配兵开始。</p></div><div class="army-head-actions"><span class="badge">驻城 ${Game.totalArmy(S().army)} 人</span>${btn('出征战术','tacticsModal','','small secondary')}</div></div>${captiveSummaryHTML()}<div class="army-grid">${Object.entries(Game.units).map(([id,u])=>`<section class="troop-card"><div class="troop-top">${troopPortrait(id,'troop-symbol')}<div class="text"><h3>${u.name}</h3><p class="sub">${u.role}</p></div><span class="number">${S().army[id]}</span></div><div class="troop-stats"><span>生命 ${u.hp}</span><span>攻击 ${u.atk}</span><span>防御 ${u.def}</span><span>速度 ${u.speed}</span><span>射程 ${u.range}</span><span>负重 ${u.carry}</span><span>耗粮 ${u.upkeep}/小时</span></div><div class="troop-bottom"><p class="troop-cost">每人 · ${Object.entries(u.cost).map(([k,v])=>`${Game.resources[k].name}${v}`).join(' ')}<br>${duration(Game.trainSeconds(id,1))}/人（试玩） · 消耗 ${u.people||1} 空闲人口<br>${Game.unitRequirements(id)?'需要 '+Game.unitRequirements(id):'招募条件已满足'}</p>${btn(Game.unitUnlocked(id)?'招募训练':'条件未满足','trainModal',id,'small',!Game.unitUnlocked(id))}</div></section>`).join('')}</div><section class="panel queue-list"><div class="section-title"><h3>训练队列</h3><span class="label">依次训练 · ${S().trainQueue.length} / ${Game.trainingLimit()}</span></div>${S().trainQueue.length?S().trainQueue.map(q=>queueHTML(q,'train')).join(''):'<div class="empty">军营待命。训练士兵后，前往「天下」派遣部队。</div>'}</section>`;}
function trainModal(id){trainId=id;const u=Game.units[id],free=Game.freePopulation(),affordable=Math.floor(Math.min(...Object.entries(u.cost).map(([k,v])=>S().res[k]/v))),max=Math.max(0,Math.min(100000,Math.floor(free/(u.people||1)),affordable));showModal(`训练${u.name}`,`<p class="sub">${u.role} · 城内现有 ${S().army[id]} 人 · 每名需要 ${u.people||1} 人口</p><div class="modal-info"><span>空闲人口</span><strong>${free}</strong></div><p class="label">本次训练人数</p><div class="slider-row"><input id="train-range" type="range" min="1" max="${Math.max(1,max)}" value="${Math.max(1,Math.min(20,max))}" ${max===0?'disabled':''} aria-label="训练人数"><input id="train-number" type="number" min="1" max="${Math.max(1,max)}" value="${Math.max(1,Math.min(20,max))}" aria-label="训练人数"></div><div id="train-cost"></div><p class="hint" id="train-time"></p>${max===0?'<div class="notice">当前资源或人口不足，先发展城池或获取战利品。</div>':''}`,btn('取消','close','','secondary')+btn('开始训练','train',id,'',max===0||S().trainQueue.length>=Game.trainingLimit()));updateTrain();}
function updateTrain(){const el=document.getElementById('train-number');if(!el)return;const count=Math.max(1,Math.min(Number(el.max),Math.floor(Number(el.value)||1)));el.value=count;document.getElementById('train-range').value=count;document.getElementById('train-cost').innerHTML=costs(Game.trainCost(trainId,count));document.getElementById('train-time').textContent=`工期 ${duration(Game.trainSeconds(trainId,count))} · 占用人口 ${num(count*(Game.units[trainId].people||1))} · 勇武与练兵科技缩短工期`;}
function expeditionStrip(){return Game.allExpeditions().map(e=>{const n=Game.getNode(e.node),arrived=e.phase==='march'&&e.end<=Date.now();return `<div class="dispatch-strip"><div><strong>${esc(Game.general(e.general).name)} · ${e.mode==='raid'?'掠夺':'占领'} · ${n.name}</strong><p>${e.phase==='return'?'返城 '+clock(e.end):e.phase==='battle'?'战斗进行中':arrived?'已抵达，等待指令':'行军 '+clock(e.end)}</p></div>${arrived?btn('进入战斗','manualExpeditionBattle',e.node,'small'):e.phase==='march'?btn('召回','manualExpeditionRecall',e.node,'small secondary'):''}</div>`;}).join('');}

function dispatchModal(nodeId,mode='raid'){campaignDispatchModal(nodeId,mode);}
function dispatchArmy(){return Object.fromEntries([...modalBody.querySelectorAll('[data-army-number]')].map(el=>[el.dataset.armyNumber,Number(el.value)||0]));}
function updateDispatch(nodeId){const sel=document.getElementById('dispatch-general');if(!sel?.value){document.getElementById('dispatch-estimate').textContent='暂无可出征主将。';return;}const n=Game.getNode(nodeId)||Game.getNode(document.getElementById('dispatch-mode')?.dataset.node)||Game.getNode(selectedNode),army=dispatchArmy(),count=Game.totalArmy(army),g=Game.general(sel.value),strength=Math.round(Game.power(army)*(1+g.atk/220)),info=Game.attackInfo(n.id,document.getElementById('dispatch-mode')?.value||'raid'),enemy=Game.power(info.army),supply=Math.ceil(count*1.2+n.time*2),intel=Game.intel(n.id),cargo=Game.lootPreview(n.id,document.getElementById('dispatch-mode')?.value||'raid',army);document.getElementById('dispatch-estimate').innerHTML=`出征 <strong>${num(count)} 人</strong> · 行军耗粮 <strong>${num(supply)}</strong>（试玩值）<br>部队负重 <strong>${num(Game.carry(army))}</strong> · 校场单队上限 ${num(Game.armyLimit())}<br>我军参考战力 <strong>${num(strength)}</strong> · 敌军 ${intel?.exact?num(enemy):'需精确侦察'}<br><span class="hint">${intel?.exact?(strength>enemy?'参考战力占优，留意兵种和射程。':'敌军较强，建议先补充兵力。'):'未精确侦察时不显示敌军战力。'} 战后按幸存士兵负重结算，伤兵不参与搬运。</span><div class="divider"></div><span class="label">无战损时预计基础装载 ${num(cargo.loaded)} / ${num(cargo.capacity)}</span>${lootHtml(cargo.loot)}${cargo.discarded?`<p class="hint">当前负重不足，约 ${num(cargo.discarded)} 基础资源无法带走；可带民夫或辎重车提高负重。</p>`:''}<p class="hint">额外掉落使用剩余负重，实际装载随战损减少。</p>`;}
function heroesPage(){return `<div class="page-head"><div><h2>帐下群英</h2><p class="sub">一人守城，一人出征。通过实战提升武将等级。</p></div><span class="badge">已招募 ${S().generals.length} · 招贤馆 ${S().buildings.tavern} 间房</span></div><div class="hero-grid">${Game.generals.map(base=>{const g=Game.general(base.id),owned=S().generals.includes(g.id),busy=Game.generalBusy(g.id),gov=S().governor===g.id;return `<section class="hero-card ${owned?'':'locked'}"><span class="hero-watermark">${g.type}</span><div class="hero-art">${generalPortrait(g)}</div><div><h3>${esc(g.name)} <span class="label">Lv.${g.level}</span></h3><p class="hero-title">${esc(g.title)}</p></div><div class="hero-stats"><span>勇武<b>${Math.round(g.atk)}</b></span><span>统御<b>${g.def}</b></span><span>内政<b>${Math.round(g.pol)}</b></span><span>智谋<b>${Math.round(g.wis)}</b></span><span>统率<b>${Math.round(g.lead)}</b></span></div><p class="hint hero-desc">${esc(g.desc)}</p><div class="hero-footer"><span class="label">${!owned?'攻下黄巾营寨可解救':busy?'出征或驻守中':gov?'现任太守':`经验 ${S().generalXp[g.id]||0} / ${g.level*80}`}</span>${owned?btn(gov?'太守':'任命太守','governor',g.id,'small secondary',gov||busy):''}</div></section>`;}).join('')}</div><div class="notice" style="margin-top:18px">主将的勇武提高部队攻击，统御降低受到的伤害，并为擅长兵种额外增加 12% 攻击。统率影响属性覆盖范围（试玩公式：每点有效统率影响 100 士兵）。太守的内政提高城内生产。</div>`;}
function reportsPage(){return `<div class="page-head"><div><h2>沙场纪事</h2><p class="sub">保存最近 20 次战斗，观察配兵与指挥的结果。</p></div><span class="badge">胜利 ${S().stats.victories} 次</span></div>${S().reports.length?S().reports.map(r=>`<article class="report"><div class="report-top"><h3>${Game.getNode(r.node).name}</h3><span class="result ${r.won?'':'loss'}">${r.won?'胜利':r.retreated?'撤退':'战败'} · ${r.round} 回合</span></div><p class="meta">${new Date(r.id).toLocaleString('zh-CN')} · ${r.mode==='raid'?'掠夺':'占领'}${r.claimed?' · 取得归属':''}${r.moraleAfter!==null&&r.moraleAfter!==undefined?' · 民心 '+r.moraleBefore+' → '+r.moraleAfter:''} · 主将 ${Game.general(r.general).name}</p>${battleCargoHTML(r)}${lootHtml(r.loot)}${battleDropsHTML(r)}${r.overflow?`<p class="hint">仓库已满，${num(r.overflow)} 资源未能入库。</p>`:''}<p class="hint">永久损失 ${Game.totalArmy(r.lost)} · 伤兵归队 ${Game.totalArmy(r.wounded)} · ${r.stationed?'留守':'返城'} ${Game.totalArmy(r.back)} 人 · 武将经验 +${r.xp}</p></article>`).join(''):'<div class="panel empty-report"><div class="glyph">册</div><h3>尚无战报</h3><p class="sub">前往天下，派遣你的第一支部队。</p><div style="margin-top:20px">'+btn('查看山河图','nav','world')+'</div></div>'}`;}
function citySettings(){manualGovernmentModal('comfort');}
function cityTaxSettings(){showModal('官府 · 任命与税率',`${governmentSummary()}${governmentNav('settings')}<p class="label">任命太守</p><select id="governor-select" aria-label="任命太守">${S().generals.filter(id=>!Game.generalBusy(id)).map(id=>`<option value="${id}" ${id===S().governor?'selected':''}>${Game.general(id).name} · 内政 ${Game.general(id).pol}</option>`).join('')}</select><div class="settings-row"><label for="tax-range">税率 <strong id="tax-value">${S().tax}%</strong></label><input id="tax-range" type="range" min="0" max="100" step="1" value="${S().tax}"><p class="hint">目标民心 = 100 − 税率。民心逐渐变化并影响人口；劳动人口不足时资源产出下降。人口变化速度、税收公式为试玩值。</p></div>`,btn('取消','close','','secondary')+btn('确认调整','citySettingsSave'));}
function settings(){showModal('设置与帮助',`<p class="sub">三国城志 · 单机 PVE v0.13.0</p><ol class="help-list"><li><strong>发展城池：</strong>先领取新版礼包与任务补给，按任务完成民房、军营和校场；资源田补充日常产出。</li><li><strong>训练士兵：</strong>为出征准备兵力，民房提供人口，资源田占用劳动人口，训练消耗空闲人口。</li><li><strong>配将出征：</strong>太守留守城池，另一位武将率军前往据点。</li><li><strong>指挥取胜：</strong>每 30 秒推进一回合，也可点击「下一回合」立即结算。胜利有机会掉落商城道具和额外资源，强敌奖励更高。枪克骑、骑克弓、盾抗箭。掠夺抢资源，占领取得归属与产量加成；野地驻军可召回。</li></ol><div class="notice">浏览器关闭后，资源最多累积 8 小时，建造和训练仍会完成。战斗与自动指挥只在页面运行时推进。进度保存在当前浏览器，清除网站数据会删除进度。</div><div class="settings-row">${btn('试玩倍率 ×'+S().speed,'manualSpeed','','secondary block')}</div><section class="panel"><h3>测试工具</h3><p class="hint">点击一次，粮食、木材、石料、铁锭和黄金各增加 ${num(RewardData.testSupplyAmount)}。可重复点击，允许暂时超过仓储容量。</p>${btn('测试补给 · 五种资源各 +100 万','testSupplies','','block')}</section><div class="settings-row">${btn('导出存档','exportSave','','secondary block')}</div><div class="settings-row"><label for="import-file">导入存档</label><input id="import-file" type="file" accept="application/json,.json"></div><div class="divider"></div>${btn('重新开始','resetAsk','','danger block')}`,btn('继续游戏','close'));}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id;switch(a){case 'close':modal.close();break;case 'nav':page=id;render();window.scrollTo({top:0,behavior:'smooth'});break;case 'building':buildingModal(id);break;case 'upgrade':if(actResult(Game.upgrade(id),'建造队已出发'))modal.close();break;case 'mission':if(actResult(Game.claimMission(id),'目标达成，奖励已收入仓库')){if(modal.open&&[classicMissionModal,growthMissionModal].includes(manualModalContext))classicMissionModal();}break;case 'trainModal':trainModal(id);break;case 'train':if(actResult(Game.train(id,Number(document.getElementById('train-number').value)),'已加入训练队列'))modal.close();break;case 'node':selectedNode=id;render();break;case 'dispatchModal':dispatchModal(id);break;case 'dispatch':if(actResult(Game.dispatch(id,document.getElementById('dispatch-general').value,dispatchArmy(),document.getElementById('dispatch-mode').value),'部队已出征'))modal.close();break;case 'battleStart':actResult(Game.startBattle());autoLast=Date.now();break;case 'recall':showModal('召回部队', '<p class="sub">取消本次行军，部队将在 5 秒后返回。行军消耗的粮食不返还。</p>',btn('继续行军','close','','secondary')+btn('确认召回','recallConfirm'));break;case 'recallConfirm':actResult(Game.recall(),'部队正在返城');modal.close();break;case 'battleRound':advanceBattleRound();break;case 'battleAuto':if(S().battle&&!S().battle.finished){S().battle.auto=!S().battle.auto;Game.save();autoLast=Date.now();render();}break;case 'battleDismiss':Game.dismissBattle();render();break;case 'governor':actResult(Game.setGovernor(id),`${Game.general(id).name} 已任命为太守`);break;case 'citySettings':citySettings();break;case 'citySettingsSave':Game.setTax(document.getElementById('tax-range').value);if(actResult(Game.setGovernor(document.getElementById('governor-select').value),'城务已调整'))modal.close();break;case 'settings':settings();break;case 'testSupplies':{const error=Game.grantTestSupplies();if(!error)settings();actResult(error,'测试补给已到账：四资源及黄金各 +100 万');break;}case 'resetAsk':showModal('重新开始？','<p class="sub">将清除本浏览器的城池、军队、武将成长和战报。可以先导出存档。</p>',btn('保留进度','close','','secondary')+btn('继续确认','resetConfirmAsk','','danger'));break;case 'resetConfirmAsk':showModal('最后确认','<p class="sub">确定删除当前存档并回到初始城池？此操作无法撤销。</p>',btn('取消','close','','secondary')+btn('删除存档并重开','resetFinal','','danger'));break;case 'resetFinal':Game.reset();page='city';modal.close();render();toast('新城池已建立');break;case 'exportSave':{Game.save();const blob=new Blob([JSON.stringify(S(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`三国城志-存档-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出');break;}}});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='train-range'){document.getElementById('train-number').value=el.value;updateTrain();}if(el.id==='train-number')updateTrain();if(el.dataset.armyRange){const n=modalBody.querySelector(`[data-army-number="${el.dataset.armyRange}"]`);n.value=el.value;updateDispatch();}if(el.dataset.armyNumber){const value=Math.max(0,Math.min(Number(el.max),Math.floor(Number(el.value)||0)));el.value=value;modalBody.querySelector(`[data-army-range="${el.dataset.armyNumber}"]`).value=value;updateDispatch();}if(el.id==='tax-range')document.getElementById('tax-value').textContent=el.value+'%';});
document.addEventListener('change',async event=>{const el=event.target;if(el.id==='dispatch-general')updateDispatch();if(el.id==='dispatch-mode')updateCampaignPreview();if(el.id==='import-file'&&el.files[0]){try{const data=Game.migrateSave(JSON.parse(await el.files[0].text()));if(!validSave(data))throw new Error('存档格式不匹配');pendingImport=data;showModal('导入存档', '<p class="sub">这将替换当前进度。确认使用文件中的城池存档？</p>',btn('取消','close','','secondary')+btn('确认导入','importConfirm'));}catch{toast('无法读取存档，请选择本游戏导出的 JSON 文件');el.value='';}}});
let pendingImport=null;
function validSave(d){try{return Game.validSave(d);}catch{return false;}}
document.addEventListener('click',e=>{if(e.target.closest('[data-action="importConfirm"]')&&pendingImport){try{Game.importSave(pendingImport);pendingImport=null;modal.close();page='city';render();toast('存档已导入');}catch{toast('导入失败，请检查浏览器存储权限');}}});
function refreshValues(){document.querySelectorAll('[data-stock-fill]').forEach(el=>{el.style.width=Math.min(100,S().res[el.dataset.stockFill]/Game.capacity(el.dataset.stockFill)*100)+'%';});document.querySelectorAll('[data-battle-timer]').forEach(el=>{const text=battleTimerText();if(el.textContent!==text)el.textContent=text;});document.querySelectorAll('[data-auto-upgrade-status]').forEach(el=>{const status=Game.autoUpgradeStatus();if(el.textContent!==status)el.textContent=status;});document.querySelectorAll('[data-population]').forEach(el=>el.textContent=num(S().population)+' / '+num(Game.maxPop()));document.querySelectorAll('[data-free-pop]').forEach(el=>el.textContent=num(Game.freePopulation()));document.querySelectorAll('[data-morale]').forEach(el=>el.textContent=Math.round(S().morale));document.querySelectorAll('[data-unrest]').forEach(el=>el.textContent=Math.round(S().unrest));refreshGovernmentQuotes();updateSpeedupPreview();const rates=Game.rates();document.querySelectorAll('[data-res]').forEach(el=>el.textContent=num(S().res[el.dataset.res]));document.querySelectorAll('[data-rate]').forEach(el=>{const v=rates[el.dataset.rate];el.textContent=`${v>=0?'+':''}${Math.round(v*60)}/时`;el.classList.toggle('negative',v<0);});document.querySelectorAll('[data-plot-rate]').forEach(el=>{const type=el.dataset.plotRate;el.textContent='+'+Math.round(S().plots.filter(p=>p.type===type).reduce((v,p)=>v+Game.plotYield(p)*60,0))+'/时';});document.querySelectorAll('[data-clock]').forEach(el=>el.textContent=duration((Number(el.dataset.clock)-Date.now())/1000));document.querySelectorAll('[data-progress-end]').forEach(el=>{const start=Number(el.dataset.progressStart),end=Number(el.dataset.progressEnd);el.style.width=`${Math.min(100,Math.max(0,(Date.now()-start)/(end-start)*100))}%`;});}
function signature(){const s=S();return JSON.stringify([s.prestige,s.copper,s.jewels,s.captives,s.activityMetrics,s.epic,s.daily,s.daily.tasks.map(t=>Game.progression.taskReady(s,t)),Object.keys(Game.resources).map(id=>s.res[id]>=100000),s.starterGiftVersion,s.civicCooldowns,Object.values(s.civicCooldowns).map(end=>end>Date.now()),s.governor,s.tax,s.unrest,s.missionClaims,Game.missions.map(m=>Game.missionReady(m)),s.autoUpgrade,s.buildings,s.cityLayout,s.cityLevels,s.tech,s.speed,s.researchQueue,s.buildQueue.map(q=>[q.start,q.end]),s.trainQueue.map(q=>[q.start,q.end]),s.defenseQueue.length,s.inventory,s.gems,Object.keys(s.buffs).filter(k=>s.buffs[k].end>Date.now()),Date.now()-s.trialGiftAt>=86400000,s.innCandidates,s.generals,s.conquered,s.garrisons,s.towns,s.plots,s.army,s.buildQueue.length,s.trainQueue.length,Game.allExpeditions().map(e=>[e.node,e.phase,e.end<=Date.now()]),!!(s.expedition&&s.expedition.end<=Date.now()),Object.entries(s.cooldowns).filter(([,end])=>end>Date.now()).map(([id])=>id)]);}
let previous=signature(),saveLast=0;
setInterval(()=>{Game.tick();const b=S().battle;if(b?.auto&&!b.finished&&Date.now()-autoLast>=BATTLE_ROUND_MS){advanceBattleRound();}const next=signature();if(next!==previous){previous=next;render();if(modal.open&&manualModalContext){const refresh=manualModalContext,scroll=modal.scrollTop;refresh();modal.scrollTop=scroll;}}else {refreshValues();progressionRefreshValues();}if(Date.now()-saveLast>5000){Game.save();saveLast=Date.now();}},500);
document.addEventListener('visibilitychange',()=>{if(document.hidden)Game.save();else{Game.tick();render();}});window.addEventListener('pagehide',()=>Game.save());
render();if(offline)showModal('城池仍在发展',`<p class="sub">离开 ${duration(offline.seconds)}，百姓已将产出收入仓库。</p>${lootHtml(offline.gain)}<p class="hint">最多累积 8 小时，超出仓储上限的资源不再生产。建造与训练也已结算。</p>`,btn('回到城池','close'));if(!Game.save())toast('浏览器存储不可用，关闭页面后进度无法保存');
