'use strict';
const BattlefieldSystem=(()=>{
  const CONFIG_VERSION=1,RENT_UNITS=['militia','spear','shield','archer','cavalry'];
  const object=x=>!!x&&typeof x==='object'&&!Array.isArray(x),integer=n=>Number.isSafeInteger(n)&&n>=0;
  const clone=x=>JSON.parse(JSON.stringify(x)),sum=a=>Object.values(a).reduce((a,b)=>a+b,0),empty=()=>({version:1,seq:0,starterClaimed:false,run:null,daily:{},firstClears:{},relics:{},lastReceipt:null});
  const blank=api=>Object.fromEntries(Object.keys(api.units).map(id=>[id,0]));
  function troopStats(id,tech,buffs){const u=ManualData.units[id];return {hp:Math.round(u.hp*(1+tech.supply*.05)),atk:Math.round(u.atk*(1+tech.combat*.05)*(buffs.drum?1.1:1)),def:Math.round(u.def*(1+tech.protection*.05)*(buffs.formation?1.1:1)),range:Math.round(u.range*(u.range>=1000?1+tech.shooting*.05:1)),speed:Math.round(u.speed*(u.kind==='infantry'?1+tech.march*.1:1+tech.riding*.05))};}
  function init(s){if(s.battlefields===undefined)s.battlefields=empty();const r=s.battlefields?.run;if(object(r)){if(r.infiltration===undefined)r.infiltration={};if(object(r.battle)&&r.battle.route===undefined)r.battle.route='normal';}}
  function armyValid(a,api){return object(a)&&Object.keys(a).length===Object.keys(api.units).length&&Object.keys(api.units).every(id=>integer(a[id])&&(RENT_UNITS.includes(id)||a[id]===0));}
  function selection(a,allowed,api,nonzero=false){if(!object(a)||Object.keys(a).some(id=>!allowed.includes(id)||!integer(a[id])))return null;const out={...blank(api),...a};return sum(out)<=800&&(!nonzero||sum(out)>0)?out:null;}
  function active(s){return s.battlefields?.run;}
  function locked(s){return !!active(s)?.battle&&!active(s).battle.finished;}
  function quote(s,general,army,api,campaign='yellow_turban'){
    const c=BattlefieldData.config(campaign);
    const selected=selection(army,RENT_UNITS,api,true),city=api.city(api.currentCity),bf=s.battlefields||empty();
    let reason=!c?'未知剧本':campaign==='nanman'&&!bf.firstClears.yellow_turban?'需要首次完整通关黄巾之乱':!api.enabled?'剧本战场仅在单机模式开放':bf.run?'已有战役，请继续或放弃':!city||city.buildings.hall<3||city.buildings.drill<1?'需要本城官府3级、校场1级':!s.generals.includes(general)||api.heroCity(general)!==api.currentCity?'请选择本城将领':api.generalBusy(general)||api.role(general)?'将领出征、驻守或任职中':(s.generalLevels[general]||1)<c.minLevel?'需要将领'+c.minLevel+'级':!selected?'选择1至800名租兵':Object.entries(selected).some(([id,n])=>n&&!api.unlocked(id))?'租兵兵种尚未解锁':(s.inventory.reinforcementToken||0)<1?'需要援军令×1':'';
    const key=JSON.stringify([bf.seq,api.currentCity,general,selected,campaign]);return {reason,key,army:selected,pool:3000,cost:1,limit:800};
  }
  function start(s,general,army,key,api,campaign='yellow_turban'){const q=quote(s,general,army,api,campaign);if(q.reason)return q.reason;if(q.key!==key)return '租兵方案已变化，请重新确认';const bf=s.battlefields;s.inventory.reinforcementToken--;bf.seq++;const frozen=api.freeze(api.currentCity);bf.run={id:BattlefieldData.config(campaign).prefix+':'+bf.seq,campaign,configVersion:CONFIG_VERSION,sourceCity:api.currentCity,general,startedAt:api.now,completed:[],selectedNode:null,army:q.army,pool:3000-sum(q.army),wounded:blank(api),medicalQuota:0,battle:null,techSnapshot:frozen.tech,troopBuffs:frozen.buffs,unitSnapshot:frozen.units,unlocked:frozen.unlocked,routeDiscovered:false,infiltration:{}};return null;}
  function enter(s,id,choice,api){const r=active(s),n=BattlefieldData.get(id,r?.campaign);if(!r)return '尚未开始战役';const c=BattlefieldData.config(r.campaign);if(locked(s))return '请先结束当前战场战斗';if(choice!=='normal'&&!(choice==='hidden'&&id===c.discover&&r.routeDiscovered)&&!(choice==='infiltration'&&r.infiltration[id]==='infiltration'))return '该进入方式尚未开放';if(r.infiltration[id]&&choice!==r.infiltration[id])return '请沿已确认的潜入结果进入';if(!n||!BattlefieldData.available(r.completed,r.campaign).includes(id))return '地点未开放或已完成';if(n.dialogue){r.completed.push(id);r.medicalQuota+=200;r.selectedNode=null;r.battle=null;return null;}if(!sum(r.army))return '租兵编队已全灭，请补租或放弃本轮';r.selectedNode=id;r.battle=null;return null;}
  function attemptInfiltration(s,id,answer,api){const r=active(s);if(!r)return '请先开始本轮战役';const c=BattlefieldData.config(r.campaign);if(locked(s)||r.selectedNode)return '请先结束当前地点战斗';if(id!==c.infiltration||!BattlefieldData.available(r.completed,c.id).includes(id))return '当前地点不能潜入';if(r.infiltration[id])return '本轮此处已尝试潜入，请沿结果继续';if(!s.equipment.some(e=>e.relic==='mask'&&e.hero===r.general))return '请为本轮主将穿戴易容面具';if(!['forest','river','rise','return'].includes(answer)||c.id==='nanman'&&!['forest','river','return'].includes(answer)||c.id==='yellow_turban'&&!['rise','river','return'].includes(answer))return '请选择有效的口令';r.infiltration[id]=answer===c.answer?'infiltration':'normal';return null;}
  function reinforce(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能补租';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(r.army)+sum(chosen)>800)return '补租后编队需在1至800人范围';if(sum(chosen)>r.pool)return '本轮补租池不足，可做救援支线或放弃';for(const id of Object.keys(r.army))r.army[id]+=chosen[id];r.pool-=sum(chosen);r.battle=null;r.selectedNode=null;return null;}
  function heal(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能救治';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(chosen)>r.medicalQuota||Object.keys(chosen).some(id=>chosen[id]>r.wounded[id]))return '救治数量超过伤兵或军医额度';for(const id of Object.keys(chosen))r.wounded[id]-=chosen[id];r.medicalQuota-=sum(chosen);r.pool+=sum(chosen);return null;}
  function abandon(s,id){const r=active(s);if(!r||r.id!==id)return '战役编号已变化';s.battlefields.run=null;return null;}
  function view(s,api,campaign='yellow_turban'){
    const bf=s.battlefields||empty(),r=bf.run,c=BattlefieldData.config(r?.campaign||campaign),completed=r?.completed||[],available=c?BattlefieldData.available(completed,c.id):[];
    const reason=!c?'未知剧本':!api.enabled?'剧本战场仅在单机模式开放':c.id==='nanman'&&!bf.firstClears.yellow_turban?'需要首次完整通关黄巾之乱':api.city(api.currentCity)?.buildings.hall<3||api.city(api.currentCity)?.buildings.drill<1?'需要本城官府3级、校场1级':'';
    return {enabled:api.enabled,campaign:c,entryReason:reason,run:r?clone(r):null,nodes:c?[...c.mainIds,...c.sideIds].map(id=>({...BattlefieldData.get(id,c.id),completed:completed.includes(id),available:available.includes(id),reason:completed.includes(id)?'已完成':available.includes(id)?'':'先完成前置主线'})):[],reward:c?BattlefieldData.reward(completed,c.id):{prestige:0,xp:0},tokens:s.inventory.reinforcementToken||0,boxes:c?(s.inventory[c.boxItem]||0):0,starterClaimed:bf.starterClaimed,relics:clone(bf.relics),lastReceipt:bf.lastReceipt?clone(bf.lastReceipt):null};
  }
  const BOX_SLOTS=['weapon','helmet','armor','cloak','bracer','boots','mount'];
  function openBox(s,api,campaign='yellow_turban'){const c=BattlefieldData.config(campaign);if(!c)return '未知剧本装备箱';if(!(s.inventory[c.boxItem]>0))return '没有对应装备箱';if(s.equipment.length>=s.equipmentCapacity)return '装备库已满，箱子保留在背包';const slot=BOX_SLOTS[Math.floor(Math.random()*BOX_SLOTS.length)],e=HeroSystem.addEquipment(s,slot,c.tier);e.setId=c.setId;s.inventory[c.boxItem]--;return null;}
  function claimRelic(s,id,api){if(!['compass','mask'].includes(id)||!s.battlefields.relics[id]?.unlocked)return '尚未取得奇物线索';if(s.battlefields.relics[id].claimed)return '此奇物已领取';if(s.equipment.length>=s.equipmentCapacity)return '装备库已满，领取资格保留';const e=HeroSystem.addEquipment(s,'accessory',1);e.relic=id;s.battlefields.relics[id].claimed=true;return null;}
  function discoverRoute(s,api){const r=active(s);if(!r)return '请先开始本轮战役';const c=BattlefieldData.config(r.campaign);if(locked(s))return '请先结束当前战斗';if(r.routeDiscovered)return '本轮已探明隐藏入口';if(r.completed.includes(c.discover))return '探索支线已完成';if(!s.equipment.some(e=>e.relic==='compass'&&e.hero===r.general))return '请为本轮主将穿戴寻踪罗盘';r.routeDiscovered=true;return null;}
  const dayKey=now=>new Date(now+8*3600000).toISOString().slice(0,10);
  function entryReason(s,api){const c=api.city(api.currentCity);return !api.enabled?'剧本战场仅在单机模式开放':!c||c.buildings.hall<3||c.buildings.drill<1?'需要本城官府3级、校场1级':'';}
  function claimStarterToken(s,api){const error=entryReason(s,api);if(error)return error;if(s.battlefields.starterClaimed)return '首次援军令已领取';if((s.inventory.reinforcementToken||0)>=Number.MAX_SAFE_INTEGER)return '援军令数量已达上限';s.inventory.reinforcementToken=(s.inventory.reinforcementToken||0)+1;s.battlefields.starterClaimed=true;return null;}
  function buyToken(s,api){const error=entryReason(s,api);if(error)return error;if(s.res.gold<2500)return '黄金不足，需要2500黄金';if((s.inventory.reinforcementToken||0)>=Number.MAX_SAFE_INTEGER)return '援军令数量已达上限';s.res.gold-=2500;s.inventory.reinforcementToken=(s.inventory.reinforcementToken||0)+1;return null;}
  function settle(s,r,now,api){const bf=s.battlefields,c=BattlefieldData.config(r.campaign);if(bf.run!==r||!r.completed.includes(c.finalNode)||!r.battle?.finished||!r.battle.result?.won)return '尚未完成整轮战役';const day=dayKey(now),prior=bf.daily[r.campaign],count=prior?.day===day?prior.count+1:1,first=count===1,base=BattlefieldData.reward(r.completed,r.campaign),prestige=first?base.prestige:Math.floor(base.prestige/2),xp=first?base.xp:Math.floor(base.xp/2);
    s.prestige+=prestige;api.addXp(r.general,xp);if(first)s.inventory[c.boxItem]=(s.inventory[c.boxItem]||0)+1;
    const receipt={runId:r.id,campaign:r.campaign,general:r.general,sourceCity:r.sourceCity,day,at:now,completed:[...r.completed],prestige,xp,box:first?1:0,battleResult:JSON.parse(JSON.stringify(r.battle.result))};bf.daily[r.campaign]={day,count};if(!bf.firstClears[r.campaign])bf.firstClears[r.campaign]={at:now,runId:r.id};bf.lastReceipt=receipt;bf.run=null;return null;
  }
  function validFinalResult(r){return object(r)&&Object.keys(r).length===(r.facts===undefined?5:6)&&r.won===true&&integer(r.round)&&r.round<=30&&[r.back,r.lost,r.recovered].every(a=>object(a)&&Object.keys(a).length===Object.keys(ManualData.units).length&&Object.entries(a).every(([id,n])=>Object.hasOwn(ManualData.units,id)&&integer(n)))&&Object.keys(r.lost).every(id=>r.recovered[id]===Math.floor(r.lost[id]*.6))&&(r.facts===undefined||BattleReview.validFacts(r.facts)&&r.facts.endedBy==='win'&&r.facts.rounds===r.round);}
  function validRewards(bf){
    const date=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
    const idValid=(id,c)=>{const prefix=c.prefix+':';return typeof id==='string'&&id.startsWith(prefix)&&/^[1-9]\d*$/.test(id.slice(prefix.length))&&integer(Number(id.slice(prefix.length)))&&Number(id.slice(prefix.length))<=bf.seq;};
    if([...Object.keys(bf.daily),...Object.keys(bf.firstClears)].some(k=>!BattlefieldData.config(k))||Object.keys(bf.relics).some(k=>k!=='compass'&&k!=='mask'))return false;
    for(const relic of Object.values(bf.relics))if(!object(relic)||Object.keys(relic).length!==2||relic.unlocked!==true||typeof relic.claimed!=='boolean')return false;
    for(const c of BattlefieldData.catalog().map(x=>BattlefieldData.config(x.id))){const daily=bf.daily[c.id],first=bf.firstClears[c.id];if(daily!==undefined&&(!object(daily)||Object.keys(daily).length!==2||!date(daily.day)||!integer(daily.count)||daily.count<1)||first!==undefined&&(!object(first)||Object.keys(first).length!==2||!integer(first.at)||!idValid(first.runId,c)))return false;if((daily===undefined)!==(first===undefined))return false;}
    const last=bf.lastReceipt;if(last===null)return !Object.keys(bf.daily).length&&!Object.keys(bf.firstClears).length;
    const c=BattlefieldData.config(last?.campaign);if(!c)return false;const daily=bf.daily[c.id],first=bf.firstClears[c.id];
    if(!object(last)||(last.battleResult===undefined?Object.keys(last).length!==10:Object.keys(last).length!==11||!validFinalResult(last.battleResult))||!idValid(last.runId,c)||!integer(last.at)||!date(last.day)||dayKey(last.at)!==last.day||typeof last.general!=='string'||last.general.length>100||typeof last.sourceCity!=='string'||last.sourceCity.length>100||!BattlefieldData.validCompleted(last.completed,c.id)||!last.completed.includes(c.finalNode)||!daily||!first||daily.day!==last.day||first.at>last.at)return false;
    const reward=BattlefieldData.reward(last.completed,c.id),isFirst=daily.count===1;return last.prestige===(isFirst?reward.prestige:Math.floor(reward.prestige/2))&&last.xp===(isFirst?reward.xp:Math.floor(reward.xp/2))&&last.box===(isFirst?1:0);
  }
  function nodeForRun(r,id,route='normal'){
    const c=BattlefieldData.config(r.campaign),n=BattlefieldData.get(id,r.campaign);if(!n||!c)return null;n.route=route;n.armyAttack={};n.commander={name:n.name,title:c.name,attack:1,defense:1};
    if(c.id==='yellow_turban'){if(id==='m3'&&!r.completed.includes('s2'))n.commander.attack=1.05;if(id==='m9'&&!r.completed.includes('s6'))n.commander.defense=1.1;if(id==='s6'&&route==='infiltration')delete n.army.archer;}
    else {if(id==='n3'&&!r.completed.includes('b2'))n.armyAttack.archer=1.08;if(id==='n6'&&!r.completed.includes('b3'))n.commander.defense=1.12;if(id==='n9'&&!r.completed.includes('b6'))n.commander.defense=1.1;if(id==='b2'&&route==='hidden'||id==='b6'&&route==='infiltration')delete n.army.archer;}
    return n;
  }
  function finishNode(s,b,won,api,endedBy){const r=active(s);if(!r||r.battle!==b||b.finished||b.runId!==r.id||r.selectedNode!==b.node)return '战场快照不匹配';const back=blank(api),lost=blank(api),recovered=blank(api);
    for(const row of b.player){back[row.id]=Math.ceil(row.hp/row.stats.hp);lost[row.id]=row.initial-back[row.id];recovered[row.id]=Math.floor(lost[row.id]*.6);r.wounded[row.id]+=lost[row.id]-recovered[row.id];r.pool+=recovered[row.id];}
    const facts=BattleReview.finishFacts(b,won,endedBy);if(facts)b.facts={...facts};
    r.army=back;b.finished=true;b.result={...(facts?{facts}:{}),won,back,lost,recovered,round:b.round};
    if(won){const c=BattlefieldData.config(r.campaign);r.completed.push(b.node);r.selectedNode=null;if(c.rescue.includes(b.node))r.pool+=500;if(b.node===c.relicNode&&!s.battlefields.relics[c.relic])s.battlefields.relics[c.relic]={unlocked:true,claimed:false};if(b.node===c.finalNode)return settle(s,r,api.now,api);}
    return null;
  }
  function battleValid(b,r,api){
    if(!object(b)||(b.facts!==undefined&&(!BattleReview.validFacts(b.facts)||b.facts.rounds!==b.round||b.finished&&JSON.stringify(b.facts)!==JSON.stringify(b.result?.facts)))||b.kind!=='battlefield'||b.runId!==r.id||b.general!==r.general||b.sourceCity!==r.sourceCity||b.rules!==3||b.mode!=='raid'||b.siege!==false||b.gate!==null||!integer(b.round)||b.round>30||typeof b.finished!=='boolean'||typeof b.auto!=='boolean'||!integer(b.length)||b.length<200||b.length>10000||!HeroSystem.validMountProfile(b.mountProfile)||!GeneralGrowth.validProfile(b.skillProfile)||!object(b.generalSnapshot)||b.generalSnapshot.id!==r.general||!['atk','def','pol','wis','lead'].every(k=>Number.isFinite(b.generalSnapshot[k])&&b.generalSnapshot[k]>=0&&b.generalSnapshot[k]<=1e9)||!Number.isFinite(b.legendProcChance)||b.legendProcChance<0||b.legendProcChance>1)return false;
    const c=BattlefieldData.config(r.campaign),n=nodeForRun(r,b.node,b.route);if(!n||n.dialogue||!['normal','hidden','infiltration'].includes(b.route)||b.route==='hidden'&&(b.node!==c.discover||!r.routeDiscovered)||b.route==='infiltration'&&r.infiltration[b.node]!=='infiltration'||r.infiltration[b.node]&&b.route!==r.infiltration[b.node]||!Array.isArray(b.player)||!Array.isArray(b.enemy)||!b.player.length||!b.enemy.length||!object(b.orders)||!object(b.enemyOrders)||!Array.isArray(b.log)||b.log.length>40||b.log.some(x=>typeof x!=='string'||x.length>1000)||!BattleStratagems.valid(b,api))return false;
    if(b.finished?(b.result?.won?!r.completed.includes(b.node):r.selectedNode!==b.node):r.selectedNode!==b.node||!BattlefieldData.available(r.completed,r.campaign).includes(b.node))return false;
    if(!BattlefieldData.validCompleted(b.completedBefore,r.campaign)||JSON.stringify(b.completedBefore)!==JSON.stringify(r.completed.filter(id=>!(b.finished&&b.result?.won&&id===b.node))))return false;
    const bonus=b.completedBefore.includes('s3')?1.08:1;
    for(const [side,rows,orders] of [['player',b.player,b.orders],['enemy',b.enemy,b.enemyOrders]]){
      if(new Set(rows.map(row=>row.id)).size!==rows.length||Object.keys(orders).length!==rows.length)return false;
      for(const row of rows){const base=side==='player'?r.unitSnapshot[row.id]:api.units[row.id],expected=base?{hp:base.hp,atk:base.atk*(side==='player'?bonus:n.armyAttack[row.id]||1),def:base.def,speed:base.speed,range:base.range}:null;
        if(!expected||!RENT_UNITS.includes(row.id)||!integer(row.initial)||row.initial<1||row.initial>800||!object(row.stats)||Object.entries(expected).some(([k,v])=>row.stats[k]!==v)||!HeroSystem.validSpeedStats(row.stats,row.id,b.mountProfile,side==='player')||!Number.isFinite(row.hp)||row.hp<0||row.hp>row.initial*row.stats.hp||row.maxHp!==row.initial*row.stats.hp||!Number.isFinite(row.pos)||row.pos<0||row.pos>b.length||typeof row.defending!=='boolean'||!object(orders[row.id])||!['advance','hold','fallback'].includes(orders[row.id].command)||typeof orders[row.id].target!=='string'||orders[row.id].target!==''&&!(side==='player'?b.enemy:b.player).some(x=>x.id===orders[row.id].target))return false;
        if(side==='enemy'&&n.army[row.id]!==row.initial||side==='player'&&!b.finished&&r.army[row.id]!==row.initial)return false;
      }
    }
    if(b.enemy.length!==Object.keys(n.army).length)return false;
    if(!b.finished)return b.result===null&&b.player.length===Object.values(r.army).filter(n=>n>0).length;
    const result=b.result;if(!object(result)||(result.facts!==undefined&&(!BattleReview.validFacts(result.facts)||result.facts.endedBy==='ongoing'||(result.won?result.facts.endedBy!=='win':result.facts.endedBy==='win')||result.facts.rounds!==b.round))||typeof result.won!=='boolean'||result.round!==b.round||![result.back,result.lost,result.recovered].every(a=>armyValid(a,api))||JSON.stringify(result.back)!==JSON.stringify(r.army))return false;
    if(result.won&&(!b.player.some(row=>row.hp>0)||b.enemy.some(row=>row.hp>0)))return false;
    return Object.keys(api.units).every(id=>{const row=b.player.find(row=>row.id===id),back=row?Math.ceil(row.hp/row.stats.hp):0,lost=row?row.initial-back:0;return result.back[id]===back&&result.lost[id]===lost&&result.recovered[id]===Math.floor(lost*.6);});
  }
  function valid(s,api){const bf=s.battlefields;if(!object(bf)||bf.version!==1||!integer(bf.seq)||typeof bf.starterClaimed!=='boolean'||![bf.daily,bf.firstClears,bf.relics].every(object)||!validRewards(bf))return false;
    const r=bf.run;if(r===null)return true;const c=BattlefieldData.config(r?.campaign);if(!c)return false;if(!object(r)||r.id!==c.prefix+':'+bf.seq||bf.seq<1||r.configVersion!==1||!integer(r.startedAt)||!api.city(r.sourceCity)||!s.generals.includes(r.general)||api.heroCity(r.general)!==r.sourceCity||api.otherBusy(r.general)||api.role(r.general)||!BattlefieldData.validCompleted(r.completed,c.id)||r.completed.includes(c.finalNode)||!armyValid(r.army,api)||sum(r.army)>800||!armyValid(r.wounded,api)||!integer(r.pool)||!integer(r.medicalQuota)||r.medicalQuota>200||typeof r.routeDiscovered!=='boolean'||!object(r.infiltration)||Object.keys(r.infiltration).some(id=>id!==c.infiltration||!['normal','infiltration'].includes(r.infiltration[id])||!bf.relics.mask?.claimed||!BattlefieldData.get(id,c.id).requires.every(dep=>r.completed.includes(dep)))||r.routeDiscovered&&!bf.relics.compass?.claimed||!Array.isArray(r.unlocked)||new Set(r.unlocked).size!==r.unlocked.length||r.unlocked.some(id=>!RENT_UNITS.includes(id))||Object.entries(r.army).some(([id,n])=>n&&!r.unlocked.includes(id))||!object(r.techSnapshot)||Object.keys(r.techSnapshot).length!==Object.keys(ManualData.technology).length||Object.keys(ManualData.technology).some(id=>!integer(r.techSnapshot[id])||r.techSnapshot[id]>10)||!object(r.troopBuffs)||Object.keys(r.troopBuffs).length!==2||!['drum','formation'].every(k=>typeof r.troopBuffs[k]==='boolean')||!object(r.unitSnapshot))return false;
    const quota=c.pool+500*c.rescue.filter(id=>r.completed.includes(id)).length;if(sum(r.army)+sum(r.wounded)+r.pool!==quota||r.medicalQuota> (r.completed.includes(c.medical)?200:0))return false;
    if(r.selectedNode!==null&&!BattlefieldData.available(r.completed,c.id).includes(r.selectedNode))return false;
    if(Object.keys(r.unitSnapshot).length!==RENT_UNITS.length||RENT_UNITS.some(id=>!object(r.unitSnapshot[id])||Object.keys(r.unitSnapshot[id]).length!==5||!['hp','atk','def','speed','range'].every(k=>Number.isFinite(r.unitSnapshot[id][k])&&r.unitSnapshot[id][k]>=0&&r.unitSnapshot[id][k]<=100000)||r.unitSnapshot[id].hp<1||r.unitSnapshot[id].speed<1))return false;
    if(RENT_UNITS.some(id=>Object.entries(troopStats(id,r.techSnapshot,r.troopBuffs)).some(([k,v])=>r.unitSnapshot[id][k]!==v)))return false;
    return r.battle===null||battleValid(r.battle,r,api);
  }
  return {attemptInfiltration,BOX_SLOTS,openBox,claimRelic,discoverRoute,dayKey,buyToken,claimStarterToken,settle,troopStats,nodeForRun,finishNode,battleValid,RENT_UNITS,init,valid,view,quote,start,enter,reinforce,heal,abandon,locked,armyValid,selection,blank,sum};
})();
