'use strict';
const BattlefieldSystem=(()=>{
  const CONFIG_VERSION=1,RENT_UNITS=['militia','spear','shield','archer','cavalry'];
  const object=x=>!!x&&typeof x==='object'&&!Array.isArray(x),integer=n=>Number.isSafeInteger(n)&&n>=0;
  const clone=x=>JSON.parse(JSON.stringify(x)),sum=a=>Object.values(a).reduce((a,b)=>a+b,0),empty=()=>({version:1,seq:0,starterClaimed:false,run:null,daily:{},firstClears:{},relics:{},lastReceipt:null});
  const blank=api=>Object.fromEntries(Object.keys(api.units).map(id=>[id,0]));
  function troopStats(id,tech,buffs){const u=ManualData.units[id];return {hp:Math.round(u.hp*(1+tech.supply*.05)),atk:Math.round(u.atk*(1+tech.combat*.05)*(buffs.drum?1.1:1)),def:Math.round(u.def*(1+tech.protection*.05)*(buffs.formation?1.1:1)),range:Math.round(u.range*(u.range>=1000?1+tech.shooting*.05:1)),speed:Math.round(u.speed*(u.kind==='infantry'?1+tech.march*.1:1+tech.riding*.05))};}
  function init(s){if(s.battlefields===undefined)s.battlefields=empty();}
  function armyValid(a,api){return object(a)&&Object.keys(a).length===Object.keys(api.units).length&&Object.keys(api.units).every(id=>integer(a[id])&&(RENT_UNITS.includes(id)||a[id]===0));}
  function selection(a,allowed,api,nonzero=false){if(!object(a)||Object.keys(a).some(id=>!allowed.includes(id)||!integer(a[id])))return null;const out={...blank(api),...a};return sum(out)<=800&&(!nonzero||sum(out)>0)?out:null;}
  function active(s){return s.battlefields?.run;}
  function locked(s){return !!active(s)?.battle&&!active(s).battle.finished;}
  function quote(s,general,army,api){
    const selected=selection(army,RENT_UNITS,api,true),city=api.city(api.currentCity),bf=s.battlefields||empty();
    let reason=!api.enabled?'剧本战场仅在单机模式开放':bf.run?'已有战役，请继续或放弃':!city||city.buildings.hall<3||city.buildings.drill<1?'需要本城官府3级、校场1级':!s.generals.includes(general)||api.heroCity(general)!==api.currentCity?'请选择本城将领':api.generalBusy(general)||api.role(general)?'将领出征、驻守或任职中':(s.generalLevels[general]||1)<5?'需要将领5级':!selected?'选择1至800名租兵':Object.entries(selected).some(([id,n])=>n&&!api.unlocked(id))?'租兵兵种尚未解锁':(s.inventory.reinforcementToken||0)<1?'需要援军令×1':'';
    const key=JSON.stringify([bf.seq,api.currentCity,general,selected]);return {reason,key,army:selected,pool:3000,cost:1,limit:800};
  }
  function start(s,general,army,key,api){const q=quote(s,general,army,api);if(q.reason)return q.reason;if(q.key!==key)return '租兵方案已变化，请重新确认';const bf=s.battlefields;s.inventory.reinforcementToken--;bf.seq++;const frozen=api.freeze(api.currentCity);bf.run={id:'yellow:'+bf.seq,campaign:'yellow_turban',configVersion:CONFIG_VERSION,sourceCity:api.currentCity,general,startedAt:api.now,completed:[],selectedNode:null,army:q.army,pool:3000-sum(q.army),wounded:blank(api),medicalQuota:0,battle:null,techSnapshot:frozen.tech,troopBuffs:frozen.buffs,unitSnapshot:frozen.units,unlocked:frozen.unlocked,routeDiscovered:false};return null;}
  function enter(s,id,choice,api){const r=active(s),n=BattlefieldData.get(id);if(!r)return '尚未开始战役';if(locked(s))return '请先结束当前战场战斗';if(choice!=='normal')return '该进入方式尚未开放';if(!n||!BattlefieldData.available(r.completed).includes(id))return '地点未开放或已完成';if(n.dialogue){r.completed.push(id);r.medicalQuota+=200;r.selectedNode=null;r.battle=null;return null;}if(!sum(r.army))return '租兵编队已全灭，请补租或放弃本轮';r.selectedNode=id;r.battle=null;return null;}
  function reinforce(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能补租';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(r.army)+sum(chosen)>800)return '补租后编队需在1至800人范围';if(sum(chosen)>r.pool)return '本轮补租池不足，可做救援支线或放弃';for(const id of Object.keys(r.army))r.army[id]+=chosen[id];r.pool-=sum(chosen);r.battle=null;r.selectedNode=null;return null;}
  function heal(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能救治';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(chosen)>r.medicalQuota||Object.keys(chosen).some(id=>chosen[id]>r.wounded[id]))return '救治数量超过伤兵或军医额度';for(const id of Object.keys(chosen))r.wounded[id]-=chosen[id];r.medicalQuota-=sum(chosen);r.pool+=sum(chosen);return null;}
  function abandon(s,id){const r=active(s);if(!r||r.id!==id)return '战役编号已变化';s.battlefields.run=null;return null;}
  function view(s,api){const bf=s.battlefields||empty(),r=bf.run,available=BattlefieldData.available(r?.completed||[]),completed=r?.completed||[],reward=BattlefieldData.reward(completed);return {enabled:api.enabled,entryReason:!api.enabled?'剧本战场仅在单机模式开放':api.city(api.currentCity)?.buildings.hall<3||api.city(api.currentCity)?.buildings.drill<1?'需要本城官府3级、校场1级':'',run:r?clone(r):null,nodes:[...BattlefieldData.MAIN_IDS,...BattlefieldData.SIDE_IDS].map(id=>({...BattlefieldData.get(id),completed:completed.includes(id),available:available.includes(id),reason:completed.includes(id)?'已完成':available.includes(id)?'':'先完成前置主线'})),reward,tokens:s.inventory.reinforcementToken||0,boxes:s.inventory.yellowEquipmentBox||0,starterClaimed:bf.starterClaimed,relics:clone(bf.relics),lastReceipt:bf.lastReceipt?clone(bf.lastReceipt):null};}
  function nodeForRun(r,id){const n=BattlefieldData.get(id);if(!n)return null;n.commander={name:n.name,title:'黄巾战场',attack:id==='m3'&&!r.completed.includes('s2')?1.05:1,defense:id==='m9'&&!r.completed.includes('s6')?1.1:1};return n;}
  function finishNode(s,b,won,api){const r=active(s);if(!r||r.battle!==b||b.finished||b.runId!==r.id||r.selectedNode!==b.node)return '战场快照不匹配';const back=blank(api),lost=blank(api),recovered=blank(api);
    for(const row of b.player){back[row.id]=Math.ceil(row.hp/row.stats.hp);lost[row.id]=row.initial-back[row.id];recovered[row.id]=Math.floor(lost[row.id]*.6);r.wounded[row.id]+=lost[row.id]-recovered[row.id];r.pool+=recovered[row.id];}
    r.army=back;b.finished=true;b.result={won,back,lost,recovered,round:b.round};
    if(won){r.completed.push(b.node);r.selectedNode=null;if(['s1','s5'].includes(b.node))r.pool+=500;}
    return null;
  }
  function battleValid(b,r,api){
    if(!object(b)||b.kind!=='battlefield'||b.runId!==r.id||b.general!==r.general||b.sourceCity!==r.sourceCity||b.rules!==3||b.mode!=='raid'||b.siege!==false||b.gate!==null||!integer(b.round)||b.round>30||typeof b.finished!=='boolean'||typeof b.auto!=='boolean'||!integer(b.length)||b.length<200||b.length>10000||!HeroSystem.validMountProfile(b.mountProfile)||!GeneralGrowth.validProfile(b.skillProfile)||!object(b.generalSnapshot)||b.generalSnapshot.id!==r.general||!['atk','def','pol','wis','lead'].every(k=>Number.isFinite(b.generalSnapshot[k])&&b.generalSnapshot[k]>=0&&b.generalSnapshot[k]<=1e9)||!Number.isFinite(b.legendProcChance)||b.legendProcChance<0||b.legendProcChance>1)return false;
    const n=BattlefieldData.get(b.node);if(!n||n.dialogue||!Array.isArray(b.player)||!Array.isArray(b.enemy)||!b.player.length||!b.enemy.length||!object(b.orders)||!object(b.enemyOrders)||!Array.isArray(b.log)||b.log.length>40||b.log.some(x=>typeof x!=='string'||x.length>1000)||!BattleStratagems.valid(b,api))return false;
    if(b.finished?(b.result?.won?!r.completed.includes(b.node):r.selectedNode!==b.node):r.selectedNode!==b.node||!BattlefieldData.available(r.completed).includes(b.node))return false;
    if(!BattlefieldData.validCompleted(b.completedBefore)||JSON.stringify(b.completedBefore)!==JSON.stringify(r.completed.filter(id=>!(b.finished&&b.result?.won&&id===b.node))))return false;
    const bonus=b.completedBefore.includes('s3')?1.08:1;
    for(const [side,rows,orders] of [['player',b.player,b.orders],['enemy',b.enemy,b.enemyOrders]]){
      if(new Set(rows.map(row=>row.id)).size!==rows.length||Object.keys(orders).length!==rows.length)return false;
      for(const row of rows){const base=side==='player'?r.unitSnapshot[row.id]:api.units[row.id],expected=base?{hp:base.hp,atk:base.atk*(side==='player'?bonus:1),def:base.def,speed:base.speed,range:base.range}:null;
        if(!expected||!RENT_UNITS.includes(row.id)||!integer(row.initial)||row.initial<1||row.initial>800||!object(row.stats)||Object.entries(expected).some(([k,v])=>row.stats[k]!==v)||!HeroSystem.validSpeedStats(row.stats,row.id,b.mountProfile,side==='player')||!Number.isFinite(row.hp)||row.hp<0||row.hp>row.initial*row.stats.hp||row.maxHp!==row.initial*row.stats.hp||!Number.isFinite(row.pos)||row.pos<0||row.pos>b.length||typeof row.defending!=='boolean'||!object(orders[row.id])||!['advance','hold','fallback'].includes(orders[row.id].command)||typeof orders[row.id].target!=='string'||orders[row.id].target!==''&&!(side==='player'?b.enemy:b.player).some(x=>x.id===orders[row.id].target))return false;
        if(side==='enemy'&&n.army[row.id]!==row.initial||side==='player'&&!b.finished&&r.army[row.id]!==row.initial)return false;
      }
    }
    if(b.enemy.length!==Object.keys(n.army).length)return false;
    if(!b.finished)return b.result===null&&b.player.length===Object.values(r.army).filter(n=>n>0).length;
    const result=b.result;if(!object(result)||typeof result.won!=='boolean'||result.round!==b.round||![result.back,result.lost,result.recovered].every(a=>armyValid(a,api))||JSON.stringify(result.back)!==JSON.stringify(r.army))return false;
    if(result.won&&(!b.player.some(row=>row.hp>0)||b.enemy.some(row=>row.hp>0)))return false;
    return Object.keys(api.units).every(id=>{const row=b.player.find(row=>row.id===id),back=row?Math.ceil(row.hp/row.stats.hp):0,lost=row?row.initial-back:0;return result.back[id]===back&&result.lost[id]===lost&&result.recovered[id]===Math.floor(lost*.6);});
  }
  function valid(s,api){const bf=s.battlefields;if(!object(bf)||bf.version!==1||!integer(bf.seq)||typeof bf.starterClaimed!=='boolean'||![bf.daily,bf.firstClears,bf.relics].every(object)||bf.lastReceipt!==null||Object.keys(bf.daily).length||Object.keys(bf.firstClears).length||Object.keys(bf.relics).length)return false;
    const r=bf.run;if(r===null)return true;if(!object(r)||r.id!=='yellow:'+bf.seq||bf.seq<1||r.campaign!=='yellow_turban'||r.configVersion!==1||!integer(r.startedAt)||!api.city(r.sourceCity)||!s.generals.includes(r.general)||api.heroCity(r.general)!==r.sourceCity||api.otherBusy(r.general)||api.role(r.general)||!BattlefieldData.validCompleted(r.completed)||r.completed.includes('m9')||!armyValid(r.army,api)||sum(r.army)>800||!armyValid(r.wounded,api)||!integer(r.pool)||!integer(r.medicalQuota)||r.medicalQuota>200||typeof r.routeDiscovered!=='boolean'||!Array.isArray(r.unlocked)||new Set(r.unlocked).size!==r.unlocked.length||r.unlocked.some(id=>!RENT_UNITS.includes(id))||Object.entries(r.army).some(([id,n])=>n&&!r.unlocked.includes(id))||!object(r.techSnapshot)||Object.keys(r.techSnapshot).length!==Object.keys(ManualData.technology).length||Object.keys(ManualData.technology).some(id=>!integer(r.techSnapshot[id])||r.techSnapshot[id]>10)||!object(r.troopBuffs)||Object.keys(r.troopBuffs).length!==2||!['drum','formation'].every(k=>typeof r.troopBuffs[k]==='boolean')||!object(r.unitSnapshot))return false;
    const quota=3000+500*['s1','s5'].filter(id=>r.completed.includes(id)).length;if(sum(r.army)+sum(r.wounded)+r.pool!==quota||r.medicalQuota> (r.completed.includes('s4')?200:0))return false;
    if(r.selectedNode!==null&&!BattlefieldData.available(r.completed).includes(r.selectedNode))return false;
    if(Object.keys(r.unitSnapshot).length!==RENT_UNITS.length||RENT_UNITS.some(id=>!object(r.unitSnapshot[id])||Object.keys(r.unitSnapshot[id]).length!==5||!['hp','atk','def','speed','range'].every(k=>Number.isFinite(r.unitSnapshot[id][k])&&r.unitSnapshot[id][k]>=0&&r.unitSnapshot[id][k]<=100000)||r.unitSnapshot[id].hp<1||r.unitSnapshot[id].speed<1))return false;
    if(RENT_UNITS.some(id=>Object.entries(troopStats(id,r.techSnapshot,r.troopBuffs)).some(([k,v])=>r.unitSnapshot[id][k]!==v)))return false;
    return r.battle===null||battleValid(r.battle,r,api);
  }
  return {troopStats,nodeForRun,finishNode,battleValid,RENT_UNITS,init,valid,view,quote,start,enter,reinforce,heal,abandon,locked,armyValid,selection,blank,sum};
})();
