'use strict';
// Dedicated campaign dialogs never borrow the city battle or its action names.
const battlefieldUI=(()=>{
  const total=a=>Object.values(a||{}).reduce((n,x)=>n+x,0),slots={weapon:'武器',helmet:'头盔',armor:'铠甲',cloak:'披风',bracer:'护腕',boots:'战靴',mount:'坐骑'};
  let pending=null,selectedCampaign='yellow_turban',selectedBattle=null,selectedUnit='';
  const view=()=>Game.battlefieldView(selectedCampaign);
  const name=id=>Game.units[id]?.name||id;
  const armyHTML=a=>Object.entries(a||{}).filter(([,n])=>n).map(([id,n])=>esc(name(id))+' '+num(n)).join('、')||'无';
  const fields=(prefix,ids,defaultCount=0)=>`<div class="battlefield-inputs">${ids.map((id,i)=>`<label>${esc(name(id))}<input id="${prefix}-${id}" type="number" min="0" max="800" step="1" value="${i===0?defaultCount:0}" inputmode="numeric"></label>`).join('')}</div>`;
  const read=(prefix,ids)=>Object.fromEntries(ids.map(id=>[id,Number(document.getElementById(prefix+'-'+id)?.value||0)]));
  function notice(text){return `<p class="notice">${esc(text)}</p>`;}
  function result(error,success=''){if(typeof error==='string'&&error){toast(error);return false;}if(success)toast(success);if(typeof render==='function')render();return true;}
  function rewards(v){const first=S().battlefields.daily[v.campaign.id]?.day!==BattlefieldSystem.dayKey(Date.now()),factor=first?1:.5;return `<p class="battlefield-reward">本日${first?'首次通关：装备箱 ×1':'已通关：本轮不再发箱'} · 当前路线预计声望 ${Math.floor(v.reward.prestige*factor)} / 将领经验 ${Math.floor(v.reward.xp*factor)}</p><p class="hint">完整击败${v.campaign.id==='nanman'?'孟获':'张角'}后统一结算，已完成支线增加收益。每天以北京时间零点为界，按最终通关时间计算；同日后续声望和经验减半。</p>`;}
  function map(){
    const v=view(),r=v.run,c=v.campaign,locked=!!r?.battle&&!r.battle.finished;selectedCampaign=c.id;
    let body=`<div class="battlefield-map"><div class="battlefield-catalog">${BattlefieldData.catalog().map(item=>{const model=Game.battlefieldView(item.id),reason=r&&r.campaign!==item.id?'请先结束当前战役':!r?model.entryReason:'',today=S().battlefields.daily[item.id]?.day===BattlefieldSystem.dayKey(Date.now());return `<button class="battlefield-campaign ${c.id===item.id?'is-selected':''}" data-action="battlefieldCampaign" data-id="${item.id}" ${reason?'disabled':''}><strong>${item.name}</strong><span>${today?'今日箱已领':'今日有箱'}</span><small>${reason||'主将'+item.minLevel+'级 · 九主线六支线'}</small></button>`;}).join('')}</div><p class="sub">${c.name} · 九主线 / 六支线</p><p>一名自己的将领率领租兵。援军令 ×1 覆盖整轮，城内军队和人口不参与；中途可以暂停、刷新续战。</p>${rewards(v)}`;
    if(v.entryReason&&!r)body+=notice(v.entryReason);
    body+=`<p class="hint">装备箱随机出一件，可重复；援军令2500黄金。</p><div class="battlefield-stock"><span>援军令 <b>${v.tokens}</b></span><span>${c.id==='nanman'?'蛮族箱':'黄巾箱'} <b>${v.boxes}</b></span></div><div class="battlefield-controls">${!v.starterClaimed?btn('领援军令','battlefieldStarter','','secondary',!!v.entryReason):''}${btn('购援军令','battlefieldBuyAsk','','secondary',!!v.entryReason)}${v.boxes?btn('开'+(c.id==='nanman'?'蛮族箱':'黄巾箱'),'battlefieldBox',c.id,'secondary'):''}${['compass','mask'].map(id=>v.relics[id]?.unlocked&&!v.relics[id].claimed?btn(id==='compass'?'领罗盘':'领面具','battlefieldRelic',id,'secondary'):'').join('')}</div>`;
    if(!r){const heroes=S().generals.filter(id=>Game.heroCity(id)===Game.currentCityId()),unlocked=BattlefieldSystem.RENT_UNITS.filter(id=>Game.unitUnlocked(id));body+=`<section class="panel"><h3>整备官军</h3><p class="hint">本城官府3级、校场1级，主将${c.minLevel}级且没有任职或出征。初始租兵总池3000人，每战编队最多800人。兵种科技在开局冻结。</p><label for="battlefield-general">主将</label><select id="battlefield-general">${heroes.map(id=>`<option value="${esc(id)}">${esc(Game.general(id).name)} · ${S().generalLevels[id]||1}级${Game.generalBusy(id)?' · 占用中':''}</option>`).join('')}</select>${fields('battlefield-start',unlocked,800)}${btn('出战','battlefieldStartAsk','','block',!!v.entryReason)}</section>`;
      if(v.lastReceipt){const p=v.lastReceipt;body+=`<section class="panel battlefield-report"><h3>上次通关报告</h3><p>${p.completed.length-9} 条支线 · 声望 +${p.prestige} · 经验 +${p.xp} · ${p.campaign==='nanman'?'蛮族箱':'黄巾箱'} +${p.box}</p><p class="hint">${esc(p.day)} · ${esc(p.runId)}</p></section>`;}
    }else{body+=`<section class="panel"><h3>${esc(Game.general(r.general).name)} · 本轮官军</h3><p>${armyHTML(r.army)}</p><div class="battlefield-stock"><span>编队 <b>${total(r.army)}/800</b></span><span>可补租 <b>${r.pool}</b></span><span>待救治 <b>${total(r.wounded)}</b></span><span>军医额度 <b>${r.medicalQuota}</b></span></div><p class="hint">伤亡的60%返回补租池，其余进入待救治池；失败仍保留损失。${!total(r.army)?'编队已全灭，请补租；池不足时可救治或放弃本轮。':''}</p>${locked?btn('继续战斗','battlefieldResume','','block'):`${fields('battlefield-rent',r.unlocked)}<div class="battlefield-controls">${btn('补租','battlefieldRentAsk','','secondary')}${btn('主将装备','heroDetail',r.general,'secondary',Game.heroCity(r.general)!==Game.currentCityId())}${btn('探路','battlefieldDiscover','','secondary',r.routeDiscovered||r.completed.includes(c.discover))}</div>${r.medicalQuota?`<p class="hint">可救治：${armyHTML(r.wounded)}。救治后进入补租池，需要另行补租。</p>${fields('battlefield-heal',r.unlocked)}${btn('救治','battlefieldHealAsk','','secondary')}`:''}`}${btn('放弃','battlefieldAbandonAsk',r.id,'danger')}</section>`;
      if(r.battle?.finished){const b=r.battle,n=BattlefieldData.get(b.node,r.campaign),review=BattleReview.explain(b.result.facts);body+=`<section class="panel battlefield-report"><h3>${esc(n.name)} · ${b.result.won?'胜利':'败退'}</h3>${review.reasons.map(reason=>`<p>${esc(reason)}</p>`).join('')}${review.advice?`<p class="hint">${esc(review.advice)}</p>`:''}<details><summary>战场经过</summary><p>${esc(b.result.won?n.victory:n.defeat)}</p></details><p>折损 ${total(b.result.lost)}，回收 ${total(b.result.recovered)}。${b.result.won?'可返回其他区域补做支线。':'该地点可重试，补租不会恢复已耗尽的额度。'}</p></section>`;}
    }
    body+=`<div class="battlefield-arcs">${[1,2,3].map((arc,i)=>`<section class="battlefield-arc"><h3>${c.arcs[i]}</h3>${['main','side'].map(kind=>`<h4>${kind==='main'?'主线':'可选支线'}</h4>${v.nodes.filter(n=>n.arc===arc&&n.kind===kind).map(n=>`<button class="battlefield-node ${n.completed?'is-complete':''}" data-battlefield-node="${n.id}" data-action="battlefieldNodeAsk" data-id="${n.id}" ${!r||!n.available||locked?'disabled':''}><strong>${esc(n.name)}</strong><small>${n.completed?'已完成':!r?(n.reason||'待出战'):locked?'战斗中':n.reason||'可进入'}${kind==='side'?' · 支线':''}</small></button>`).join('')}`).join('')}</section>`).join('')}</div></div>`;
    showModal('战场 · '+c.name,body,btn('关闭','close','','secondary'));
  }
  function battle(){
    const r=view().run,b=r?.battle;if(!b||b.finished){map();return;}
    const battleKey=r.id+':'+b.node;
    if(selectedBattle!==battleKey){selectedBattle=battleKey;selectedUnit='';}
    const selected=b.player.find(row=>row.id===selectedUnit&&row.hp>0)||b.player.find(row=>row.hp>0)||b.player[0];
    selectedUnit=selected?.id||'';
    const n=BattlefieldData.get(b.node,r.campaign),count=row=>Math.ceil(row.hp/row.stats.hp);
    const tabs=b.player.map(row=>`<button class="battlefield-formation-tab ${row.id===selectedUnit?'is-selected':''}" data-action="battlefieldSelect" data-id="${row.id}" aria-pressed="${row.id===selectedUnit}" ${row.hp<=0?'disabled':''}>${typeof troopPortrait==='function'?troopPortrait(row.id):''}<strong>${esc(name(row.id))}</strong><span>${count(row)}/${row.initial}</span></button>`).join('');
    showModal(n.name,`<div class="battlefield-battle"><p class="sub">第 ${b.round}/30 回合 · ${esc(n.objective)}</p><details class="battlefield-help" data-ui-disclosure="battlefield-help"><summary>规则 ›</summary><p class="hint">前进接敌，坚守提高防御，后退拉开距离。选择目标后点指令，下回合执行。超过30回合视为败退。</p></details><div class="battlefield-formation-tabs" aria-label="选择指挥兵队">${tabs}</div><div class="battlefield-field">${[b.player,b.enemy].map((rows,i)=>rows.map(row=>`<div class="battlefield-unit ${i?'is-enemy':row.id===selectedUnit?'is-selected':''}" data-battlefield-unit="${row.id}"><strong>${i?'敌':'我'} · ${esc(name(row.id))} ${count(row)}/${row.initial}</strong><div class="battlefield-track" aria-label="${esc(name(row.id))}位置 ${row.pos}"><span style="left:${Math.max(0,Math.min(100,row.pos/b.length*100))}%"></span></div>${!i?`<label>目标<select id="battlefield-target-${row.id}"><option value="">自动选择</option>${b.enemy.filter(x=>x.hp>0).map(x=>`<option value="${x.id}" ${b.orders[row.id].target===x.id?'selected':''}>${esc(name(x.id))}</option>`).join('')}</select></label><div class="battlefield-orders">${[['advance','前进'],['hold','坚守'],['fallback','后退']].map(([c,text])=>btn(text+(b.orders[row.id].command===c?' ✓':''),'battlefieldOrder',row.id+'|'+c,'secondary',row.hp<=0)).join('')}</div>`:''}</div>`).join('')).join('')}</div>${b.round?`<p class="battlefield-round-summary" role="status">本战损员：我军 ${b.player.reduce((sum,row)=>sum+row.initial-count(row),0)} · 敌军 ${b.enemy.reduce((sum,row)=>sum+row.initial-count(row),0)}</p>`:''}<details class="battlefield-log-detail" data-ui-disclosure="battlefield-log-${r.id}-${b.node}"><summary>战斗日志 · ${b.log.length}</summary><div class="battlefield-log" aria-live="polite">${b.log.map(text=>`<p>${esc(text)}</p>`).join('')}</div></details></div>`,btn('暂停','battlefieldPause','','secondary')+btn('下一回合','battlefieldRound'));
  }
  function infiltrationHTML(r,id,c){if(r.infiltration[id])return `<p class="hint">本轮已尝试：${r.infiltration[id]==='infiltration'?'潜入成功，敌军弓兵已避开':'身份暴露，正面进入'}。</p>`;const has=S().equipment.some(e=>e.hero===r.general&&e.relic==='mask');return `<p class="hint">易容面具：正确口令可避开弓兵，错误则正面交战；本轮此处只尝试一次。${has?'':'请先为主将穿戴面具，或直接正面进入。'}</p>`+(has?`<div class="battlefield-controls">${(c.id==='nanman'?[['forest','归林'],['river','渡江'],['return','归营']]:[['rise','当立'],['river','渡江'],['return','归营']]).map(([answer,text])=>btn(''+text,'battlefieldInfiltrate',id+'|'+answer,'secondary')).join('')}</div>`:'');}
  function ask(title,text,action,id=''){showModal(title,notice(text),btn('返回','battlefieldOpen','','secondary')+btn('确认','battlefield'+action,id));}
  function handle(a,id){if(!a.startsWith('battlefield'))return false;const v=view(),r=v.run,c=v.campaign;switch(a){
    case 'battlefieldOpen':map();break;
    case 'battlefieldCampaign':if(!r&&BattlefieldData.config(id)){selectedCampaign=id;pending=null;}map();break;
    case 'battlefieldStartAsk':{const general=document.getElementById('battlefield-general')?.value||'',army=read('battlefield-start',BattlefieldSystem.RENT_UNITS),q=Game.battlefieldQuote(general,army,c.id);if(q.reason){toast(q.reason);break;}pending={general,army,key:q.key,campaign:c.id};ask('开始'+c.name,'援军令 ×1 覆盖整轮；租兵 '+total(army)+' 人，余池 '+(3000-total(army))+' 人。最终胜利才发奖励，放弃不退令。','Start');break;}
    case 'battlefieldStart':if(!pending){toast('请重新出战');break;}if(result(Game.startBattlefield(pending.general,pending.army,pending.key,pending.campaign))){pending=null;map();}break;
    case 'battlefieldStarter':if(result(Game.claimStarterReinforcementToken(),'援军令已收入背包'))map();break;
    case 'battlefieldBuyAsk':ask('购买援军令','从当前城支付2500黄金，购买援军令 ×1。','Buy');break;
    case 'battlefieldBuy':if(result(Game.buyReinforcementToken(),'援军令已收入背包'))map();break;
    case 'battlefieldNodeAsk':{const n=v.nodes.find(x=>x.id===id);if(!r||!n?.available){toast(n?.reason||'请先开始战役');break;}showModal(n.name,`<p>${esc(n.intro)}</p><p class="notice">${esc(n.objective)}</p><p>敌军：${n.dialogue?'无需战斗，护送医官':armyHTML(n.army)}</p>${r.infiltration[id]==='infiltration'?'<p class="hint">潜入守军：'+armyHTML(BattlefieldSystem.nodeForRun(r,id,'infiltration').army)+'</p>':''}${id===c.discover&&r.routeDiscovered?'<p class="hint">密道守军：'+armyHTML(BattlefieldSystem.nodeForRun(r,id,'hidden').army)+'</p>':''}<p class="hint">${n.kind==='side'?'此支线可选；完成后增加整轮收益。':'此处为主线节点。'}${id===c.finalNode?'最终胜利立即结束本轮，请先完成想做的支线。':''}</p>`,btn('返回','battlefieldOpen','','secondary')+btn(n.dialogue?'护送医官':r.infiltration[id]==='infiltration'?'潜入':'正面进入','battlefieldEnter',id+'|'+(r.infiltration[id]||'normal'))+(id===c.discover&&r.routeDiscovered?btn('密道','battlefieldEnter',id+'|hidden','secondary'):'')+(id===c.infiltration?infiltrationHTML(r,id,c):''));break;}
    case 'battlefieldEnter':{const [node,choice]=id.split('|');if(result(Game.enterBattlefieldNode(node,choice)))battle();break;}
    case 'battlefieldSelect':if(r?.battle?.player.some(row=>row.id===id&&row.hp>0)){selectedUnit=id;battle();}break;
    case 'battlefieldOrder':{const [unit,command]=id.split('|');if(result(Game.battlefieldOrder(unit,command,document.getElementById('battlefield-target-'+unit)?.value||'')))battle();break;}
    case 'battlefieldRound':if(result(Game.battlefieldRound()))battle();break;
    case 'battlefieldPause':if(result(Game.pauseBattlefieldBattle()))map();break;
    case 'battlefieldResume':if(result(Game.resumeBattlefieldBattle()))battle();break;
    case 'battlefieldRentAsk':case 'battlefieldHealAsk':if(!r){toast('请先开始战役');break;}pending={runId:r.id,army:read(a==='battlefieldRentAsk'?'battlefield-rent':'battlefield-heal',r.unlocked)};ask(a==='battlefieldRentAsk'?'补租编队':'军医救治',armyHTML(pending.army)+(a==='battlefieldRentAsk'?'：从本轮池扣除人数，编队上限800。':'：消耗军医额度，将伤兵转入补租池。'),a==='battlefieldRentAsk'?'Rent':'Heal');break;
    case 'battlefieldRent':case 'battlefieldHeal':if(!pending||pending.runId!==r?.id){toast('战役已变化，请重新确认');break;}if(result(a==='battlefieldRent'?Game.reinforceBattlefield(pending.army):Game.healBattlefield(pending.army))){pending=null;map();}break;
    case 'battlefieldAbandonAsk':if(r)ask('放弃本轮？','本轮租兵、支线进度和未结算收益将全部丢失，援军令不退。已获得的箱子和奇物保留。','Abandon',r.id);break;
    case 'battlefieldAbandon':if(result(Game.abandonBattlefield(id),'本轮已放弃'))map();break;
    case 'battlefieldBox':{const campaign=id||c.id,error=Game.openBattlefieldBox(campaign);if(result(error,error?'':'获得'+HeroSystem.itemName(S().equipment.at(-1))))map();break;}
    case 'battlefieldRelic':if(result(Game.claimBattlefieldRelic(id),'奇物已收入装备库'))map();break;
    case 'battlefieldInfiltrate':{const [node,answer]=id.split('|');if(result(Game.attemptBattlefieldInfiltration(node,answer))){const run=view().run;ask(run.infiltration[node]==='infiltration'?'潜入成功':'身份暴露',run.infiltration[node]==='infiltration'?'已避开弓兵，仍需击败剩余守军。':'口令不符，需要击败完整守军；本轮不能重新选择。','Enter',node+'|'+run.infiltration[node]);}break;}
    case 'battlefieldCompass':if(result(Game.claimBattlefieldRelic('compass'),'寻踪罗盘已收入装备库'))map();break;
    case 'battlefieldDiscover':if(result(Game.discoverBattlefieldRoute(),'隐藏入口已探明'))map();break;
    default:return false;
  }return true;}
  return {map,battle,handle};
})();
function battlefieldModal(){battlefieldUI.map();}
function handleBattlefieldAction(action,id=''){return battlefieldUI.handle(action,id);}
