'use strict';
const BattlefieldSystem=(()=>{
  const CONFIG_VERSION=1,RENT_UNITS=['militia','spear','shield','archer','cavalry'];
  const object=x=>!!x&&typeof x==='object'&&!Array.isArray(x),integer=n=>Number.isSafeInteger(n)&&n>=0;
  const clone=x=>JSON.parse(JSON.stringify(x)),sum=a=>Object.values(a).reduce((a,b)=>a+b,0),empty=()=>({version:1,seq:0,starterClaimed:false,run:null,daily:{},firstClears:{},relics:{},lastReceipt:null});
  const blank=api=>Object.fromEntries(Object.keys(api.units).map(id=>[id,0]));
  function init(s){if(s.battlefields===undefined)s.battlefields=empty();}
  function armyValid(a,api){return object(a)&&Object.keys(a).length===Object.keys(api.units).length&&Object.keys(api.units).every(id=>integer(a[id])&&(RENT_UNITS.includes(id)||a[id]===0));}
  function selection(a,allowed,api,nonzero=false){if(!object(a)||Object.keys(a).some(id=>!allowed.includes(id)||!integer(a[id])))return null;const out={...blank(api),...a};return sum(out)<=800&&(!nonzero||sum(out)>0)?out:null;}
  function active(s){return s.battlefields?.run;}
  function locked(s){return !!active(s)?.battle&&!active(s).battle.finished;}
  function quote(s,general,army,api){
    const selected=selection(army,RENT_UNITS,api,true),city=api.city(api.currentCity),bf=s.battlefields||empty();
    let reason=!api.enabled?'剧本战场仅在单机模式开放':bf.run?'已有战役，请继续或放弃':!city||city.buildings.hall<3||city.buildings.drill<1?'需要本城官府3级、校场1级':!s.generals.includes(general)||api.heroCity(general)!==api.currentCity?'请选择本城将领':api.generalBusy(general)||api.role(general)?'将领出征、驻守或任职中':(s.generalLevels[general]||1)<5?'需要将领5级':!selected?'选择1至800名租兵':Object.entries(selected).some(([id,n])=>n&&!api.unlocked(id))?'租兵兵种尚未解锁':(s.inventory.reinforcementToken||0)<1?'需要援军令×1':'';
    const key=JSON.stringify([bf.seq,api.currentCity,general,selected]);return {reason,key,army:selected,pool:3000,cost:1,limit:800};
  }
  function start(s,general,army,key,api){const q=quote(s,general,army,api);if(q.reason)return q.reason;if(q.key!==key)return '租兵方案已变化，请重新确认';const bf=s.battlefields;s.inventory.reinforcementToken--;bf.seq++;const frozen=api.freeze(api.currentCity);bf.run={id:'yellow:'+bf.seq,campaign:'yellow_turban',configVersion:CONFIG_VERSION,sourceCity:api.currentCity,general,startedAt:api.now,completed:[],selectedNode:null,army:q.army,pool:3000-sum(q.army),wounded:blank(api),medicalQuota:0,battle:null,techSnapshot:frozen.tech,unitSnapshot:frozen.units,unlocked:frozen.unlocked,routeDiscovered:false};return null;}
  function enter(s,id,choice,api){const r=active(s),n=BattlefieldData.get(id);if(!r)return '尚未开始战役';if(locked(s))return '请先结束当前战场战斗';if(choice!=='normal')return '该进入方式尚未开放';if(!n||!BattlefieldData.available(r.completed).includes(id))return '地点未开放或已完成';if(n.dialogue){r.completed.push(id);r.medicalQuota+=200;r.selectedNode=null;r.battle=null;return null;}if(!sum(r.army))return '租兵编队已全灭，请补租或放弃本轮';r.selectedNode=id;r.battle=null;return null;}
  function reinforce(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能补租';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(r.army)+sum(chosen)>800)return '补租后编队需在1至800人范围';if(sum(chosen)>r.pool)return '本轮补租池不足，可做救援支线或放弃';for(const id of Object.keys(r.army))r.army[id]+=chosen[id];r.pool-=sum(chosen);r.battle=null;r.selectedNode=null;return null;}
  function heal(s,army,api){const r=active(s);if(!r)return '尚未开始战役';if(locked(s))return '战斗中不能救治';const chosen=selection(army,r.unlocked,api,true);if(!chosen||sum(chosen)>r.medicalQuota||Object.keys(chosen).some(id=>chosen[id]>r.wounded[id]))return '救治数量超过伤兵或军医额度';for(const id of Object.keys(chosen))r.wounded[id]-=chosen[id];r.medicalQuota-=sum(chosen);r.pool+=sum(chosen);return null;}
  function abandon(s,id){const r=active(s);if(!r||r.id!==id)return '战役编号已变化';s.battlefields.run=null;return null;}
  function view(s,api){const bf=s.battlefields||empty(),r=bf.run,available=BattlefieldData.available(r?.completed||[]),completed=r?.completed||[],reward=BattlefieldData.reward(completed);return {enabled:api.enabled,entryReason:!api.enabled?'剧本战场仅在单机模式开放':api.city(api.currentCity)?.buildings.hall<3||api.city(api.currentCity)?.buildings.drill<1?'需要本城官府3级、校场1级':'',run:r?clone(r):null,nodes:[...BattlefieldData.MAIN_IDS,...BattlefieldData.SIDE_IDS].map(id=>({...BattlefieldData.get(id),completed:completed.includes(id),available:available.includes(id),reason:completed.includes(id)?'已完成':available.includes(id)?'':'先完成前置主线'})),reward,tokens:s.inventory.reinforcementToken||0,boxes:s.inventory.yellowEquipmentBox||0,starterClaimed:bf.starterClaimed,relics:clone(bf.relics),lastReceipt:bf.lastReceipt?clone(bf.lastReceipt):null};}
  function valid(s,api){const bf=s.battlefields;if(!object(bf)||bf.version!==1||!integer(bf.seq)||typeof bf.starterClaimed!=='boolean'||![bf.daily,bf.firstClears,bf.relics].every(object)||bf.lastReceipt!==null||Object.keys(bf.daily).length||Object.keys(bf.firstClears).length||Object.keys(bf.relics).length)return false;
    const r=bf.run;if(r===null)return true;if(!object(r)||r.id!=='yellow:'+bf.seq||bf.seq<1||r.campaign!=='yellow_turban'||r.configVersion!==1||!integer(r.startedAt)||!api.city(r.sourceCity)||!s.generals.includes(r.general)||api.heroCity(r.general)!==r.sourceCity||api.otherBusy(r.general)||api.role(r.general)||!BattlefieldData.validCompleted(r.completed)||r.completed.includes('m9')||!armyValid(r.army,api)||sum(r.army)>800||!armyValid(r.wounded,api)||!integer(r.pool)||!integer(r.medicalQuota)||r.medicalQuota>200||typeof r.routeDiscovered!=='boolean'||!Array.isArray(r.unlocked)||new Set(r.unlocked).size!==r.unlocked.length||r.unlocked.some(id=>!RENT_UNITS.includes(id))||Object.entries(r.army).some(([id,n])=>n&&!r.unlocked.includes(id))||!object(r.techSnapshot)||Object.keys(r.techSnapshot).length!==Object.keys(ManualData.technology).length||Object.keys(ManualData.technology).some(id=>!integer(r.techSnapshot[id])||r.techSnapshot[id]>10)||!object(r.unitSnapshot))return false;
    const quota=3000+500*['s1','s5'].filter(id=>r.completed.includes(id)).length;if(sum(r.army)+sum(r.wounded)+r.pool!==quota||r.medicalQuota> (r.completed.includes('s4')?200:0))return false;
    if(r.selectedNode!==null&&!BattlefieldData.available(r.completed).includes(r.selectedNode))return false;
    if(Object.keys(r.unitSnapshot).length!==RENT_UNITS.length||RENT_UNITS.some(id=>!object(r.unitSnapshot[id])||Object.keys(r.unitSnapshot[id]).length!==5||!['hp','atk','def','speed','range'].every(k=>Number.isFinite(r.unitSnapshot[id][k])&&r.unitSnapshot[id][k]>=0&&r.unitSnapshot[id][k]<=100000)||r.unitSnapshot[id].hp<1||r.unitSnapshot[id].speed<1))return false;
    return r.battle===null;
  }
  return {RENT_UNITS,init,valid,view,quote,start,enter,reinforce,heal,abandon,locked,armyValid,selection,blank,sum};
})();
