'use strict';
function captiveSummaryHTML(){const count=Game.totalArmy(S().captives);return `<section class="panel"><div class="section-title"><h3>俘虏营 · ${num(count)} / ${num(Game.captiveCapacity())}</h3>${btn('管理俘虏','captiveCamp','','small secondary')}</div><p class="hint">战胜敌军有机会获得降卒。招降消耗粮食、黄金和空闲人口，随后直接加入驻城军队。未招降的俘虏不耗粮、不参与战斗。</p></section>`;}
function captiveCampModal(){const s=S(),rows=RewardData.captives.units.filter(id=>s.captives[id]>0);
  showModal('军队 · 俘虏营',`<div class="quest-summary"><strong>收容 ${num(Game.totalArmy(s.captives))} / ${num(Game.captiveCapacity())} 人</strong><span>空闲人口 ${num(Game.freePopulation())}</span></div><p class="notice">胜利收容概率 30%–50%，随敌军等级增加。成功时可收容敌军的约 3%–8%；押解人数最多为幸存我军的 25%，每战不超过 300 人，超出营地容量者会被释放。县城临时义兵与运输、侦察、器械单位不作为俘虏。</p><p class="hint">收容容量 = 官府等级 ×100 + 校场等级 ×50（最低 100，最高 5,000）。招降须满足对应兵种的建筑与科技条件；每人花费粮食 50、黄金为原训练价的一半且至少 20，并消耗该兵种所需人口。招降立即归队；释放没有资源奖励。</p>${rows.length?rows.map(id=>{const u=Game.units[id],q=Game.captiveRecruitQuote(id,1);return `<article class="quest-card"><div class="quest-heading"><h3>${troopPortrait(id,'unit-portrait-small')}${u.name}</h3><span class="badge">${num(s.captives[id])} 名</span></div>${costs(q.cost)}<p class="hint">每人需要 ${q.people} 空闲人口${q.reason?' · '+esc(q.reason):''}</p><div class="quest-actions">${btn('选择招降数量','captiveRecruitPlan',id,'small',!!q.reason)}${btn('释放俘虏','captiveReleasePlan',id,'small secondary')}</div></article>`;}).join(''):'<div class="empty">暂未收容俘虏。赢得野地或据点战斗后，有机会带回降卒。</div>'}`,btn('前往军队','captiveArmy','','secondary')+btn('关闭','close','','secondary'));manualModalContext=captiveCampModal;
}
function captivePlan(id,release=false){const count=S().captives[id]||0,u=Game.units[id];if(!count||!u){toast('俘虏已处理');captiveCampModal();return;}
  let max=count;if(!release){const q=Game.captiveRecruitQuote(id,1);max=Math.max(0,Math.min(count,Math.floor(Game.freePopulation()/q.people),...Object.entries(q.cost).map(([k,n])=>Math.floor(S().res[k]/n))));}
  showModal((release?'释放':'招降')+' · '+u.name,`<p class="sub">当前收容 ${num(count)} 人</p><label class="label" for="captive-count">${release?'释放人数':'招降人数'}</label><input id="captive-count" type="number" data-unit="${id}" data-release="${release}" min="1" max="${Math.max(1,max)}" value="${Math.max(1,Math.min(max,10))}" ${max?'':'disabled'}><div id="captive-quote"></div>${release?'<p class="notice">释放后无法撤销，没有资源或人口奖励。</p>':'<p class="hint">确认后立即加入驻城军队，开始消耗粮食。</p>'}`,btn('返回俘虏营','captiveCamp','','secondary')+btn(release?'确认释放':'确认招降',release?'captiveRelease':'captiveRecruit',id,release?'danger':'',!max));refreshCaptiveQuote();
}
function refreshCaptiveQuote(){const input=document.getElementById('captive-count'),area=document.getElementById('captive-quote');if(!input||!area||input.dataset.release==='true')return;const q=Game.captiveRecruitQuote(input.dataset.unit,Number(input.value));area.innerHTML=costs(q.cost)+`<p class="hint">需要 ${num(q.people)} 人口${q.reason?' · '+esc(q.reason):''}</p>`;const button=modalBody.querySelector('[data-action="captiveRecruit"]');if(button)button.disabled=!!q.reason;}
function captiveDropsHTML(result){if(!result.captures||!result.won)return '';const count=Game.totalArmy(result.captures);return `<section class="battle-drops"><h4>收容俘虏</h4>${count?`<div class="item-drops">${Object.entries(result.captures).filter(([,n])=>n>0).map(([id,n])=>`<span class="item-drop">${Game.units[id].name} ×${num(n)}</span>`).join('')}</div><p class="hint">已收入俘虏营，招降后才能加入军队。</p>${btn('管理俘虏','captiveCamp','','small secondary')}`:'<p class="hint">本次没有收容俘虏。</p>'}${result.captureDiscarded?`<p class="hint">押解或营地名额不足，释放 ${num(result.captureDiscarded)} 人。</p>`:''}</section>`;}
document.addEventListener('input',event=>{if(event.target.id==='captive-count')refreshCaptiveQuote();});
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id;
  if(a==='captiveCamp')captiveCampModal();
  if(a==='captiveRecruitPlan')captivePlan(id);
  if(a==='captiveReleasePlan')captivePlan(id,true);
  if(a==='captiveRecruit'||a==='captiveRelease'){const count=Number(document.getElementById('captive-count')?.value),error=a==='captiveRecruit'?Game.recruitCaptives(id,count):Game.releaseCaptives(id,count);if(actResult(error,a==='captiveRecruit'?'降卒已加入驻城军队':'俘虏已释放'))captiveCampModal();}
  if(a==='captiveArmy'){modal.close();page='army';render();}
});
