'use strict';
let classicInfoOpen=false;
function classicBuildingDetails(id){
  const base=roof(45,31,.65,'#556552'),roof2=roof(45,18,.46,'#61745a');
  const flag='<path d="M15 49V12m0 0l14 4-14 5" stroke="#76634c" stroke-width="2" fill="#a65b37"/>';
  const crates='<path d="M61 47l12-7 12 7-12 8Z" fill="#d1b27a"/><path d="M61 47v10l12 8 12-8V47l-12 8Z" fill="#96784f"/><path d="M73 55v10m-8-11l15-9" stroke="#6e593a"/>';
  const details={
    academy:base+roof2+'<path d="M19 44l10 4 10-4v10l-10 4-10-4Z" fill="#ece3bc" stroke="#a69a6b"/><path d="M29 48v10" stroke="#8f8965"/>',
    inn:base+'<path d="M67 20v26m-7-22h15" stroke="#6d5942" stroke-width="2"/><rect x="67" y="25" width="12" height="14" rx="1" fill="#b1874b"/><text x="69" y="35" font-size="9" fill="#f1dbab">客</text>',
    tavern:base+flag+'<path d="M60 42l10-5 10 5v12l-10 5-10-5Z" fill="#c8bb8d"/><path d="M65 46h10m-8 5h6" stroke="#8a7a51"/>',
    market:base+'<path d="M13 45l20-9 17 9-20 10Z" fill="#ccba8e"/><path d="M16 46v12m27-8v13" stroke="#827655" stroke-width="2"/><path d="M16 45l7-5m1 10l7-5m1 10l7-5" stroke="#ad734f" stroke-width="4"/>',
    warehouse:base+crates,
    drill:roof(65,24,.36)+flag+'<path d="M17 47l29-16 24 13-29 17Z" fill="#baa97c" stroke="#8d9366"/><circle cx="41" cy="47" r="6" fill="none" stroke="#776d4d"/><path d="M41 41v12m-6-6h12" stroke="#776d4d"/>',
    embassy:base+roof2+flag,
    smith:base+'<path d="M60 48v-9l10-5 10 5v9l-10 6Z" fill="#8d8d7a"/><path d="M63 44l7-4 7 4-7 6Z" fill="#a85b36"/><path d="M68 38l3-12 4-6" stroke="#bbb9a3" stroke-width="3" opacity=".6"/>',
    workshop:base+crates+'<circle cx="22" cy="49" r="9" fill="#aa9568" stroke="#645d42" stroke-width="2"/><path d="M22 41v16m-8-8h16m-14-6l12 12m-12 0l12-12" stroke="#645d42"/>',
    stable:base+'<path d="M59 48l3-10 6-5 5 2 3 7 7 3-4 6H67l-2 9m13-10l2 8M62 41l-5-6" fill="#947653" stroke="#665740" stroke-width="2"/>',
    post:base+flag+'<path d="M18 50l13-7 13 7-13 8Z" fill="#bc9e69"/><path d="M18 50v6l13 8 13-8v-6" fill="#a08352"/>',
    beacon:'<path d="M27 34l18-10 20 10v21L45 67 27 55Z" fill="#a7ae94"/><path d="M27 34l18 11 20-11M45 45v22" fill="none" stroke="#7a8c71"/><path d="M22 33L45 16l23 17Z" fill="#4e6450"/><path d="M40 18l4-13 3 9 4-8 2 13" fill="#b27541"/><path d="M46 6l-2-8" stroke="#d4c6a4" stroke-width="4"/>'
  };
  return details[id]||base;
}
function classicSidebar(){
  const s=S(),rates=Game.rates();
  return `<aside class="classic-sidebar ${classicInfoOpen?'mobile-open':''}" aria-label="君主与城池信息"><div class="lord-card">${generalPortrait(Game.general(s.governor),'lord-portrait')}<div><strong>${esc(s.ruler)} <span class="lord-banner">${esc(s.banner)}</span></strong><span>青溪城 · (${Game.home.x}, ${Game.home.y})</span><small>太守 ${esc(Game.general(s.governor).name)}</small></div></div><section class="rail-section"><h3>城池状况 <button data-action="citySettings" title="调整税率与太守">内政</button></h3><dl class="city-ledger"><div><dt>官府</dt><dd>${s.buildings.hall} 级</dd></div><div><dt>人口</dt><dd data-population>${num(s.population)} / ${num(Game.maxPop())}</dd></div><div><dt>空闲人口</dt><dd data-free-pop>${num(Game.freePopulation())}</dd></div><div><dt>劳动人口</dt><dd>${num(Game.workers())}</dd></div><div><dt>民心 / 民怨</dt><dd><span data-morale>${Math.round(s.morale)}</span> / ${Math.round(s.unrest)}</dd></div><div><dt>税率</dt><dd>${s.tax}%</dd></div><div><dt>军队</dt><dd>${num(Game.committed())} 人</dd></div></dl></section><section class="rail-section"><h3>资源生产 <button data-action="manualStorage">仓储</button></h3><div class="classic-resources">${Object.entries(Game.resources).map(([id,r])=>`<div class="classic-resource"><div class="resource-line"><span class="resource-emblem ${id}">${resourceIcon(id,'')}</span><span>${r.name}</span><strong data-res="${id}">${num(s.res[id])}</strong></div><div class="stock-meter"><i data-stock-fill="${id}" style="width:${Math.min(100,s.res[id]/Game.capacity(id)*100)}%"></i></div><div class="resource-detail"><span data-rate="${id}" class="rate ${rates[id]<0?'negative':''}">${rates[id]>=0?'+':''}${Math.round(rates[id]*60)}/时</span><span>上限 ${num(Game.capacity(id))}</span></div></div>`).join('')}</div></section><div class="rail-actions">${btn('资源交易','manualMarket','','small secondary')}${btn('附属野地','classicTerritory','','small secondary')}${btn('城防工事','manualDefense','','small secondary')}${btn('倍率 ×'+s.speed,'manualSpeed','','small secondary')}</div><p class="rail-footnote">城池与队列自动保存<br>离线资源最多积累 8 小时</p></aside>`;
}
function classicShell(){
  const s=S(),active=page==='city'?cityArea:page;
  const primary=[['inner','城内'],['outer','城外'],['world','地图'],['army','军队'],['heroes','将领'],['reports','战报'],['shop','商城']];
  const view=({city:cityPage,army:armyPage,world:worldPage,heroes:heroesPage,reports:reportsPage,shop:manualShopPage})[page]();
  const latest=s.reports[0],m=Game.missions[s.mission],arrivals=Game.allExpeditions().filter(e=>e.phase==='march'&&e.end<=Date.now()).length;
  return `<div class="classic-frame"><header class="classic-header"><div class="classic-brand"><span class="brand-mark">三</span><h1>三国城志</h1><span class="classic-edition">单机 PVE</span></div><div class="classic-header-meta"><span>青溪城 · 官府 ${s.buildings.hall} 级</span><span>元宝 <b>${num(s.gems)}</b></span><button class="classic-info-toggle" data-action="classicInfo" aria-expanded="${classicInfoOpen}">城池详情</button><button data-action="settings" aria-label="设置与帮助">设置</button></div></header><nav class="classic-toolbar" aria-label="主导航"><div class="classic-primary">${primary.map(([id,label])=>`<button data-action="classicNav" data-id="${id}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${label}${id==='world'&&arrivals?`<i>${arrivals}</i>`:''}</button>`).join('')}</div><div class="classic-tools"><button class="classic-gift" data-action="classicStarterGift" title="粮食、木材、石料、铁锭、黄金各 20,000 · 每个存档限领一次" ${s.starterGiftClaimed?'disabled':''}>${s.starterGiftClaimed?'新手礼包已领':'新手礼包'}</button><button data-action="classicQueues">建造队列 <b>${s.buildQueue.length}/${Game.buildLimit()}</b></button><button data-action="manualInventory">宝物</button><button data-action="classicMission">任务${m?.check(s)?' ●':''}</button></div></nav><div class="classic-workspace">${classicSidebar()}<main id="main" class="classic-content screen-${page}" aria-label="游戏主界面">${view}</main></div><footer class="classic-footer"><div class="classic-bulletin"><span class="bulletin-tag">军情</span><span>${s.battle&&!s.battle.finished?`正在攻打 ${esc(Game.getNode(s.battle.node).name)} · 第 ${s.battle.round} 回合`:arrivals?`${arrivals} 支部队已抵达，前往地图指挥战斗`:latest?`${esc(Game.getNode(latest.node).name)} · ${latest.won?'战斗胜利':'战斗失利'} · ${latest.round} 回合${Object.keys(latest.itemDrops||{}).length?' · 获得道具':''}`:'暂无军情。建设军营、校场后，可配兵出征。'}</span>${btn('查看','classicNav',s.battle||arrivals?'world':'reports','small secondary')}</div>${missionHTML()}</footer></div>`;
}
function classicQueuePanel(){
  const s=S();return `<section class="panel classic-queue-panel"><div class="section-title"><h3>建造队列</h3><span class="label">${s.buildQueue.length} / ${Game.buildLimit()}</span></div>${autoUpgradeControls()}${s.buildQueue.length?s.buildQueue.map(q=>queueHTML(q,'build')).join(''):'<div class="empty">建造队空闲<br>点击建筑升级，点击空地建设。</div>'}<p class="hint queue-caption">城内、城外共用建造队。</p></section><section class="panel classic-city-actions"><div class="section-title"><h3>城池事务</h3></div><div class="city-action-grid">${btn('科技研究','manualResearch','','small secondary')}${btn('招兵训练','manualArmy','','small secondary')}${btn('寻访将领','manualInn','','small secondary')}${btn('出征战术','tacticsModal','','small secondary')}</div><p class="hint">${cityArea==='outer'?'':'选中地块查看详情与操作。'}</p></section>`;
}
function classicQueuesModal(){
  const s=S();showModal('营造与训练队列',`${autoUpgradeControls()}<h3 class="ledger-heading">营造 ${s.buildQueue.length}/${Game.buildLimit()}</h3>${s.buildQueue.length?s.buildQueue.map(q=>queueHTML(q,'build')+btn('取消施工','manualCancelAsk',q.plot===undefined?'site:'+q.site:'plot:'+q.plot,'small danger')).join(''):'<p class="empty">暂无工程。</p>'}<h3 class="ledger-heading">训练 ${s.trainQueue.length}/${Game.trainingLimit()}</h3>${s.trainQueue.length?s.trainQueue.map(q=>queueHTML(q,'train')).join(''):'<p class="empty">暂无训练。</p>'}<h3 class="ledger-heading">科技研究</h3>${s.researchQueue?`<p class="hint">${Game.manual.technology[s.researchQueue.id].name} → ${s.researchQueue.level} 级 ${clock(s.researchQueue.end)}</p>`:'<p class="empty">暂无研究。</p>'}`,btn('关闭','close','','secondary'));manualModalContext=classicQueuesModal;
}
function classicMissionModal(){showModal('当前任务',missionHTML(),btn('关闭','close','','secondary'));manualModalContext=classicMissionModal;}
function classicTargetActions(n){
  const s=S(),owned=!!s.conquered[n.id];if(owned&&(n.wild||Game.isCity(n)))return campaignNodeDetails(n);
  const raid=Game.attackInfo(n.id,'raid'),occupy=Game.attackInfo(n.id,'occupy'),cooling=s.cooldowns[n.id]>Date.now(),dispatched=Game.allExpeditions().some(e=>e.node===n.id),full=Game.allExpeditions().length>=s.buildings.drill,commonReason=!s.buildings.drill?'需要校场':cooling?'驻军恢复中':dispatched?'部队已派出':full?'派遣名额已满':'',occupyReason=Game.attackBlocked(n.id,'occupy'),info=Game.battleDropInfo(n.id);
  return `<div class="target-actions">${btn(commonReason?'掠夺 · '+commonReason:'配兵掠夺','campaignDispatch',n.id+':raid','secondary',!!commonReason)}${btn(commonReason?'占领 · '+commonReason:owned?'已占领':occupyReason?'野地名额已满':'配兵占领','campaignDispatch',n.id+':occupy','',!!commonReason||!!occupyReason||owned)}</div><p class="target-summary hint">掠夺：夺取资源后返城。<br>占领：${Game.isCity(n)?'启用城防与义兵，胜利降低民心。':n.wild?'取得产量加成，部队留守野地。':'取得据点归属，部队返城。'}</p><div class="reward">${n.reward}</div><p class="target-drop-info">胜利掉落：道具 ${Math.round(info.itemChance*1000)/10}% · 额外资源 ${Math.round(info.resourceChance*1000)/10}%</p><details class="target-details"><summary>预计战利品与规则</summary><p class="label">掠夺战利品</p>${lootHtml(raid.loot)}<p class="label">占领战利品</p>${lootHtml(occupy.loot)}${Game.isCity(n)?`<p class="hint">掠夺不启用城防与义兵；仓储保护 ${Math.max(0,40-s.tech.plunder*3)}% 资源，基础黄金不被掠夺。占领时加入 ${occupy.militia} 义兵，当前民心 ${occupy.morale}；胜利降低 35，低于 0 时易主。</p>`:''}<p class="hint">${battleDropHint(n)}</p></details><p class="hint target-time">行军 ${duration(n.time/s.speed)} · 返城 ${duration(Math.max(5,n.time/2)/s.speed)}${cooling?' · 恢复 '+clock(s.cooldowns[n.id]):''}</p>${occupyReason?`<p class="hint">${esc(occupyReason)}</p>`:''}`;
}
document.addEventListener('click',event=>{
  const el=event.target.closest('[data-action]');if(!el||el.disabled)return;
  const action=el.dataset.action,id=el.dataset.id;
  if(action==='classicNav'){if(id==='inner'||id==='outer'){page='city';cityArea=id;}else page=id;classicInfoOpen=false;render();document.getElementById('main').scrollTop=0;}
  if(action==='classicInfo'){classicInfoOpen=!classicInfoOpen;document.querySelector('.classic-sidebar')?.classList.toggle('mobile-open',classicInfoOpen);el.setAttribute('aria-expanded',String(classicInfoOpen));}
  if(action==='classicStarterGift')actResult(Game.claimStarterGift(),'新手礼包到账：粮食、木材、石料、铁锭、黄金各 +20,000');
  if(action==='classicQueues')classicQueuesModal();
  if(action==='classicTerritory')showModal('附属野地',territorySummary(),btn('关闭','close','','secondary'));
  if(action==='classicMission')classicMissionModal();
});
