'use strict';
function heritageOfficeModal(){
 const s=S(),selected=Object.fromEntries(Object.keys(HeritageSystem.roles).map(role=>[role,HeritageSystem.roleHero(s,role)])),available=s.generals.filter(id=>!Game.generalBusy(id)&&cityHeroHome(id)===activeCityMeta().id);
 showModal(esc(activeCityMeta().name)+' · 任职与税率',`${governmentSummary()}${governmentNav('settings')}<p class="notice">城守负责生产与建设，主将负责练兵，军师负责研究。一人只能任一职；任职将领留在城内，卸任后才能出征。开局仅两位将领，可先只任城守，留另一位出征。</p><div class="staff-grid">${Object.entries(HeritageSystem.roles).map(([role,label])=>`<label class="staff-card"><strong>${label}</strong><select id="staff-${role}" aria-label="任命${label}"><option value="">暂不任命</option>${available.map(id=>{const g=Game.general(id);return `<option value="${id}" ${selected[role]===id?'selected':''}>${esc(g.name)} · 内政 ${num(g.pol)} / 勇武 ${num(g.atk)} / 智谋 ${num(g.wis)}</option>`;}).join('')}</select><span class="hint">${{governor:'内政提高资源田产出、缩短新建设工期。',commander:'勇武缩短新练兵工期；空缺时由城守、军师依次代办。',counsellor:'智谋缩短新研究工期；空缺时由主将、城守依次代办。'}[role]}</span></label>`).join('')}</div><p class="hint">当前生效：建造 ${esc(Game.general(HeritageSystem.effectiveHero(s,'build')).name)} · 练兵 ${esc(Game.general(HeritageSystem.effectiveHero(s,'train')).name)} · 研究 ${esc(Game.general(HeritageSystem.effectiveHero(s,'research')).name)}。换职后只影响新开工队列，已开始的队列保持原时点。</p><div class="settings-row"><label for="tax-range">税率 <strong id="tax-value">${s.tax}%</strong></label><input id="tax-range" type="range" min="0" max="100" step="1" value="${s.tax}"><p class="hint">目标民心 = 100 − 税率。民心影响人口，劳动人口不足会降低产量。人口、税收公式为试玩值。</p></div>`,btn('取消','close','','secondary')+btn('确认任职与税率','heritageOfficeSave'));
}
function heritageJewelHTML(jewels){const entries=Object.entries(jewels||{});return entries.length?`<div class="jewel-grid">${entries.map(([id,n])=>`<div><strong>${Game.progression.jewels[id].name}</strong><span>×${num(n)}</span></div>`).join('')}</div>`:'';}
function heritageRequirementHTML(rule){
 const s=S(),counties=rule.county?HeritageSystem.ownedCounties(s):[];
 const row=(met,label)=>`<li class="${met?'requirement-met':'requirement-missing'}"><span aria-label="${met?'已满足':'未满足'}">${met?'✓':'○'}</span> ${label}</li>`;
 return `<ul class="heritage-requirements">${rule.prestige?row(s.prestige>=rule.prestige,`声望 ${num(rule.prestige)}（当前 ${num(s.prestige)}，不扣除）`):''}${rule.office?row(s.honors.office>=rule.office,`官职达到 ${HeritageData.offices[rule.office].name}（当前 ${HeritageSystem.office(s).name}）`):''}${rule.noble?row(s.honors.noble>=rule.noble,`爵位达到 ${HeritageData.nobles[rule.noble].name}（当前 ${HeritageSystem.noble(s).name}）`):''}${rule.hall?row(s.buildings.hall>=rule.hall,`官府 ${rule.hall} 级（当前 ${s.buildings.hall} 级）`):''}${rule.county?row(counties.length>0,`持有至少一座县城（当前 ${counties.length} 座${counties.length?' · '+esc(counties.map(c=>c.name).join('、')):''}，掠夺不算）`):''}</ul>${rule.gold?`<p class="label">晋升需消耗</p>${costs({gold:rule.gold})}`:''}${Object.keys(rule.jewels||{}).length?'<p class="label">晋升需消耗珠宝</p>'+heritageJewelHTML(rule.jewels)+heritageJewelSubstituteHTML(rule.jewels):''}`;
}
function heritageJewelSubstituteHTML(required){
 const p=HeritageSystem.jewelPayment(S(),required);if(!Object.keys(p.short).length)return '';
 const short=Object.entries(p.short).map(([id,n])=>Game.progression.jewels[id].name+' ×'+n).join('、'),use=Object.entries(p.substitute).map(([id,n])=>Game.progression.jewels[id].name+' ×'+n).join('、');
 return `<p class="${p.covered?'notice':'hint'}">缺 ${esc(short)}：可用其他珠宝按 ${p.rate} 倍价值折算（按声望价值，低价值珠宝优先）。${p.covered?'确认晋升时另外消耗 '+esc(use)+' 代替缺少的部分。':'现有珠宝折算后仍不足。'}</p>`;
}
function heritagePromotionCard(kind){
 const s=S(),current=kind==='office'?HeritageSystem.office(s):HeritageSystem.noble(s),q=HeritageSystem.promotionQuote(s,kind),salary=HeritageSystem.salaryQuote(s,kind),title=kind==='office'?'官职':'爵位';
 return `<section class="quest-card"><div class="quest-heading"><h3>${title} · ${current.name}</h3><span class="badge">${current.id} / ${kind==='office'?14:21}</span></div><p class="label">每日${kind==='office'?'食君之禄':'采食封邑'}</p>${lootHtml(salary.reward)}${btn(salary.claimed?'今日已领取':'领取'+(kind==='office'?'官职俸禄':'封邑资源'),'heritageSalary',kind,'secondary',salary.claimed||current.salary===0)}${kind==='noble'?`<p class="hint">可管理城池上限 ${current.city_count} 座 · 当前持有 ${Game.cityList().length} 座。</p>`:''}<div class="divider"></div>${q.next?`<h3>晋升 · ${q.next.name}</h3><p class="hint">${q.rule.rankTrial?(kind==='office'?'先达到所需爵位，再申请此官职。'+(q.rule.county?'县城须实际占领。':''):'晋爵可增加城池上限，黄金与珍宝在确认时扣除。'):q.rule.jewelTrial?(q.rule.trial?'本阶晋升采用试玩条件，需消耗珠宝。':'声望等条件沿用原配置，珠宝消耗为本版新增试玩规则。'):q.rule.trial?'本阶晋升采用试玩条件。':kind==='office'?'条件数值取自配置包；晋升任务与官职的对应按任务编号顺序适配。':'条件数值取自配置包的晋爵任务。'}</p>${heritageRequirementHTML(q.rule)}<p class="${q.reason?'notice':'hint'}">${esc(q.reason||'条件满足，可以晋升')}</p>${btn('确认晋升','heritagePromoteAsk',kind,'block',!!q.reason)}`:'<p class="notice">已达到最高级别</p>'}</section>`;
}
function heritageJewelSynthHTML(){
 const s=S(),P=Game.progression,order=P.JEWEL_ORDER;
 return `<section class="quest-card jewel-synth"><div class="quest-heading"><h3>珠宝合成</h3><span class="badge">${P.JEWEL_SYNTH} 合 1</span></div><p class="hint">${P.JEWEL_SYNTH} 枚同种珠宝合成 1 枚高一级珠宝。另外，5 级以上据点或野地连续 ${P.JEWEL_PITY} 场胜利没掉翡翠、玉石或夜明珠时，下一场必掉一枚（当前 ${s.jewelPity||0} / ${P.JEWEL_PITY}）。</p><div class="jewel-synth-rows">${order.slice(0,-1).map((id,i)=>{const q=P.synthesizeQuote(s,id,1);return `<div class="jewel-synth-row"><span>${P.jewels[id].name} ×${num(s.jewels[id])} → ${P.jewels[order[i+1]].name}</span>${btn('合成 1','jewelSynth',id+'|1','small secondary',!!q.reason)}${btn('全部 ×'+q.max,'jewelSynth',id+'|all','small secondary',q.max<1)}</div>`;}).join('')}</div></section>`;
}
function heritageHonorModal(){
 taskTab='honors';showModal('任务册 · 官职与爵位',`${taskTabs()}<div class="quest-summary"><strong>声望 ${num(S().prestige)}</strong><span>${HeritageSystem.office(S()).name} · ${HeritageSystem.noble(S()).name}</span></div><p class="notice">先晋爵再升官：公士 → 伍长 → 上造 → 什长。县长及后续官职须持有县城。声望不扣除，黄金与珍宝在确认时扣除。两类俸禄各可每日领取一次，北京时间 05:00 刷新；晋升不会重复发放当日俸禄。</p><div class="honor-grid">${heritagePromotionCard('office')}${heritagePromotionCard('noble')}</div>${heritageJewelSynthHTML()}<details class="government-rules"><summary>查看全部官职、爵位与俸禄</summary><h3>官职</h3><table class="progression-table"><tr><th>官职</th><th>爵位门槛</th><th>城池门槛</th><th>黄金 / 日</th></tr>${HeritageData.offices.map(r=>`<tr><td>${r.name}</td><td>${r.promotion?.noble?HeritageData.nobles[r.promotion.noble].name:'—'}</td><td>${r.promotion?.county?'持有县城':'—'}</td><td>${num(r.salary)}</td></tr>`).join('')}</table><h3>爵位</h3><table class="progression-table"><tr><th>爵位</th><th>四资源各 / 日</th><th>资料城池上限</th></tr>${HeritageData.nobles.map(r=>`<tr><td>${r.name}</td><td>${num(r.salary)}</td><td>${r.city_count} 座</td></tr>`).join('')}</table></details>${heritageHistoryHTML('salary')}`,btn('城内任职','heritageOffice','','secondary')+btn('关闭','close','','secondary'));manualModalContext=heritageHonorModal;
}
function heritageHistoryHTML(kind){const history=S().heritageHistory.filter(r=>r.kind===kind).slice(0,4);return history.length?`<h3 class="ledger-heading">最近${kind==='salary'?'领取':'采集'}记录</h3><div class="manual-list">${history.map(r=>`<article><h4>${esc(r.name)}</h4><p class="hint">${new Date(r.at).toLocaleString('zh-CN')}</p>${lootHtml(r.loot)}${heritageJewelHTML(r.jewels)}${r.xp?`<p class="hint">将领经验 +${num(r.xp)}</p>`:''}${r.overCapacity?`<p class="notice">爆仓入库 ${num(r.overCapacity)}，已计入收获，资源已到账。</p>`:''}${r.discarded?`<p class="hint">${r.overCapacity===undefined?'负重或仓储不足':'超出可携带数量'}，${num(r.discarded)} 资源未能收取。</p>`:''}</article>`).join('')}</div>`:'';}
function heritageGatherHTML(id){
 const a=S().gatherings[id],q=a?HeritageSystem.gatherQuote(S(),id):null,reason=HeritageSystem.gatherReason(S(),id);
 return `<div class="notice gathering-summary">${a?`采集中 · ${q?.ready?'可以结束并收获':'最早收获 '+clock(a.start+HeritageSystem.HOUR)} · 最多累积 24 小时`:`野地采集 · ${esc(reason||'驻军已就绪，可以开始')}`} ${btn(a?'查看采集':'开始采集',a?'heritageGather':'heritageGatherStart',id,'small secondary',!a&&!!reason)}</div>`;
}
function heritageGatherBoardModal(){const ids=Object.keys(S().conquered).filter(id=>Game.getNode(id)?.wild);showModal('附属野地 · 采集',`<p class="notice">占领非平地野地后，让将领和部队驻守，再开始采集。按真实时间计算，至少 1 小时可收获，最多累积 24 小时；每满 1 小时有一次珍宝抽取机会。收获允许爆仓，资源田在库存低于容量后恢复增产。驻军仍耗粮，采集不再另扣启动费用。</p><div class="manual-list">${ids.map(id=>`<article><h3>${esc(Game.getNode(id).name)} · ${Game.getNode(id).level} 级</h3>${heritageGatherHTML(id)}</article>`).join('')||'<p class="notice">还没有附属野地。前往地图，选择野地并以「占领」方式出征。</p>'}</div>${heritageHistoryHTML('gather')}`,btn('前往地图','dailyGo','world','secondary')+btn('关闭','close','','secondary'));manualModalContext=heritageGatherBoardModal;}
function heritageGatherModal(id){
 const s=S(),n=Game.getNode(id),a=s.gatherings[id],q=HeritageSystem.gatherQuote(s,id);if(!a||!q){heritageGatherBoardModal();return;}
 showModal('野地采集 · '+esc(n.name),`<p class="sub">${esc(Game.general(a.general).name)}率 ${num(Game.totalArmy(s.garrisons[id].army))} 人驻守 · 开始时野地 ${a.level} 级</p><p class="notice">已采集 ${duration(q.elapsed/1000)}${q.cap?' · 已达到 24 小时收益上限':''}；${q.ready?'现在可结束收获。':'至少 1 小时可收获，剩余 '+clock(a.start+HeritageSystem.HOUR)+'。'}</p><h3>预计资源收获</h3>${lootHtml({[q.resource]:q.received})}<p class="hint">按文件公式累计 ${num(q.amount)} · 部队负重 ${num(q.carry)} · 仓储剩余 ${num(q.room)}。${q.overCapacity?'<br>预计爆仓入库 '+num(q.overCapacity)+'，已包含在上方资源收获中；满仓或超仓也可收取。':''}${q.discarded?'<br>超出可携带数量，'+num(q.discarded)+' 资源无法带回。':''}<br>将领预计获得经验 +${num(q.xp)}（按实际收取资源计算，经验倍率为试玩值）。</p><h3>珍宝搜寻</h3><p class="hint">已经累积 ${q.rolls} 次抽取机会，每次 ${Math.round(q.chance*1000)/10}% 概率找到珍宝；结束采集时统一抽取。地形不同，珍宝权重不同。</p><div class="jewel-grid">${Object.entries(Game.progression.jewels).map(([key,j],i)=>`<div><strong>${j.name}</strong><span>权重 ${HeritageData.fields[a.type].weights[i]}</span></div>`).join('')}</div><p class="hint">资源受部队负重限制，满仓或超仓仍可收取，珍宝不占负重；开始时的等级和耗粮值用于本次计算。普通野地每日降级规则继续生效。收获后部队仍驻守，可重新开始采集或召回。</p>${btn('取消本次采集','heritageGatherCancelAsk',id,'small danger')}`,btn('返回野地列表','heritageGatherBoard','','secondary')+btn('结束并收获','heritageGatherCollect',id,'',!q.ready));manualModalContext=()=>heritageGatherModal(id);
}
document.addEventListener('click',event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id;if(!a.startsWith('heritage'))return;
 if(a==='heritageOffice')heritageOfficeModal();
 if(a==='heritageOfficeSave'){const error=HeritageSystem.assign(document.getElementById('staff-governor').value,document.getElementById('staff-commander').value,document.getElementById('staff-counsellor').value);if(!error){Game.setTax(Number(document.getElementById('tax-range').value));Game.save();}if(actResult(error,'城内任职与税率已保存'))modal.close();}
 if(a==='heritagePromoteAsk'){const q=HeritageSystem.promotionQuote(S(),id);if(!q?.next)return;showModal('确认晋升 · '+q.next.name,`${heritageRequirementHTML(q.rule)}<p class="notice">将扣除上方黄金与珍宝，声望不扣除。晋升后的每日俸禄按新级别发放；今天已经领取的俸禄不能再领。</p>`,btn('返回官爵页','taskTab','honors','secondary')+btn('确认晋升','heritagePromote',id,'',!!q.reason));}
 if(a==='heritagePromote'){const error=HeritageSystem.promote(id);heritageHonorModal();actResult(error,'晋升成功，新的官爵与俸禄已生效');}
 if(a==='heritageSalary'){const error=HeritageSystem.salary(id);heritageHonorModal();actResult(error,'俸禄已收入仓库');}
 if(a==='heritageGatherBoard')heritageGatherBoardModal();
 if(a==='heritageGather')heritageGatherModal(id);
 if(a==='heritageGatherStart'){const error=HeritageSystem.startGather(id);if(!error)heritageGatherModal(id);actResult(error,'已开始采集，满 1 小时可收获');}
 if(a==='heritageGatherCollect'){const error=HeritageSystem.collectGather(id);heritageGatherBoardModal();actResult(error,'采集已结束，请查看最近采集记录');}
 if(a==='heritageGatherCancelAsk')showModal('取消采集？','<p class="sub">本次累计的资源和珍宝机会将放弃，部队仍留在野地驻守，之后可以召回。</p>',btn('继续采集','heritageGather',id,'secondary')+btn('确认取消','heritageGatherCancel',id,'danger'));
 if(a==='heritageGatherCancel'){const error=HeritageSystem.cancelGather(id);heritageGatherBoardModal();actResult(error,'已取消采集，可以召回驻军');}
});
document.addEventListener('click',event=>{const el=event.target.closest('[data-action="jewelSynth"]');if(!el||el.disabled)return;const [id,times]=el.dataset.id.split('|');const error=Game.synthesizeJewel(id,times==='all'?'all':Number(times));if(!error)heritageHonorModal();actResult(error,'珠宝合成完成');});
