'use strict';
let heroTab='roster',equipmentPage=0,equipmentFilter='全部';
const EQUIPMENT_PAGE_SIZE=12;
function heroBusyLabel(id){return cityHeroHome(id)==='transit'?'城际行军中':cityHeroHome(id)!==activeCityMeta().id?'不在本城，切城后管理':'出征或驻守中';}
function heroEquipmentIcon(e){const key={weapon:'weapons',armor:'order',helmet:'blueprint',accessory:'scroll'}[e.slot];return artSprite('icons',HistoricalArt.icons.ids.indexOf(key),HeroSystem.itemName(e),'item-art');}
function heroStatsHTML(stats){return Object.entries(stats).filter(([,n])=>n).map(([k,n])=>`${HeroSystem.attrs[k]} +${num(n)}`).join(' · ')||'无额外属性';}
function heroEquipmentPageOpen(){heroTab='equipment';page='heroes';modal.close();render();}
function heroRosterPage(){
 const s=S();HeroSystem.init(s);
 const tabs=`<div class="shop-tabs">${btn('帐下将领','heroTab','roster',`secondary ${heroTab==='roster'?'active-order':''}`)}${btn('装备库 · '+s.equipment.length+'/'+s.equipmentCapacity,'heroTab','equipment',`secondary ${heroTab==='equipment'?'active-order':''}`)}${btn('铁匠铺打造','heroForge','','secondary')}${btn('客栈招募','manualInn','','secondary')}${btn('野地抓将','wildGenerals','','secondary')}${btn('将领图鉴','heroCodex','','secondary')}${btn('城内任职','heritageOffice','','secondary')}${!s.heroGiftClaimed?btn('领取将领装备礼包','heroGift'):''}</div>`;
 const head=`<div class="page-head"><div><h2>${heroTab==='roster'?'帐下群英':'将领装备库'}</h2><p class="sub">升级加点 · 装备穿戴 · 实战成长</p></div><span class="badge">已招募 ${s.generals.length} · 全城招贤 ${HeroSystem.wild.roomUsed(s)}/${Game.heroCapacity?Game.heroCapacity():s.buildings.tavern} 间房（含俘将）</span></div>${tabs}`;
 if(heroTab==='equipment')return head+heroEquipmentGrid();
 return head+`<div class="hero-grid">${Game.generals.map(base=>{const g=Game.general(base.id),owned=s.generals.includes(g.id),busy=Game.generalBusy(g.id),gov=s.governor===g.id,worn=s.equipment.filter(e=>e.hero===g.id);return `<section class="hero-card ${owned?'':'locked'}"><span class="hero-watermark">${g.type}</span><div class="hero-art">${generalPortrait(g)}</div><div><h3>${esc(g.name)} <span class="label">Lv.${g.level}</span></h3><p class="hero-title">${esc(g.title)}</p></div><div class="hero-stats">${Object.entries(HeroSystem.attrs).map(([k,label])=>`<span>${label}<b>${num(g[k])}</b></span>`).join('')}</div><p class="hint hero-desc">${esc(g.desc)}</p>${owned?`<p class="hint">忠诚 ${HeroSystem.wild.loyalty(s,g.id)} / 100 · 经验 ${num(s.generalXp[g.id])} / ${num(g.level*80)} · 待分配 ${HeroSystem.remaining(s,g.id)} 点<br>装备 ${worn.length}/4 · ${esc(cityName(cityHeroHome(g.id)))} · ${busy?heroBusyLabel(g.id):HeritageSystem.roleOf(s,g.id)?'现任'+HeritageSystem.roles[HeritageSystem.roleOf(s,g.id)]:'空闲'}</p><div class="hero-footer">${btn('培养与装备','heroDetail',g.id,'small')}${btn(gov?'现任城守':'任命城守','governor',g.id,'small secondary',gov||busy||cityHeroHome(g.id)!==activeCityMeta().id)}</div>`:'<p class="notice">占领黄巾营寨可解救</p>'}</section>`;}).join('')}</div><p class="notice">城守在城内建筑和资源田完工后获得「完工等级 ×10」经验，新建、升级和改建均计入。每升 1 级获得 3 个自由属性点，原有升级成长保留。勇武提高攻击，统御降低伤害，统率影响带兵属性覆盖；城守内政提高产出并缩短建造，主将勇武缩短练兵，军师智谋缩短研究。任职分工可在官府调整。出征或驻守期间不能调整加点与装备。装备属性叠加后参与实际计算。培养、装备数值为试玩规则。</p>`;
}
function heroEquipmentGrid(){
 const s=S(),all=s.equipment.filter(e=>equipmentFilter==='全部'||equipmentFilter==='未穿戴'&&!e.hero||e.slot===equipmentFilter),pages=Math.max(1,Math.ceil(all.length/EQUIPMENT_PAGE_SIZE));equipmentPage=Math.min(equipmentPage,pages-1);
 return `<p class="notice">装备可以在将领详情中穿戴，在铁匠铺打造；战斗胜利有 28%–55% 的机会缴获装备。普通 / 精良 / 珍稀装备要求将领 1 / 5 / 10 级。装备占用容量包含已穿戴物品。</p><div class="shop-tabs">${['全部','未穿戴',...Object.keys(HeroSystem.slots)].map(k=>btn(HeroSystem.slots[k]||k,'heroEquipmentFilter',k,`small secondary ${equipmentFilter===k?'active-order':''}`)).join('')}</div><div class="equipment-grid">${all.slice(equipmentPage*EQUIPMENT_PAGE_SIZE,(equipmentPage+1)*EQUIPMENT_PAGE_SIZE).map(e=>`<article class="equipment-card quality-${e.tier}">${heroEquipmentIcon(e)}<span class="badge">${HeroSystem.qualities[e.tier]} · ${HeroSystem.slots[e.slot]}</span><h3>${HeroSystem.itemName(e)} ${e.enhance?'+'+e.enhance:''}</h3><p class="hint">${heroStatsHTML(HeroSystem.stats(e))}</p><p class="hint">${e.hero?'已穿戴 · '+esc(Game.general(e.hero).name):'未穿戴'} · 需要 Lv.${HeroSystem.requiredLevel(e)}</p>${btn('装备详情','heroEquipment',String(e.id),'secondary block')}</article>`).join('')||'<p class="notice">暂无符合条件的装备。领取礼包、打造或击败敌军获得装备。</p>'}</div><div class="shop-tools">${btn('上一页','heroEquipmentPage',String(equipmentPage-1),'small secondary',equipmentPage===0)}<span class="label">第 ${equipmentPage+1} / ${pages} 页 · ${all.length} 件</span>${btn('下一页','heroEquipmentPage',String(equipmentPage+1),'small secondary',equipmentPage+1>=pages)}</div><p class="hint">武器架与高级武器架在背包中使用，容量最高 500 格。${btn('打开背包','manualInventory','','small secondary')}</p>`;
}
function governorTrainingHint(id){
 if(S().governor!==id)return '';
 const advice=GrowthGuide.governorAdvice(Game),g=Game.general(id);
 return `<p class="hint">城守建造经验：每次建筑或资源田完工获得等级 ×10 经验，按完工时任职归属。当前内政 ${num(g.pol)}；内政影响资源田产出与新工程工期。</p>${advice?`<p class="notice">你有 ${advice.points} 个自由点。若全投入内政，可到 ${num(advice.nextPol)}，新工程工期约缩短 ${advice.reduction.toFixed(1)}%。也可选择其他属性；输入与确认前不扣点，已开工工程不重算。</p>`:''}`;
}
function heroDetailModal(id){
 if(!S().generals.includes(id)){toast('请选择已招募将领');return;}
 const s=S(),g=Game.general(id),busy=Game.generalBusy(id),points=HeroSystem.remaining(s,id),q=HeroSystem.drillQuote(s,id),resetCost=Math.ceil(g.level/10);
 showModal('将领培养 · '+esc(g.name),`${generalPortrait(g,'hero-detail-portrait')}<p class="sub">Lv.${g.level} · ${esc(g.title)} · ${busy?heroBusyLabel(id):HeritageSystem.roleOf(s,id)?'现任'+HeritageSystem.roles[HeritageSystem.roleOf(s,id)]:'空闲'}</p><div class="hero-stats">${Object.entries(HeroSystem.attrs).map(([k,n])=>`<span>${n}<b>${num(g[k])}</b></span>`).join('')}</div><p class="hint">经验 ${num(s.generalXp[id])} / ${num(g.level*80)} · 每升 1 级获得 3 点</p>${governorTrainingHint(id)}<p class="notice">忠诚 ${HeroSystem.wild.loyalty(s,id)} / 100 ${btn('赏赐提升忠诚','wildRewardAsk',id,'small secondary',busy)}</p>${cityHeroHome(id)!==activeCityMeta().id?btn('切换到所在城市管理','citySwitchConfirm',cityHeroHome(id),'small secondary',!Game.cityMeta(cityHeroHome(id))):''}<h3>分配属性</h3><p class="label">可用 ${points} 点 · 填写本次追加点数，确认前不会扣除</p><div class="hero-allocation" data-hero="${id}">${Object.entries(HeroSystem.attrs).map(([k,n])=>`<label>${n}<span class="hint">已分配 ${s.heroPoints[id][k]}</span><input type="number" data-hero-point="${k}" min="0" max="${points}" step="1" value="0" ${busy?'disabled':''} aria-label="追加${n}点数"></label>`).join('')}</div><div class="shop-tools">${btn('确认加点','heroAllocate',id,'',busy||points===0)}${btn('清空待加点数','heroClear',id,'secondary')}${btn('洗髓重置 · '+resetCost+' 枚','heroResetAsk',id,'secondary',busy||points===HeroSystem.totalPoints(s,id))}</div>${heroSkillSummaryHTML(id)}<h3>校场操练</h3><p class="hint">消耗 ${num(q.cost)} 黄金，获得 ${q.xp} 经验；每位将领每日 3 次，今日 ${q.used}/3。需要 1 级校场，北京时间 05:00 重置。</p>${btn('操练一次','heroDrill',id,'secondary',busy||q.used>=3||s.buildings.drill<1||s.res.gold<q.cost||g.level>=10000)}<div class="divider"></div><h3>装备栏</h3><div class="hero-slots">${Object.entries(HeroSystem.slots).map(([slot,name])=>{const e=s.equipment.find(e=>e.hero===id&&e.slot===slot);return `<article><span class="label">${name}</span>${e?`${heroEquipmentIcon(e)}<strong>${HeroSystem.itemName(e)} +${e.enhance}</strong><p class="hint">${heroStatsHTML(HeroSystem.stats(e))}</p>${btn('详情 / 卸下','heroEquipment',String(e.id),'small secondary')}`:`<p class="hint">未穿戴</p>`}${btn('选择'+name,'heroPickEquipment',id+'|'+slot,'small',busy)}</article>`;}).join('')}</div><p class="notice">加点和装备属性已包含在上方总属性中。洗髓仅返还自由分配点，不影响等级和装备。</p>`,btn('返回将领','heroTab','roster','secondary'));
}
function heroPickEquipmentModal(id,slot){
 const available=S().equipment.filter(e=>e.slot===slot&&!e.hero&&HeroSystem.requiredLevel(e)<=S().generalLevels[id]);
 showModal('为 '+esc(Game.general(id).name)+' 选择'+HeroSystem.slots[slot],`<div class="manual-list">${available.map(e=>`<article>${heroEquipmentIcon(e)}<h3>${HeroSystem.qualities[e.tier]} · ${HeroSystem.itemName(e)} +${e.enhance}</h3><p class="hint">${heroStatsHTML(HeroSystem.stats(e))}</p>${btn('穿戴并替换同栏装备','heroEquip',e.id+'|'+id,'small')}</article>`).join('')||'<p class="notice">没有等级适用的闲置装备；可在装备库卸下其他将领的装备，或在铁匠铺打造。</p>'}</div>`,btn('返回培养','heroDetail',id,'secondary')+btn('查看装备库','heroTab','equipment'));
}
function heroEquipmentModal(eid){
 const e=S().equipment.find(e=>e.id===eid);if(!e){toast('装备不存在');return;}
 const q=HeroSystem.enhanceQuote(e),busy=e.hero&&Game.generalBusy(e.hero),eligible=S().generals.filter(id=>!Game.generalBusy(id)&&S().generalLevels[id]>=HeroSystem.requiredLevel(e));
 showModal('装备 · '+HeroSystem.itemName(e),`${heroEquipmentIcon(e)}<p class="sub">${HeroSystem.qualities[e.tier]} · ${HeroSystem.slots[e.slot]} · 强化 +${e.enhance}/10 · 需要将领 ${HeroSystem.requiredLevel(e)} 级</p><p class="notice">${heroStatsHTML(HeroSystem.stats(e))}</p><p class="hint">${e.hero?'穿戴者：'+esc(Game.general(e.hero).name):'闲置装备'}</p>${eligible.length?`<label class="label" for="equipment-hero">穿戴给</label><select id="equipment-hero">${eligible.map(id=>`<option value="${id}" ${id===e.hero?'selected':''}>${esc(Game.general(id).name)} · Lv.${Game.general(id).level}</option>`).join('')}</select>${btn('确认穿戴 / 转交','heroEquipSelected',String(eid),'block',!!busy)}`:'<p class="hint">没有空闲且等级适用的将领。</p>'}${e.hero?btn('卸下装备','heroUnequip',String(eid),'secondary block',!!busy):''}<div class="divider"></div><h3>强化</h3>${e.enhance<10?`<p class="hint">下一阶：${heroStatsHTML(HeroSystem.stats({...e,enhance:e.enhance+1}))}</p><p class="hint">需要黄金 ${num(q.gold)} · 强化宝珠 ×${q.pearls}（持有 ${S().inventory.pearl||0}）</p>`:'<p class="notice">已强化至最高 +10</p>'}<p class="hint">试玩规则：每阶增加基础属性的 15%，保证成功；需要铁匠铺 1 级。每件装备独立保存强化等级。</p>${btn(e.enhance>=10?'强化已满':'强化一次','heroEnhance',String(eid),'block',!!busy||e.enhance>=10||S().buildings.smith<1)}${!e.hero?`<div class="divider"></div><p class="hint">分解可得强化宝珠 ×${e.tier+Math.floor(e.enhance/3)}，消耗过的黄金不返还。</p>${btn('分解装备','heroSalvageAsk',String(eid),'danger block')}`:''}`,btn('返回背包','manualInventory','','secondary')+btn('装备库','heroTab','equipment','secondary')+(e.hero?btn('返回将领','heroDetail',e.hero):''));
}
function heroForgeModal(){
 showModal('铁匠铺 · 装备打造',`<p class="sub">当前铁匠铺 ${S().buildings.smith} 级 · 装备 ${S().equipment.length}/${S().equipmentCapacity}</p><p class="notice">普通 / 精良 / 珍稀分别需要铁匠铺 1 / 3 / 6 级；打造保证成功，得到指定装备。数值为试玩规则。</p><div class="equipment-grid forge-grid">${[1,2,3].flatMap(tier=>Object.keys(HeroSystem.slots).map(slot=>{const q=HeroSystem.forgeQuote(slot,tier),e={slot,tier,enhance:0};return `<article class="equipment-card quality-${tier}">${heroEquipmentIcon(e)}<h3>${HeroSystem.qualities[tier]} · ${HeroSystem.itemName(e)}</h3><p class="hint">${heroStatsHTML(HeroSystem.stats(e))}<br>穿戴要求 Lv.${HeroSystem.requiredLevel(e)} · 铁匠铺 ${q.smith} 级</p>${costs(q.cost)}${btn('打造一件','heroCraft',slot+'|'+tier,'block',S().buildings.smith<q.smith||!Game.canPay(q.cost)||S().equipment.length>=S().equipmentCapacity)}</article>`;})).join('')}</div>`,btn('返回装备库','heroTab','equipment','secondary'));
}
function heroEquipmentDropsHTML(result){return `${result.equipmentDrops?.length?`<div class="notice">缴获装备：${result.equipmentDrops.map(e=>HeroSystem.qualities[e.tier]+' · '+HeroSystem.itemName(e)).join('、')} · 已收入装备库 ${btn('查看装备','heroTab','equipment','small secondary')}</div>`:''}${result.equipmentDiscarded?'<p class="notice">装备库已满，1 件装备未能收取。请分解闲置装备或使用武器架扩容。</p>':''}`;}
function heroSkillCostHTML(cost){return `<p class="hint">军功 ${num(cost.merit)} · 黄金 ${num(cost.gold)}${Object.entries(cost.jewels||{}).map(([id,n])=>' · '+(Progression.jewels[id]?.name||id)+' ×'+n).join('')}</p>`;}
function heroSkillSummaryHTML(id){const skill=S().heroSkills?.[id],route=GeneralGrowth.routes.find(r=>r.id===skill?.route);return `<section class="hero-skill-summary"><div class="section-title"><h3>将领专长</h3><span class="badge">${route?esc(route.name)+' '+skill.level+'/5':'尚未选择'}</span></div><p class="hint">${route?esc(route.description):'骑军、弓军、攻城、内政四选一。军功、黄金与珍宝用于逐级培养。'}</p>${btn(route?'培养专长':'选择培养路线','heroSkillAsk',id,'secondary')}</section>`;}
function heroSkillModal(id){
 if(!S().generals.includes(id)){toast('请选择帐下将领');return;}
 showModal('专长培养 · '+esc(Game.general(id).name),`<p class="notice">每名将领只能选择一条路线，首次学习后不能改换。最高 5 级，升级条件和费用以本次预览为准。</p><div class="hero-skill-grid">${GeneralGrowth.routes.map(route=>{const q=GeneralGrowth.trainQuote(S(),id,route.id,{generalBusy:Game.generalBusy}),chosen=S().heroSkills?.[id]?.route===route.id;return `<article class="panel ${chosen?'is-current':''}"><div class="section-title"><h3>${esc(route.name)}</h3><span class="badge">${chosen?'已选 '+q.level+'/5':'互斥路线'}</span></div><p class="hint">${esc(route.description)}</p>${heroSkillCostHTML(q.cost)}${q.reason?`<p class="hint">${esc(q.reason)}</p>`:''}${btn(q.level>=5&&chosen?'已达最高级':chosen?'提升至 '+q.next+' 级':'选择并学习 1 级','heroSkillReview',id+'~'+route.id,'block',!!q.reason)}</article>`;}).join('')}</div>`,btn('返回培养','heroDetail',id,'secondary'));
}
function heroSkillReview(id,route){
 const q=GeneralGrowth.trainQuote(S(),id,route,{generalBusy:Game.generalBusy});if(!q){toast('培养路线不存在');return;}
 showModal('确认学习 · '+esc(q.name),`<p class="sub">${esc(Game.general(id).name)} · ${q.level} → ${q.next} 级</p><p class="hint">${esc(q.description)}</p>${heroSkillCostHTML(q.cost)}${q.level===0?'<p class="notice">确认后该将领固定选择此路线，其他三条路线将关闭。</p>':''}${q.reason?`<p class="notice">${esc(q.reason)}</p>`:''}`,btn('返回选择','heroSkillAsk',id,'secondary')+btn('支付并学习','heroSkillTrain',id+'~'+route+'~'+q.key,'',!!q.reason));
}
function heroCodexModal(){
 const entries=HeroSystem.wild.codex(S()),statuses={undiscovered:'待打听',active:'在野',captive:'已俘获',recruited:'已归顺',released:'已释放'};
 showModal('将领图鉴 · 十二路群英',`<p class="sub">客栈打听线索，购买对应画像，击败守军后俘获，再支付招降费用。历史将领的初始属性为本作设定。</p><div class="hero-codex-grid">${entries.map(d=>{const rumor=S().wildGenerals.rumors.find(r=>r.line===d.line);return `<article class="hero-codex-entry ${d.locked?'locked':''}"><div class="section-title"><h3>${esc(d.name)}</h3><span class="badge">${d.locked?'条件未达':statuses[d.status]||d.status}</span></div><p class="hint">${esc(d.region)} · ${esc(d.title)}<br>客栈 ${d.minInn||1} 级 · ${HeritageData.nobles[d.noble]?.name||'—'}及以上</p>${wildGeneralStatsHTML(d)}<p class="hint">画像：${d.portraitOwned?'已拥有':'尚未购买'}${d.reason?'<br>'+esc(d.reason):''}</p><div class="guide-actions">${d.status==='recruited'?btn('培养','heroDetail',d.heroId||rumor?.id,'small secondary'):d.status==='active'&&rumor?btn('地图定位','wildRumorGo',rumor.id,'small'):btn('查看线索与俘将','wildGenerals','','small secondary')}${!d.portraitOwned?btn('画像条件','wildPortraitAsk',d.line,'small secondary'):''}</div></article>`;}).join('')}</div>`,btn('客栈线索','wildGenerals','','secondary')+btn('关闭','close','','secondary'));
 manualModalContext=heroCodexModal;
}
document.addEventListener('click',event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id||el.dataset.arg||'';
 if(!a.startsWith('hero'))return;
 if(a==='heroTab'){heroTab=id;page='heroes';modal.close();render();}
 if(a==='heroEquipmentFilter'){equipmentFilter=id;equipmentPage=0;render();}
 if(a==='heroEquipmentPage'){equipmentPage=Math.max(0,Number(id));render();}
 if(a==='heroGift')actResult(HeroSystem.gift(),'领取成功：两套普通装备、5 枚强化宝珠、2 枚洗髓丹');
 if(a==='heroDetail')heroDetailModal(id);
 if(a==='heroCodex')heroCodexModal();
 if(a==='heroSkillAsk')heroSkillModal(id);
 if(a==='heroSkillReview'){const [hero,route]=id.split('~');heroSkillReview(hero,route);}
 if(a==='heroSkillTrain'){const [hero,route,...key]=id.split('~');if(actResult(Game.trainGeneralSkill(hero,route,key.join('~')),'技能已提升'))heroSkillModal(hero);}
 if(a==='heroClear')modalBody.querySelectorAll('[data-hero-point]').forEach(input=>input.value=0);
 if(a==='heroAllocate'){const points=Object.fromEntries([...modalBody.querySelectorAll('[data-hero-point]')].map(input=>[input.dataset.heroPoint,Number(input.value)]));if(actResult(HeroSystem.allocate(id,points),'属性点已分配'))heroDetailModal(id);}
 if(a==='heroDrill'&&actResult(HeroSystem.drill(id),'操练完成，经验 +80'))heroDetailModal(id);
 if(a==='heroResetAsk')showModal('确认洗髓',`<p class="sub">消耗洗髓丹 ×${Math.ceil(S().generalLevels[id]/10)}，返还 ${HeroSystem.totalPoints(S(),id)-HeroSystem.remaining(S(),id)} 个已分配点数。保留等级、经验和装备。</p>`,btn('取消','heroDetail',id,'secondary')+btn('确认重置','heroReset',id));
 if(a==='heroReset'&&actResult(HeroSystem.reset(id),'属性点已返还'))heroDetailModal(id);
 if(a==='heroEquipment')heroEquipmentModal(Number(id));
 if(a==='heroPickEquipment'){const [hero,slot]=id.split('|');heroPickEquipmentModal(hero,slot);}
 if(a==='heroEquip'){const [eid,hero]=id.split('|');if(actResult(HeroSystem.equip(Number(eid),hero),'装备已穿戴'))heroDetailModal(hero);}
 if(a==='heroEquipSelected'){const hero=document.getElementById('equipment-hero')?.value;if(actResult(HeroSystem.equip(Number(id),hero),'装备已穿戴'))heroEquipmentModal(Number(id));}
 if(a==='heroUnequip'&&actResult(HeroSystem.unequip(Number(id)),'装备已卸下'))heroEquipmentModal(Number(id));
 if(a==='heroEnhance'&&actResult(HeroSystem.enhance(Number(id)),'强化成功'))heroEquipmentModal(Number(id));
 if(a==='heroForge')heroForgeModal();
 if(a==='heroCraft'){const [slot,tier]=id.split('|');if(actResult(HeroSystem.forge(slot,Number(tier)),'装备打造完成'))heroForgeModal();}
 if(a==='heroSalvageAsk'){const e=S().equipment.find(e=>e.id===Number(id));if(e)showModal('确认分解装备',`<p class="sub">分解 ${HeroSystem.itemName(e)} +${e.enhance}，获得强化宝珠 ×${e.tier+Math.floor(e.enhance/3)}。装备会永久消失。</p>`,btn('取消','heroEquipment',id,'secondary')+btn('确认分解','heroSalvage',id,'danger'));}
 if(a==='heroSalvage'&&actResult(HeroSystem.salvage(Number(id)),'装备已分解，强化宝珠已到账'))heroEquipmentPageOpen();
});
