'use strict';
function mainlineModel(){
  const s=S(),groups=Game.progression.groups(s),captured=(s.wildGenerals?.recruited?.length||0)>0;
  const stages=[
    {id:'city',name:'建立城池',done:s.buildings.hall>=2,status:'官府 '+s.buildings.hall+' / 2 级；城内外建设和弓兵前置可按下方成长引导完成。',mission:'hall2',reward:'四资源各 8,000 · 黄金 12,000 · 声望 300',action:'classicGuideGo',label:'继续建设与弓兵路线'},
    {id:'battle',name:'弓兵首战',done:s.stats.victories>=1,status:'出征胜利 '+Math.min(1,s.stats.victories)+' / 1 场 · 已有弓兵 '+GrowthGuide.held(Game,'archer')+' / 30 名。先侦察，再配兵；胜利后查看损失并补兵。',mission:'firstVictory',reward:'粮食、木材、铁锭各 6,000 · 黄金 6,000 · 声望 300',action:'mainlineFirstBattle',label:'查看首战与当前队伍'},
    {id:'general',name:'招降野地将领',done:captured,status:captured?'已通过野地线索招降将领。':s.wildGenerals?.captives?.length?'已俘获将领，核对招贤馆空位及招降费用。':'客栈打听 → 购买对应画像 → 地图寻找 → 击败守军 → 俘获 → 招降。首位游侠建议以轻骑兵快速奔袭。军营 '+s.buildings.barracks+' / 5 级 · 驾驭技巧 '+s.tech.riding+' / 1 级 · 驻城轻骑兵 '+s.army.cavalry+' / 建议 30 名 · 招贤馆 '+HeroSystem.wild.roomUsed(s)+' / '+s.buildings.tavern+' 间（俘将占1间）。陈岚画像 '+(HeroSystem.wild.portraitOwned(s,'wanderer')?'已持有':'未持有，需 10 元宝')+'，永久保留。招降无需爵位，费用另需黄金 6,000 或珍珠 1。',mission:'wildGeneral',reward:'粮食、木材、铁锭各 3,000 · 声望 300；将领需支付招降费用',action:'wildGenerals',label:'查看野地抓将'},
    {id:'epic',mission:'countyAccess',name:'完成黄巾史诗',done:Game.countyUnlocked(),status:groups.map(g=>g.name+' '+Math.min(100,Math.floor(g.progress*100))+'%').join(' · '),reward:'开放古渡县城进军；捐献奖励以史诗面板预览为准',action:'taskTab',arg:'epic',label:'查看四项史诗与差额'},
    {id:'county',name:'攻下第一座县城',done:!!s.conquered.fort,status:s.conquered.fort?'古渡县城已归属你，第二章已开启。':!Game.landmarkVisible('fort')?'先推进当前任务据点 '+(Game.nextLandmark()?.name||'')+'，逐站发现古渡县城。':'古渡县城尚未占领；需要破城、歼灭守军，并将民心降到 0 以下。',mission:'fort',reward:'粮食 6,000 · 木材、石料、铁锭各 4,000 · 黄金 30,000 · 声望 300；开启第二章',action:'mainlineCounty',label:'查看当前据点与占领'}
  ];
  for(const stage of stages){const mission=Game.missions.find(m=>m.id===stage.mission);if(mission){const extras=stage.id==='general'?'；将领另需支付招降费用':stage.id==='epic'?'；开放县城进军':stage.id==='county'?'；开启第二章':'';stage.reward=Object.entries(mission.reward).filter(([,n])=>n>0).map(([id,n])=>Game.resources[id].name+' '+num(n)).join(' · ')+Object.entries(mission.items||{}).map(([id,n])=>' · '+Game.manual.shop.find(i=>i.id===id).name+' ×'+n).join('')+' · 声望 300'+extras;}}
  const current=stages.find(x=>!x.done),ready=stages.map(x=>x.mission&&Game.missions.find(m=>m.id===x.mission)).filter(m=>m&&Game.missionReady(m));
  return {stages,current,ready};
}
function mainlineGuideHTML(){
  const m=mainlineModel(),goal=m.current,done=m.stages.filter(x=>x.done).length;
  return `<section class="mainline-guide" aria-label="当前主线目标"><div class="mainline-heading"><span class="label">主线征程 · ${done} / 5 达成</span>${m.ready.length?btn('领取主线补给（'+m.ready.length+'）','mainlineClaim','','small'):''}</div><div class="mainline-stages" aria-label="五阶段进度">${m.stages.map((x,i)=>`<span class="${x.done?'done':x===goal?'current':''}">${x.done?'✓':i+1} ${x.name}</span>`).join('')}</div><h2>${goal?esc(goal.name):'一县之主 · 向北境进军'}</h2><p class="hint">${esc(goal?goal.status:'五阶段主线已达成。继续按章节逐关占领，并查看一次性通关补给。')}</p><p class="mainline-reward">${goal?'完成奖励：'+esc(goal.reward):'后续奖励：以当前章节的通关补给卡片为准。'}</p>${goal?.mission&&Game.missionClaimed(goal.mission)?'<p class="hint">这项任务奖励已领取。</p>':''}<div class="guide-actions">${goal?btn(goal.label,goal.action,goal.arg||'','small'):btn('查看章节路线','taskTab','chapter','small')}${btn('补给来源与补兵账本','supplyBridge','','small secondary')}</div></section>`;
}
function supplyBridgeModal(){
  const s=S(),archerCost=Game.trainCost('archer',30),reports=s.reports.filter(r=>r.mode==='raid'&&r.won&&r.resourceReceipt).slice(0,5);
  const total=o=>Object.values(o||{}).reduce((n,v)=>n+v,0),loss=r=>Object.entries(r.lost||{}).reduce((n,[id,count])=>n+total(Game.units[id]?.cost)*count,0),received=r=>total(r.resourceReceipt.base.received)+total(r.resourceReceipt.bonus.received);
  showModal('补给来源与补兵账本',`<section class="supply-stage"><h3>前期 · 建城与首支弓兵队</h3><p class="hint">先领取十阶礼包与已完成任务，建设民房、资源田、军营和书院。30 弓兵的训练材料如下，人口与科技前置仍须满足；加速在队列里选择使用。</p>${costs(archerCost)}${resourceWaitHTML(archerCost)}<div class="guide-actions">${btn('领取已完成任务','guideRewards','','small')}${btn('查看礼包与加速','onboardingGifts','','small secondary')}</div></section><section class="supply-stage"><h3>中期 · 侦察与掠夺补给</h3><p class="hint">先接每日讨伐或缴获任务，再侦察适合当前兵力的资源野地。以弓兵输出、步兵保护，必要时带辎重部队提高负重。3 级起的普通野地掠夺额外提供两倍基础资源，仍受部队负重限制。同一目标再次掠夺仅有 60% 基础收益；满仓可入库，装不下的资源留在战场。</p><p class="hint">下表使用最近 5 场胜利掠夺的实际入库与永久损失。资源总量按市场 1:1 等价，伤兵不算补兵成本；不含行军耗粮、时间、珠宝与装备价值，不能当作完整利润。</p>${reports.length?`<div class="supply-ledger-scroll"><table class="supply-ledger"><thead><tr><th>目标</th><th>实际入库</th><th>永久损失补兵</th><th>物资差额</th></tr></thead><tbody>${reports.map(r=>`<tr><th>${esc(Game.getNode(r.node)?.name||r.node)}</th><td>${num(received(r))}</td><td>${num(loss(r))}</td><td class="${received(r)<loss(r)?'short':''}">${num(received(r)-loss(r))}</td></tr>`).join('')}</tbody></table></div>`:'<p class="notice">尚无可核算的胜利掠夺战报。首战后会出现实际记录。</p>'}${btn('查看每日征战任务','taskTab','daily','small secondary')}</section><section class="supply-stage"><h3>后期 · 领地、采集与俸禄</h3><p class="hint">占领资源野地取得产量加成；保留驻军可采集，满 1 小时后收获资源与概率珍宝。驻军耗粮为城内的两倍，应控制规模。官职每日领黄金，爵位每日领四资源；领取前查看条件与收入。</p><div class="guide-actions">${btn('查看领地与驻军','classicTerritory','','small secondary')}${btn('查看采集收获','heritageGatherBoard','','small secondary')}${btn('查看每日俸禄','taskTab','honors','small secondary')}</div></section>`,btn('关闭','close','','secondary'));
}
document.addEventListener('click',event=>{
  const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;
  if(a==='mainlineClaim'){const ready=mainlineModel().ready;let count=0;for(const m of ready)if(!Game.claimMission(m.id))count++;actResult(count?null:'暂无可领主线补给',count+' 项主线补给已到账');render();}
  if(a==='mainlineFirstBattle'){const s=S();if(s.battle||Game.allExpeditions().length){page='world';render();}else if(!GrowthGuide.archerComplete(Game))onboardingRouteModal();else {page='world';selectedNode='field';worldView={x:Game.getNode('field').x,y:Game.getNode('field').y};render();worldNodeModal('field');}}
  if(a==='mainlineCounty'){const n=Game.landmarkVisible('fort')?Game.getNode('fort'):Game.nextLandmark();if(n){page='world';selectedNode=n.id;worldView={x:n.x,y:n.y};render();worldNodeModal(n.id);}}
  if(a==='supplyBridge')supplyBridgeModal();
});
