'use strict';
const OnboardingSystem=(()=>{
  function init(s){if(s.onboarding===undefined)s.onboarding={schema:1,claims:[],hidden:false,lastOpen:null};}
  function valid(s){const o=s.onboarding;if(!o||o.schema!==1||typeof o.hidden!=='boolean'||!Array.isArray(o.claims)||new Set(o.claims).size!==o.claims.length||!o.claims.every(n=>Number.isInteger(n)&&n>=1&&n<=10&&n<=s.buildings.hall))return false;const r=o.lastOpen;return r===null||!!r&&typeof r==='object'&&(r.kind==='jewel'&&Progression.jewels[r.id]&&Number.isInteger(r.count)&&r.count>=2&&r.count<=5||r.kind==='equipment'&&Number.isSafeInteger(r.id)&&r.id>0&&r.id<=s.equipmentSeq);}
  function quote(s,level){const gift=OnboardingData.gifts.find(x=>x.level===level);if(!gift)return null;const resources={...gift.resources};if(level===1)for(const id of Object.keys(resources))resources[id]=Math.max(0,resources[id]-(s.starterGiftVersion>=2?gift.resources[id]:s.starterGiftVersion===1?20000:0));return {...gift,resources,items:{...gift.items},claimed:s.onboarding.claims.includes(level),unlocked:s.buildings.hall>=level};}
  function available(s){return OnboardingData.gifts.filter(g=>s.buildings.hall>=g.level&&!s.onboarding.claims.includes(g.level));}
  function claim(level){Game.tick(Date.now(),false);const s=Game.state,q=quote(s,level);if(!q)return '请选择 1–10 阶礼包';if(q.claimed)return '这一阶礼包已领取';if(!q.unlocked)return '需要官府 '+level+' 级';for(const [id,n]of Object.entries(q.resources))s.res[id]+=n;for(const [id,n]of Object.entries(q.items))s.inventory[id]=(s.inventory[id]||0)+n;if(level===1){s.starterGiftVersion=2;s.starterGiftClaimed=true;}s.onboarding.claims.push(level);Game.save();return null;}
  function openItem(id,slot){const s=Game.state,item=ManualData.shop.find(x=>x.id===id);if(!(s.inventory[id]>0))return '没有可开启的盒子';if(item?.effect==='jewelBox'){const spec=OnboardingData.jewels;let roll=Math.random()*Object.values(spec.weights).reduce((a,b)=>a+b,0),jewel=Object.keys(spec.weights).at(-1);for(const [key,w]of Object.entries(spec.weights)){roll-=w;if(roll<0){jewel=key;break;}}const count=spec.min+Math.floor(Math.random()*(spec.max-spec.min+1));s.jewels[jewel]+=count;s.onboarding.lastOpen={kind:'jewel',id:jewel,count};}else if(item?.effect==='equipmentBox'){if(!Object.hasOwn(HeroSystem.slots,slot))return '请选择装备部位';if(s.equipment.length>=s.equipmentCapacity)return '装备库已满，盒子已保留，请先整理装备';const e=HeroSystem.addEquipment(s,slot,item.tier);s.onboarding.lastOpen={kind:'equipment',id:e.id};}else return '请选择珠宝盒或装备盒';s.inventory[id]--;Progression.record(s,'item');Game.save();return null;}
  function hide(hidden){Game.state.onboarding.hidden=!!hidden;Game.save();}
  return {init,valid,quote,available,claim,openItem,hide};
})();
