'use strict';
let onlineMarchDraft=null,onlinePrivateReviewed=false;
function onlineMapDecorate(){
 const s=OnlineClient.status(),w=s.world;if(s.mode!=='shared'||!w)return;const own=s.user.id;
 for(const cell of document.querySelectorAll('.world-cell[data-x][data-y]')){
  cell.querySelector('[data-online-pin]')?.remove();const x=Number(cell.dataset.x),y=Number(cell.dataset.y),capital=w.players.find(p=>p.home?.x===x&&p.home?.y===y),city=w.cities.find(c=>c.owner&&c.x===x&&c.y===y),owner=capital?.id||city?.owner;if(!owner)continue;
  const player=w.players.find(p=>p.id===owner),same=owner===own,ally=!same&&w.membership&&player?.alliance===w.membership.alliance,mine=w.alliances.find(a=>a.id===w.membership?.alliance),other=w.alliances.find(a=>a.id===player?.alliance),relations=[mine?.relations?.[other?.id],other?.relations?.[mine?.id]],enemy=relations.some(r=>r?.status==='enemy'),friendly=relations.some(r=>r?.status==='friendly'),label=same?'我方':ally?'同盟':enemy?'敌对':friendly?'友好':'玩家',color=same?'#325e50':ally?'#355d36':enemy?'#7d3030':friendly?'#325975':'#62533b',pin=document.createElement('span');
  pin.dataset.onlinePin=owner;pin.className='world-site-name';pin.style.cssText='background:'+color+';color:#fff;padding:2px 4px;border-radius:3px;z-index:4;max-width:96%;';pin.textContent=label+' · '+(city?.name||player?.name||'城池');cell.append(pin);
 }
}
document.addEventListener('click',event=>{const s=OnlineClient.status();if(s.mode!=='shared'||!s.world)return;const cell=event.target.closest('.world-cell[data-x][data-y]'),pin=cell?.querySelector('[data-online-pin]');if(!pin)return;const owner=pin.dataset.onlinePin;if(owner!==s.user.id){event.preventDefault();event.stopImmediatePropagation();onlinePlayerCitiesModal(owner);}},true);
function onlineStatusHTML(){const s=OnlineClient.status();if(s.mode!=='shared')return ''; return `<div class="online-session-bar" role="status"><span>共享世界 · ${esc(s.config?.realm||'china-1')} · ${s.busy?'提交中…':'版本 '+s.revision}${s.lastError?' · '+esc(s.lastError):''}</span>${btn('共享地图','onlineWorld','','small secondary')}${s.lastCode==='SETTLEMENT_REQUIRED'?btn('结算已抵达部队','onlineSettle','','small'):s.uncertain?btn('重试上条指令','onlineRetry','','small'):s.lastError?btn('刷新进度','onlineRefresh','','small'):''}${btn('账号','onlineAccount','','small secondary')}</div>`;}
function refreshOnlineStatus(){onlineMapDecorate();const s=OnlineClient.status();document.querySelectorAll('[data-online-status]').forEach(el=>el.innerHTML=onlineStatusHTML());document.body.classList.toggle('online-busy',!!s.busy);document.querySelectorAll('[data-online-busy]').forEach(el=>{el.textContent=s.busy?'正在连接云端…':s.lastError||'';});}
function onlineAccountModal(){
 const s=OnlineClient.status();
 let body=`<p class="notice">单机进度保留在当前浏览器。私人云档用于跨设备继续自己的城池；共享世界使用服务器新档，名将、城市归属与玩家行动共同结算。</p>`;
 if(!s.configured)body+='<p class="sub">共享世界服务尚未配置，单机游戏可继续使用。</p>'+btn('配置云端连接','onlineConfig','','secondary');
 else if(!s.user)body+=`<form class="online-auth-form" id="online-auth-form"><label for="online-email">邮箱</label><input id="online-email" type="email" autocomplete="username" required><label for="online-password">密码</label><input id="online-password" type="password" autocomplete="current-password" minlength="6" required><p class="hint">注册可能需要邮件验证，验证后再登录。</p><div class="online-actions">${btn('登录','onlineLogin')}${btn('注册账号','onlineRegister','','secondary')}</div></form>${btn('连接设置','onlineConfig','','secondary')}`;
 else body+=`<p class="sub">账号：${esc(s.user.email||'已登录')} · 当前${s.mode==='shared'?'共享世界':'单机进度'}</p><section class="panel"><h3>私人云档</h3><p class="hint">手动保存与下载，设备间版本冲突会保留当前单机进度。</p><div class="online-actions">${btn('保存当前单机至云端','onlinePrivateSave','','secondary',s.mode==='shared')}${btn('查看云档再恢复','onlinePrivateRead','','secondary',s.mode==='shared')}</div></section><section class="panel"><h3>共享世界</h3><p class="hint">${s.mode==='shared'?'建设、征战与培养提交给服务器，地图约每 15 秒刷新。':'首次加入从新城开始；已有共享城池可读取继续。'}</p><div class="online-actions">${s.mode==='shared'?btn('共享地图 / 联盟','onlineWorld')+btn('返回原单机进度','onlineLeaveAsk','','secondary'):btn('读取已有共享城池','onlineResume')+btn('加入共享世界 · 新城','onlineSharedStartAsk','','secondary')}</div></section>${s.privateConflict?btn('处理私人云档冲突','onlinePrivateConflict','','secondary block'):''}<div class="online-actions">${btn('退出账号','onlineLogout','','secondary')}${btn('连接设置','onlineConfig','','secondary')}</div>`;
 if(s.lastError)body+=`<p class="notice">${esc(s.lastError)}</p>${s.lastCode==='SETTLEMENT_REQUIRED'?btn('先结算已抵达部队','onlineSettle','','secondary'):''}${s.uncertain?btn('重试同一条指令','onlineRetry','','secondary'):s.mode==='shared'?btn('重新读取云端进度','onlineRefresh','','secondary'):''}`;
 body+='<p class="hint" data-online-busy role="status"></p>';
 showModal('账号与云端游戏',body,btn('继续游戏','close','','secondary'));
}
function onlineConfigModal(){const s=OnlineClient.status();showModal('云端连接设置',`<p class="hint">由游戏部署提供项目地址与公开密钥。只接收 publishable / anon key；账号密码只提交给该项目的登录服务。</p><label for="online-url">Supabase 项目地址</label><input id="online-url" type="url" value="${esc(s.config?.url||'')}" placeholder="https://项目.supabase.co" autocomplete="off"><label for="online-key">Publishable key</label><input id="online-key" type="password" value="" placeholder="sb_publishable_…" autocomplete="off"><label for="online-realm">世界编号</label><input id="online-realm" maxlength="40" value="${esc(s.config?.realm||'china-1')}"><p class="hint">连接设置仅保存在此浏览器。更换项目会退出当前账号。</p>`,btn('返回账号','onlineAccount','','secondary')+btn('保存连接','onlineConfigSave','', '',s.mode==='shared'));}
function onlineSharedStartAsk(){showModal('加入共享世界 · 建立新城',`<p class="notice">共享世界由服务器创建独立新城，使用正常时间。当前单机城池、物资与将领保留，返回单机后可继续。</p><p class="hint">已有共享城池时应选择「读取已有共享城池」。玩家争夺同一名将与城池，归属按服务器到达和战斗结算决定。</p>`,btn('返回','onlineAccount','','secondary')+btn('确认建立共享新城','onlineCreateShared'));}
function onlinePrivateReviewModal(){const s=OnlineClient.status(),candidate=s.privateCandidate;onlinePrivateReviewed=!!candidate;showModal('私人云档预览',candidate?`<p class="sub">云端版本 ${s.privateRevision} · ${esc(candidate.ruler||'城主')} · 官府 ${candidate.buildings?.hall||1} 级</p><p class="hint">存档时刻：${new Date(candidate.last).toLocaleString('zh-CN')}<br>帐下将领 ${candidate.generals?.length||0} · 军队 ${num(Game.totalArmy(candidate.army||{}))} 人</p><p class="notice">确认恢复会替换本浏览器单机进度，替换前自动导出当前进度为备份。其他设备的进度不会被这次下载覆盖。</p>`:'<p class="notice">账号还没有私人云档。可先在此设备保存单机进度。</p>',btn('保留本地','onlineAccount','','secondary')+(candidate?btn('导出本地备份并恢复云档','onlinePrivateImport'):''));}
function onlinePrivateConflictModal(){const s=OnlineClient.status();showModal('私人云档版本冲突',`<p class="notice">另一台设备已更新云档，本次保存没有覆盖它。当前单机进度仍保留在本浏览器。</p><p class="hint">可以导出当前进度作为另一份存档，或读取云档预览后明确恢复；不会自动合并两份城池。</p>`,btn('导出当前单机','exportSave','','secondary')+btn('保留本地继续','onlineConflictKeep','','secondary')+btn('读取云档预览','onlinePrivateRead'));}
function onlineWorldModal(){
 const s=OnlineClient.status(),w=s.world;if(s.mode!=='shared'||!w){onlineAccountModal();return;}
 const own=s.user.id,ownerName=id=>!id?'无主':id===own?'我方':w.players.find(p=>p.id===id)?.name||'其他玩家';
 const players=w.players.map(p=>{const protectedAt=Math.max(p.policy?.protectionUntil||0,p.policy?.peaceUntil||0),war=w.policy?.declarations?.find(d=>d.target===p.id&&d.endsAt>OnlineClient.now());return `<article class="online-world-row"><div><strong>${esc(p.name)}</strong><p class="hint">(${p.home?.x??'—'}, ${p.home?.y??'—'}) · 官府 ${p.level} 级${p.id===own?' · 我方':protectedAt>OnlineClient.now()?' · 保护 '+duration((protectedAt-OnlineClient.now())/1000):war?war.startsAt>OnlineClient.now()?' · 备战 '+duration((war.startsAt-OnlineClient.now())/1000):' · 战争中':''}</p></div><div class="online-row-actions">${p.id===own?btn('治下城市','citySwitchList','','small secondary'):btn('城池 / 出征','onlinePlayerCities',p.id,'small secondary')+btn('宣战','onlineDeclareAsk',p.id,'small secondary',protectedAt>OnlineClient.now())}</div></article>`;}).join('');
 const heroes=w.heroes.map(h=>`<article class="online-world-row"><div><strong>${esc(h.name)}</strong><p class="hint">${esc(ownerName(h.owner))} · ${h.status==='wild'?'在野':h.status==='captured'?'已被俘获':'已归顺'}${h.node?' · '+esc(h.node):''}</p></div>${!h.owner?btn('前往抓将','onlineMarchAsk','hunt~'+h.line,'small secondary'):''}</article>`).join('');
 const cities=w.cities.map(c=>`<article class="online-world-row"><div><strong>${esc(c.name)}</strong><p class="hint">${esc(ownerName(c.owner))}</p></div>${Game.getNode(c.id)?btn('地图定位','yellowCityView',c.id,'small secondary'):''}</article>`).join('');
 showModal('共享世界 · '+esc(s.config.realm),`<div class="online-actions">${btn('刷新世界','onlineRefresh','','secondary')}${btn('联盟与领土','onlineAllianceList','','secondary')}${btn('玩家市场','onlineMarket','','secondary')}${btn('战争与保护','onlineWarPolicy','','secondary')}${btn('结算已抵达队伍','onlineSettle','','secondary')}${btn('将领画像','wildPortraitShop','','secondary')}</div><p class="hint">读图不会主动结算战斗。队伍抵达后提交结算，按服务器时间与归属版本处理争夺；返程结束也从此结算。</p><h3>玩家城池 · ${w.players.length}</h3><div class="online-world-list">${players||'<p class="hint">暂无其他城池。</p>'}</div><details><summary>共享名将 · ${w.heroes.length} 位</summary><div class="online-world-list">${heroes}</div></details><details><summary>共享城市 · ${w.cities.length} 座</summary><div class="online-world-list">${cities}</div></details><h3>往来部队</h3>${onlineMarchesHTML(w,own)}${onlineBattleReportsHTML(w,own)}`,btn('账号','onlineAccount','','secondary')+btn('关闭','close','','secondary'));
 manualModalContext=onlineWorldModal;
}
function onlineMarchesHTML(w,own){
 const sharedCityName=(owner,id)=>id==='capital'?(w.players.find(p=>p.id===owner)?.name||'城主')+'主城':w.cities.find(c=>c.owner===owner&&c.cityId===id)?.name||(owner===own?cityName(id):id);
 return `<div class="online-world-list">${w.marches.filter(m=>m.status!=='done').map(m=>{const trade=m.kind==='trade',from=trade?m.target:m.source,to=trade?m.source:m.target,source=w.players.find(p=>p.id===from)?.name||'城主',target=w.players.find(p=>p.id===to)?.name||(m.line?'名将据点':'目的地'),label={aid:'援军',hunt:'抓将',pvp:'讨伐',trade:'市场送货'}[m.kind]||m.kind,end=m.status==='return'?m.returnAt:m.arrive,route=trade?' · 出发 '+esc(sharedCityName(m.target,m.targetCity||'capital'))+' · 抵达 '+esc(sharedCityName(m.source,m.sourceCity||'capital')):m.sourceCity?' · 出发 '+esc(cityName(m.sourceCity)):'';return `<article class="online-world-row"><div><strong>${esc(label)} · ${esc(source)} → ${esc(target)}</strong><p class="hint">${m.status==='stationed'?'驻扎中':m.status==='return'?'返程中':'行军中'}${trade?' · '+num(m.quantity)+' '+esc(Game.resources[m.resource]?.name||m.resource)+' · 黄金 '+num(m.gold):m.army?' · '+num(Game.totalArmy(m.army))+' 人':''}${m.evacuatedFrom?' · 失城后改回主城':''}${route}${m.status!=='stationed'&&end?' · '+duration((end-OnlineClient.now())/1000)+' · 预计 '+new Date(end).toLocaleTimeString('zh-CN'):''}</p></div>${m.kind==='aid'&&m.status==='stationed'&&m.source===own?btn('召回援军','onlineRecallAidAsk',m.id,'small secondary'):''}</article>`;}).join('')||'<p class="hint">暂无共享世界行军。</p>'}</div>`;
}
function onlineBattleReportsHTML(w,own){
 const reports=w.reports||[];if(!reports.length)return '<p class="hint">暂无共享世界战报，战斗完成结算后显示。</p>';
 return `<details class="online-battle-reports"><summary>共享战报 · 最近 ${reports.length} 份</summary><div class="online-world-list">${reports.map(r=>{
  const attacking=r.source===own,won=attacking?r.won:!r.won,losses=attacking?r.lost:r.defenderLost,lossText=losses?num(Game.totalArmy(losses))+' 人':'旧战报未记录',name=w.players.find(p=>p.id===(attacking?r.target:r.source))?.name||r.name,loot=Object.fromEntries(Object.entries(r.loot||{}).filter(([,n])=>n>0));
  return `<article class="online-report"><div class="section-title"><h4>${esc(name)} · ${attacking?'我方出征':'我方守城'}</h4><span class="result ${won?'':'loss'}">${won?'获胜':'失利'}</span></div><p class="hint">${new Date(r.at).toLocaleString('zh-CN')} · ${attacking?'出发 '+esc(cityName(r.sourceCity)):'受袭城市 '+esc(cityName(r.targetCity))}<br>${attacking?'出征永久损失':'守方与援军永久损失'} ${lossText} · 伤兵待治 ${num(Game.totalArmy((attacking?r.wounded:r.defenderWounded)||{}))} 人 · ${attacking?'出征':'守方'}存活 ${num(Game.totalArmy((attacking?r.attacker:r.defender)||{}))} 人</p>${Object.keys(loot).length?`<p class="hint">${attacking?(w.marches.some(m=>m.id===r.id&&m.status!=='done')?'装载战利品，随队返城入库':'战利品已结算入库'):'被掠走物资'}</p>${cityCargoHTML(loot)}`:'<p class="hint">无资源缴获或掠夺。</p>'}${r.occupation?`<p class="notice">占领：民心 ${num(r.occupation.before)} → ${num(r.occupation.after)}${r.occupation.claimed?' · 城池已经易主':' · 还需继续攻打'}</p>`:''}${r.captive?`<p class="notice">${r.captive.status==='captured'?'俘获':'将领结果'}：${esc(r.captive.name||'将领')}${r.captive.reason?' · '+esc(r.captive.reason):''}</p>`:''}${r.reason?`<p class="hint">${esc(r.reason)}</p>`:''}${r.log?.length?`<details><summary>末 ${Math.min(6,r.log.length)} 条战况</summary><div class="online-report-log">${r.log.slice(-6).map(e=>`<p>第 ${e.round} 回合 · ${e.side==='a'?'攻方':'守方'}${Game.units[e.unit]?.name||Game.manual.defenses[e.unit]?.name||esc(e.unit)}${e.type==='move'?(e.command==='fallback'?'后退':'前进')+'至 '+num(e.position):'攻击'+(e.target==='gate'?'城门':Game.units[e.target]?.name||Game.manual.defenses[e.target]?.name||esc(e.target))+' · 消灭 '+num(e.killed||0)}</p>`).join('')}</div></details>`:''}</article>`;
 }).join('')}</div></details>`;
}
function onlineAllianceListModal(){
 const s=OnlineClient.status(),w=s.world;if(!w){onlineAccountModal();return;}const membership=w.membership,mine=w.alliances.find(a=>a.id===membership?.alliance),leader=membership?.role==='leader',territory=w.territories?.find(t=>t.id===mine?.id);
 showModal('联盟外交与领土',`<p class="notice">${mine?'当前联盟：'+esc(mine.name)+' · '+(leader?'盟主':'成员'):'尚未加入联盟。加入同盟后可驻兵援防。'}</p><div class="online-actions">${!membership?btn('创建联盟','onlineAllianceCreateAsk','','secondary'):btn('退出联盟','onlineAllianceLeaveAsk','','secondary')}${leader?btn('添加作战标记','onlineMarkAsk','','secondary'):''}</div>${mine?`<p class="hint">联盟 ${territory?.members||0} 名成员 · ${territory?.capitalCount||0} 座主城 · ${territory?.total||0} 座领土城池</p><div class="online-world-list">${(territory?.cities||[]).map(c=>`<article class="online-world-row"><div><strong>${esc(c.name)}</strong><p class="hint">(${c.x}, ${c.y})</p></div>${btn('地图定位','yellowCityView',c.id,'small secondary')}</article>`).join('')||'<p class="hint">尚未拥有分城或名城。</p>'}</div>`:''}<h3>联盟外交</h3><div class="online-world-list">${w.alliances.filter(a=>a.id!==mine?.id).map(a=>{const relation=mine?.relations?.[a.id],other=a.relations?.[mine?.id],enemy=[relation,other].filter(r=>r?.status==='enemy').sort((a,b)=>a.startsAt-b.startsAt)[0],label=enemy?enemy.startsAt>OnlineClient.now()?'敌对 · 备战 '+duration((enemy.startsAt-OnlineClient.now())/1000):'敌对 · 战争中':relation?.status==='friendly'||other?.status==='friendly'?'友好':'中立';return `<article class="online-world-row"><div><strong>${esc(a.name)}</strong><p class="hint">${label} · 盟主 ${esc(w.players.find(p=>p.id===a.leader)?.name||'城主')}</p></div><div class="online-row-actions">${!membership?btn('加入','onlineAllianceJoinAsk',a.id,'small secondary'):leader?btn('友好','onlineDiplomacyAsk',a.id+'~friendly','small secondary')+btn('敌对','onlineDiplomacyAsk',a.id+'~enemy','small secondary')+btn('中立','onlineDiplomacyAsk',a.id+'~neutral','small secondary'):''}</div></article>`;}).join('')||'<p class="hint">暂无其他联盟。</p>'}</div>${mine?`<h3>本盟作战标记</h3><div class="online-world-list">${(mine.marks||[]).map(m=>`<article class="online-world-row"><div><strong>${({attack:'进攻',defend:'防守',gather:'集结'})[m.kind]} · (${m.x}, ${m.y})</strong><p class="hint">${esc(m.note||'未填写说明')} · 有效期 ${duration((m.expiresAt-OnlineClient.now())/1000)}</p></div><div class="online-row-actions">${btn('地图定位','onlineMapMark',m.x+'~'+m.y,'small secondary')}${leader?btn('删除','onlineMarkRemove',m.id,'small secondary'):''}</div></article>`).join('')||'<p class="hint">暂无作战标记。标记仅本盟成员可见。</p>'}</div>`:''}<p class="hint">同盟可实际援防；友好关系禁止进攻，敌对关系在 8 小时准备后允许战争。退出前须收回援军。</p>`,btn('共享世界','onlineWorld','','secondary')+btn('关闭','close','','secondary'));manualModalContext=onlineAllianceListModal;
}
function onlinePlayerCitiesModal(id){const w=OnlineClient.status().world,p=w?.players.find(p=>p.id===id);if(!p)return;const rows=[{cityId:'capital',name:p.name+'主城',x:p.home.x,y:p.home.y,capital:true},...w.cities.filter(c=>c.owner===id)];showModal(esc(p.name)+'的城池',`<p class="hint">宣战完成准备后可出征。占领胜利降低民心，归零时分城易主；主城保留作为恢复据点。</p><div class="online-world-list">${rows.map(c=>`<article class="online-world-row"><div><strong>${esc(c.name)}</strong><p class="hint">(${c.x}, ${c.y})${c.capital?' · 保底主城':''}</p></div><div class="online-row-actions">${btn('掠夺','onlineMarchAsk','pvp~'+id+'~'+c.cityId,'small secondary')}${!c.capital?btn('占领','onlineMarchAsk','occupy~'+id+'~'+c.cityId,'small secondary'):''}${btn('援防','onlineMarchAsk','aid~'+id+'~'+c.cityId,'small secondary',!w.membership||p.alliance!==w.membership.alliance)}</div></article>`).join('')}</div>`,btn('返回世界','onlineWorld','','secondary')+btn('宣战','onlineDeclareAsk',id,'secondary'));}
function onlineWarPolicyModal(){const w=OnlineClient.status().world,p=w?.policy;if(!p)return;const now=OnlineClient.now(),protectedAt=Math.max(p.protectionUntil,p.peaceUntil);showModal('战争与保护',`<p class="notice">${protectedAt>now?'保护剩余 '+duration((protectedAt-now)/1000)+' · 至 '+new Date(protectedAt).toLocaleString('zh-CN'):'当前没有新手保护或免战'}</p><div class="online-actions">${protectedAt>now?btn('主动结束保护','onlineEndProtectionAsk','','secondary'):''}${btn('开启 12 小时免战 · 5000 金','onlinePeaceAsk','','secondary',p.peaceCooldown>now)}</div>${p.peaceCooldown>now?`<p class="hint">免战冷却剩余 ${duration((p.peaceCooldown-now)/1000)}</p>`:''}<h3>我的宣战</h3>${(p.declarations||[]).map(d=>`<article class="online-world-row"><div><strong>${esc(w.players.find(p=>p.id===d.target)?.name||'其他玩家')}</strong><p class="hint">${d.startsAt>now?'准备剩余 '+duration((d.startsAt-now)/1000):'战争剩余 '+duration((d.endsAt-now)/1000)} · 开战 ${new Date(d.startsAt).toLocaleString('zh-CN')}</p></div>${btn('查看城市','onlinePlayerCities',d.target,'small secondary')}</article>`).join('')||'<p class="hint">尚未向其他玩家宣战。</p>'}<h3>最近军政消息</h3>${(p.events||[]).slice().reverse().map(e=>`<p class="hint">${new Date(e.at).toLocaleString('zh-CN')} · ${e.type==='war-warning'?esc(w.players.find(p=>p.id===e.actor)?.name||'城主')+'已向我方宣战，8 小时后可攻击':e.type==='city-transferred'?esc(e.name)+'已易主':e.type==='trade-delivered'?'市场物资已到货：'+num(e.quantity):e.type==='trade-paid'?'市场货款已到账：'+num(e.gold):esc(e.type)}</p>`).join('')||'<p class="hint">暂无消息。</p>'}<p class="hint">新玩家保护 72 小时；主动宣战会结束新手保护。个人宣战等待 8 小时，战争持续 48 小时。已有来袭、出征或个人宣战时不能开启免战。</p>`,btn('返回世界','onlineWorld','','secondary'));manualModalContext=onlineWarPolicyModal;}
function onlineMarketModal(){const s=OnlineClient.status(),w=s.world;if(!w)return;const own=s.user.id;showModal('玩家市场',`<p class="notice">本城市场 ${S().buildings.market} 级 · 可查看和交易半径 ${S().buildings.market*8} 格。挂单冻结物资；成交先支付黄金，商队抵达后买家收货、卖家收金，允许爆仓。</p>${btn('创建出售挂单','onlineMarketCreateAsk','','secondary',S().buildings.market<1)}<div class="online-world-list">${(w.orders||[]).map(o=>`<article class="online-world-row"><div><strong>${esc(Game.resources[o.resource]?.name||o.resource)} · ${num(o.price)} 金/单位</strong><p class="hint">${esc(w.players.find(p=>p.id===o.seller)?.name||'城主')} · (${o.origin.x}, ${o.origin.y})<br>剩余 ${num(o.remaining)} / ${num(o.quantity)} · ${({open:'出售中',filled:'已售完',cancelled:'已取消'})[o.status]}</p></div>${o.status==='open'?o.seller===own?btn('取消并退回余量','onlineMarketCancelAsk',o.id,'small secondary'):btn('购买','onlineMarketBuyAsk',o.id,'small secondary',S().buildings.market<1):''}</article>`).join('')||'<p class="hint">交易范围内暂无有效挂单。</p>'}</div><h3>送货商队</h3>${onlineMarchesHTML({...w,marches:w.marches.filter(m=>m.kind==='trade')},own)}`,btn('刷新','onlineMarketRefresh','','secondary')+btn('共享世界','onlineWorld','','secondary'));manualModalContext=onlineMarketModal;}
function onlineMarketBuyAsk(id){const w=OnlineClient.status().world,o=w?.orders.find(o=>o.id===id&&o.status==='open');if(!o){toast('挂单已变化，请刷新');return;}const max=Math.min(o.remaining,Math.floor(S().res.gold/o.price));showModal('购买玩家物资',`<p class="sub">${esc(Game.resources[o.resource]?.name||o.resource)} · ${num(o.price)} 金/单位 · 可买 ${num(max)}</p><label for="online-market-quantity">购买数量</label><input id="online-market-quantity" type="number" min="1" max="${max}" value="${Math.min(max,1000)}" inputmode="numeric"><p class="hint">确认后立即冻结货款，实际商队抵达才入库。卖家取消挂单只退回未售出的余量，已成交商队继续送货。</p>`,btn('返回市场','onlineMarket','','secondary')+btn('支付并安排送货','onlineMarketBuy',id,'',max<1));}

function onlineMarchAsk(kind,target,targetCity='capital'){
 const s=OnlineClient.status(),w=s.world;if(!w)return;const targetName=kind==='hunt'?w.heroes.find(h=>h.line===target)?.name:w.players.find(p=>p.id===target)?.name;if(!targetName){toast('目标状态已变化，请刷新');return;}
 const source=activeCityMeta(),heroes=S().generals.filter(id=>cityHeroHome(id)===source.id&&!Game.generalBusy(id)&&!HeritageSystem.roleOf(S(),id)&&!w.marches.some(m=>m.source===s.user.id&&m.general===id&&m.status!=='done'));
 onlineMarchDraft={kind,target,targetCity,source:source.id,army:{},general:''};
 showModal(({aid:'派遣盟友援军',pvp:'掠夺玩家城池',occupy:'占领玩家分城',hunt:'出征抓将'})[kind],`<p class="sub">${esc(source.name)} → ${esc(targetName)} · ${esc(targetCity==='capital'?'主城':w.cities.find(c=>c.cityId===targetCity)?.name||targetCity)}</p>${kind==='occupy'?'<label><input id="online-return-after-occupy" type="checkbox"> 占领成功后返回原城（未选则驻扎新城）</label>':''}<label for="online-march-general">带兵将领</label><select id="online-march-general">${heroes.map(id=>`<option value="${esc(id)}">${esc(Game.general(id).name)} · Lv.${Game.general(id).level}</option>`).join('')}</select><div class="city-transfer-inputs">${Object.entries(Game.units).filter(([id])=>S().army[id]>0).map(([id,u])=>`<label>${u.name}<small>驻城 ${num(S().army[id])}</small><input type="number" data-online-army="${id}" min="0" max="${S().army[id]}" value="0" inputmode="numeric"></label>`).join('')||'<p class="notice">本城暂无可派遣兵力。</p>'}</div><p class="notice">${kind==='aid'?'援军抵达后留驻盟友城市，参与防守，主动召回后返城。':kind==='hunt'?'抓将前需购买对应画像并解锁客栈线索。先到且获胜的玩家才可能获得将领，名额仍需满足。':kind==='occupy'?'占领胜利降低城内民心，归零后分城易主。易主成功按上方选择驻扎新城或返城；尚未易主时战后返城。':'服务器结算双方与援军伤亡，胜利按幸存负重掠走部分资源和黄金，战后返城。'}</p><p class="hint">行军耗粮、人数上限与目标状态由服务器再次验证，混编按最慢兵种行军。</p>`,btn('返回共享世界','onlineWorld','','secondary')+btn('预览出征','onlineMarchReview','', '',!heroes.length));
}
function onlineMarchReview(){
 if(!onlineMarchDraft)return;const d=onlineMarchDraft;if(d.source!==activeCityMeta().id){toast('出发城已改变，请重新选兵');return;}d.general=document.getElementById('online-march-general')?.value;d.returnAfterOccupy=document.getElementById('online-return-after-occupy')?.checked===true;d.army=Object.fromEntries(Object.keys(Game.units).map(id=>[id,0]));document.querySelectorAll('[data-online-army]').forEach(input=>{const id=input.dataset.onlineArmy;d.army[id]=Math.max(0,Math.min(S().army[id],Math.floor(Number(input.value)||0)));input.value=d.army[id];});if(!d.general||!Game.totalArmy(d.army)){toast('请选择将领与至少 1 名士兵');return;}
 const s=OnlineClient.status(),destination=d.kind==='hunt'?Game.getNode(s.world.heroes.find(h=>h.line===d.target)?.node):d.targetCity!=='capital'?s.world.cities.find(c=>c.cityId===d.targetCity):s.world.players.find(p=>p.id===d.target)?.home;if(!destination){toast('目标已变化');return;}const origin=activeCityMeta().capital?(s.world.players.find(p=>p.id===s.user.id)?.home||activeCityMeta()):activeCityMeta(),speed=Math.min(...Object.entries(d.army).filter(([,n])=>n>0).map(([id])=>Game.unitStats(id).speed)),pureCavalry=Object.entries(d.army).every(([id,n])=>!n||['cavalry','heavy','scout'].includes(id)),factor=pureCavalry?Game.generalGrowth.profile(S(),d.general).marchFactor:1,seconds=Math.max(1,Math.ceil(Math.hypot(origin.x-destination.x,origin.y-destination.y)*1000/Math.max(1,speed)/factor)),food=Math.ceil(Game.totalArmy(d.army)*1.2+Game.upkeep(d.army)*seconds*2/3600);
 showModal('确认共享世界出征',`<p class="sub">将领：${esc(Game.general(d.general).name)} · ${num(Game.totalArmy(d.army))} 人</p><p class="hint">${Object.entries(d.army).filter(([,n])=>n>0).map(([id,n])=>Game.units[id].name+' '+num(n)).join(' · ')}<br>预计去程 ${duration(seconds)} · 行军粮 ${num(food)} · 最终以服务器确认为准</p><p class="notice">确认后提交出征指令；士兵与将领离城。目标归属变化或前置不足时，服务器会拒绝派遣并保留兵力。</p>`,btn('返回配兵','onlineMarchAsk',d.kind+'~'+d.target+'~'+d.targetCity,'secondary')+btn('确认出征','onlineMarchSend','', '',S().res.food<food));
}
async function onlineAction(run,success,after){try{await run();if(success)toast(success);if(after)after();}catch(error){toast(error.message||'云端连接失败');if(OnlineClient.status().privateConflict)onlinePrivateConflictModal();}finally{refreshOnlineStatus();}}
document.addEventListener('click',event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id||'';if(!a.startsWith('online'))return;
 if(a==='onlineAccount')onlineAccountModal();
 if(a==='onlineConfig')onlineConfigModal();
 if(a==='onlineConfigSave')void onlineAction(async()=>{const error=await OnlineClient.configure({url:document.getElementById('online-url').value,publishableKey:document.getElementById('online-key').value,realm:document.getElementById('online-realm').value});if(error)throw new Error(error);},'连接设置已保存',onlineAccountModal);
 if(a==='onlineLogin'||a==='onlineRegister'){const form=document.getElementById('online-auth-form');if(!form.reportValidity())return;const email=document.getElementById('online-email').value.trim(),password=document.getElementById('online-password').value;el.disabled=true;void onlineAction(async()=>{const r=await OnlineClient.auth(a==='onlineLogin'?'login':'register',email,password);toast(r.confirmation?'请查收验证邮件，再回来登录':'账号已登录');},'',onlineAccountModal).finally(()=>el.disabled=false);}
 if(a==='onlineLogout')void onlineAction(()=>OnlineClient.logout(),'账号已退出',onlineAccountModal);
 if(a==='onlineSharedStartAsk')onlineSharedStartAsk();
 if(a==='onlineCreateShared'||a==='onlineResume')void onlineAction(()=>OnlineClient.openShared(a==='onlineCreateShared'),'共享世界进度已读取',()=>{modal.close();page='city';render();onlineWorldModal();});
 if(a==='onlineLeaveAsk')showModal('返回原单机进度','<p class="hint">共享世界进度保留在服务器。返回后恢复进入前的单机城池，云端队伍继续按服务器时间行军。</p>',btn('继续共享世界','onlineWorld','','secondary')+btn('返回单机','onlineLeave'));
 if(a==='onlineLeave')void onlineAction(()=>OnlineClient.leaveShared(),'已返回原单机进度',()=>{modal.close();resyncSaveUI();});
 if(a==='onlineWorld')onlineWorldModal();
 if(a==='onlineRefresh')void onlineAction(()=>OnlineClient.refresh(),'云端进度已刷新',onlineWorldModal);
 if(a==='onlineRetry')void onlineAction(()=>OnlineClient.retry(),'上条指令已确认',onlineAccountModal);
 if(a==='onlinePrivateSave')void onlineAction(()=>OnlineClient.savePrivate(),'私人云档已保存',onlineAccountModal);
 if(a==='onlinePrivateRead')void onlineAction(()=>OnlineClient.readPrivate(),'',onlinePrivateReviewModal);
 if(a==='onlinePrivateImport'&&onlinePrivateReviewed){downloadSaveText(JSON.stringify(S(),null,2),'恢复云档前备份');const error=OnlineClient.importPrivate();if(actResult(error,'私人云档已恢复，原进度已导出')){onlinePrivateReviewed=false;modal.close();resyncSaveUI();}}
 if(a==='onlinePrivateConflict')onlinePrivateConflictModal();
 if(a==='onlineConflictKeep'){OnlineClient.clearConflict();onlineAccountModal();}
 if(a==='onlinePlayerCities')onlinePlayerCitiesModal(id);
 if(a==='onlineWarPolicy')onlineWarPolicyModal();
 if(a==='onlineDeclareAsk'){const target=OnlineClient.status().world?.players.find(p=>p.id===id);if(target)showModal('向 '+esc(target.name)+' 宣战','<p class="notice">宣战会结束我方新手保护。服务器确认后开始 8 小时准备期，随后可攻击 48 小时。目标受保护、同盟或友好联盟时无法宣战。</p>',btn('返回世界','onlineWorld','','secondary')+btn('确认宣战','onlineDeclare',id));}
 if(a==='onlineDeclare')actResult(OnlineClient.enqueue('shared.declareWar',[{targetId:id}]));
 if(a==='onlineEndProtectionAsk')showModal('结束保护','<p class="notice">确认后立即结束新手保护和当前免战，其他符合宣战条件的玩家可攻击。结束后不会恢复剩余保护时间。</p>',btn('保留保护','onlineWarPolicy','','secondary')+btn('确认结束保护','onlineEndProtection'));
 if(a==='onlineEndProtection')actResult(OnlineClient.enqueue('shared.endProtection',[{}]));
 if(a==='onlinePeaceAsk')showModal('开启免战','<p class="notice">花费 5000 黄金，获得 12 小时免战；48 小时后才能再次开启。已有来袭、出征或个人宣战时无法开启。</p>',btn('返回','onlineWarPolicy','','secondary')+btn('支付并开启免战','onlinePeace'));
 if(a==='onlinePeace')actResult(OnlineClient.enqueue('shared.peace',[{}]));
 if(a==='onlineDiplomacyAsk'){const [target,status]=id.split('~'),name=OnlineClient.status().world?.alliances.find(a=>a.id===target)?.name;showModal('调整联盟外交',`<p class="notice">将对 ${esc(name||'联盟')} 的关系设为 ${({friendly:'友好',enemy:'敌对',neutral:'中立'})[status]}。${status==='enemy'?'8 小时准备后双方可战争。':status==='friendly'?'友好禁止双方攻击；对方仍设敌对时，战争关系优先。':'仅撤销本盟设置，对方仍设敌对时战争关系仍生效。'}</p>`,btn('返回联盟','onlineAllianceList','','secondary')+btn('确认外交调整','onlineDiplomacy',id));}
 if(a==='onlineDiplomacy'){const [target,status]=id.split('~');actResult(OnlineClient.enqueue('shared.setDiplomacy',[{id:target,status}]));}
 if(a==='onlineMarkAsk')showModal('添加本盟作战标记','<label for="online-mark-kind">行动</label><select id="online-mark-kind"><option value="attack">进攻</option><option value="defend">防守</option><option value="gather">集结</option></select><div class="city-transfer-inputs"><label>横坐标 X<input id="online-mark-x" type="number" min="0" max="63" value="32" inputmode="numeric"></label><label>纵坐标 Y<input id="online-mark-y" type="number" min="0" max="63" value="32" inputmode="numeric"></label></div><label for="online-mark-note">说明 · 最多 80 字</label><input id="online-mark-note" maxlength="80"><p class="hint">标记仅本盟成员可见，72 小时自动过期，最多同时 20 个。</p>',btn('返回联盟','onlineAllianceList','','secondary')+btn('添加标记','onlineMarkSend'));
 if(a==='onlineMarkSend')actResult(OnlineClient.enqueue('shared.markOperation',[{x:Number(document.getElementById('online-mark-x').value),y:Number(document.getElementById('online-mark-y').value),kind:document.getElementById('online-mark-kind').value,note:document.getElementById('online-mark-note').value.trim()}]));
 if(a==='onlineMapMark'){const [x,y]=id.split('~').map(Number);modal.close();page='world';centerWorld(x,y,false);}
 if(a==='onlineMarkRemove')actResult(OnlineClient.enqueue('shared.removeOperation',[{id}]));
 if(a==='onlineMarket')onlineMarketModal();
 if(a==='onlineMarketRefresh')void onlineAction(()=>OnlineClient.refresh(),'市场已刷新',onlineMarketModal);
 if(a==='onlineMarketCreateAsk')showModal('出售物资 · 冻结库存',`<label for="online-market-resource">出售资源</label><select id="online-market-resource">${['food','wood','stone','iron'].map(r=>`<option value="${r}">${esc(Game.resources[r].name)} · 库存 ${num(S().res[r])}</option>`).join('')}</select><div class="city-transfer-inputs"><label>出售数量<input id="online-market-quantity" type="number" min="1" max="1000000000" value="1000" inputmode="numeric"></label><label>每单位黄金<input id="online-market-price" type="number" min="1" max="10000" value="1" inputmode="numeric"></label></div><p class="notice">发布后立即冻结这批物资，不能重复用于建设或出征。可部分成交，取消后退回未售余量；已经成交的商队继续送货。</p>`,btn('返回市场','onlineMarket','','secondary')+btn('冻结物资并发布','onlineMarketCreate'));
 if(a==='onlineMarketCreate'){const resource=document.getElementById('online-market-resource').value,quantity=Math.max(1,Math.min(1000000000,Math.floor(S().res[resource]),Math.floor(Number(document.getElementById('online-market-quantity').value)||0))),price=Math.max(1,Math.min(10000,Math.floor(Number(document.getElementById('online-market-price').value)||0)));actResult(OnlineClient.enqueue('shared.marketCreate',[{resource,quantity,price}]));}
 if(a==='onlineMarketBuyAsk')onlineMarketBuyAsk(id);
 if(a==='onlineMarketBuy'){const order=OnlineClient.status().world?.orders.find(o=>o.id===id);if(order){const quantity=Math.max(1,Math.min(order.remaining,Math.floor(S().res.gold/order.price),Math.floor(Number(document.getElementById('online-market-quantity').value)||0)));actResult(OnlineClient.enqueue('shared.marketBuy',[{id,targetId:order.seller,quantity}]));}}
 if(a==='onlineMarketCancelAsk'){const order=OnlineClient.status().world?.orders.find(o=>o.id===id);if(order)showModal('取消市场挂单',`<p class="notice">取消后退回未售出的 ${num(order.remaining)} 单位物资；已成交的商队与货款不受影响。</p>`,btn('保留挂单','onlineMarket','','secondary')+btn('取消并退款','onlineMarketCancel',id));}
 if(a==='onlineMarketCancel')actResult(OnlineClient.enqueue('shared.marketCancel',[{id}]));
 if(a==='onlineAllianceList')onlineAllianceListModal();
 if(a==='onlineAllianceCreateAsk')showModal('创建联盟','<label for="online-alliance-name">联盟名称 · 2–20 字</label><input id="online-alliance-name" minlength="2" maxlength="20">',btn('返回','onlineAllianceList','','secondary')+btn('确认创建','onlineAllianceCreate'));
 if(a==='onlineAllianceCreate')actResult(OnlineClient.enqueue('shared.createAlliance',[{name:document.getElementById('online-alliance-name').value.trim()}]));
 if(a==='onlineAllianceJoinAsk')showModal('加入联盟','<p class="hint">确认后成为联盟成员，可向盟友派出援军。</p>',btn('返回','onlineAllianceList','','secondary')+btn('确认加入','onlineAllianceJoin',id));
 if(a==='onlineAllianceJoin')actResult(OnlineClient.enqueue('shared.joinAlliance',[{id}]));
 if(a==='onlineAllianceLeaveAsk')showModal('退出联盟','<p class="hint">退出前须收回所有相关援军，盟主仍有其他成员时不可退出。</p>',btn('保留联盟','onlineAllianceList','','secondary')+btn('确认退出','onlineAllianceLeave'));
 if(a==='onlineAllianceLeave')actResult(OnlineClient.enqueue('shared.leaveAlliance',[{}]));
 if(a==='onlineMarchAsk'){const [kind,target,city]=id.split('~');onlineMarchAsk(kind,target,city||'capital');}
 if(a==='onlineMarchReview')onlineMarchReview();
 if(a==='onlineMarchSend'&&onlineMarchDraft){const d=onlineMarchDraft;if(d.source!==activeCityMeta().id){toast('出发城已变化');return;}actResult(OnlineClient.enqueue(d.kind==='hunt'?'shared.hunt':d.kind==='aid'?'shared.aid':'shared.attackPlayer',[{general:d.general,army:d.army,...(d.kind==='hunt'?{line:d.target}:{targetId:d.target,targetCity:d.targetCity,mode:d.kind==='occupy'?'occupy':'raid',returnAfterOccupy:d.returnAfterOccupy})}],d.source));}
 if(a==='onlineRecallAidAsk')showModal('召回盟友驻军','<p class="hint">援军离开盟友城市并返城，抵达后再结算归队。</p>',btn('保留驻扎','onlineWorld','','secondary')+btn('确认召回','onlineRecallAid',id));
 if(a==='onlineRecallAid')actResult(OnlineClient.enqueue('shared.recallAid',[{id}]));
 if(a==='onlineSettle')actResult(OnlineClient.enqueue('shared.settle',[{}]));
});
document.addEventListener('submit',event=>{if(event.target.id==='online-auth-form'){event.preventDefault();}});
document.addEventListener('online-state',refreshOnlineStatus);
document.addEventListener('online-snapshot',()=>{if(typeof render==='function'){previous=signature();render();if(modal.open&&manualModalContext){const scroll=modal.scrollTop;manualModalContext();modal.scrollTop=scroll;}}});
document.addEventListener('online-error',event=>toast(event.detail.message+(event.detail.uncertain?'；可重试同一条指令或读取服务器结果':'')));
document.addEventListener('online-command',event=>{const type=event.detail.type;if(type.startsWith('shared.market'))onlineMarketModal();else if(['shared.setDiplomacy','shared.markOperation','shared.removeOperation'].includes(type))onlineAllianceListModal();else if(['shared.declareWar','shared.peace','shared.endProtection'].includes(type))onlineWarPolicyModal();else if(type.startsWith('shared.'))onlineWorldModal();else if(['switchCity','enterOwnedCity'].includes(type)){modal.close();page='city';cityArea='inner';render();}else if(['sendTransport','redeployArmy'].includes(type)){modal.close();page='army';render();}else if(type==='foundCity')citySwitchListModal();else if(type==='useItem'&&['jewelBox','equipmentBox'].includes(Game.manual.shop.find(i=>i.id===event.detail.args?.[0])?.effect)&&S().onboarding.lastOpen){const r=S().onboarding.lastOpen,message=r.kind==='jewel'?Game.progression.jewels[r.id].name+' ×'+r.count:HeroSystem.itemName(S().equipment.find(e=>e.id===r.id));showModal('开盒所得',`<p class="notice">已获得：${esc(message)}</p>`,btn('返回背包','manualInventory'));}else if(type==='useItem'&&modal.open&&modalBody.querySelector('[data-action="manualUse"]')?.dataset.id===event.detail.args?.[0])manualInventoryModal();else if(!manualModalContext&&modal.open)modal.close();toast('云端操作已确认');});
