const {test}=require('node:test'),assert=require('node:assert/strict');const {ready,begin,plain,cloneActiveSave}=require('./helpers/battlefield.cjs');
function fight(e,id='m1'){assert.equal(e.Game.enterBattlefieldNode(id),null);const b=e.Game.state.battlefields.run.battle;assert.ok(b,'formal battlefield snapshot missing');return b;}
function finish(e){for(let i=0;i<30&&!e.Game.state.battlefields.run.battle.finished;i++)e.Game.battlefieldRound();return e.Game.state.battlefields.run.battle;}
test('real rounds settle rental survivors and recover sixty percent without city loot or wounded',()=>{const e=ready(),G=e.Game;begin(e,{militia:800});const before=plain({army:G.state.army,pop:G.state.population,care:G.state.warCare,res:G.state.res,stats:G.state.stats,xp:G.state.generalXp.lin});const b=fight(e);finish(e);assert.equal(b.result.won,true);const dead=800-b.result.back.militia;assert.equal(b.result.recovered.militia,Math.floor(dead*.6));assert.equal(G.state.battlefields.run.pool,2200+Math.floor(dead*.6));assert.equal(G.state.battlefields.run.wounded.militia,dead-Math.floor(dead*.6));assert.deepEqual(plain({army:G.state.army,pop:G.state.population,care:G.state.warCare,res:G.state.res,stats:G.state.stats,xp:G.state.generalXp.lin}),before);const stable=JSON.stringify(G.state);G.battlefieldRound();assert.equal(JSON.stringify(G.state),stable);assert.equal(G.validSave(G.state),true);});
test('thirty idle rounds fail, preserve finite rental losses and permit reinforced retry',()=>{const e=ready(),G=e.Game;begin(e,{militia:1});const b=fight(e);G.battlefieldOrder('militia','hold');for(let i=0;i<30;i++){for(const row of b.enemy)b.enemyOrders[row.id].command='hold';G.battlefieldRound();}assert.equal(b.round,30);assert.equal(b.result.won,false);assert.equal(G.state.battlefields.run.completed.length,0);assert.equal(G.reinforceBattlefield({militia:799}),null);assert.equal(G.enterBattlefieldNode('m1'),null);assert.equal(G.state.battlefields.run.battle.player[0].initial,800);});
test('mounted snapshots are frozen and the run general may equip only between battles',()=>{const e=ready(),G=e.Game,H=e.evaluate('HeroSystem'),horse=H.addEquipment(G.state,'mount',1);begin(e);assert.equal(typeof G.battlefieldCanEquip,'function');assert.equal(G.battlefieldCanEquip('lin'),true);assert.equal(H.equip(horse.id,'lin'),null);const b=fight(e);assert.equal(b.mountProfile.speed,6);assert.equal(G.battlefieldCanEquip('lin'),false);assert.ok(H.unequip(horse.id));assert.ok(G.startTacticalLesson('advance'));assert.ok(G.startCityDefense(true,'su',{}));const bad=cloneActiveSave(G.state);bad.battlefields.run.battle.player[0].hp++;assert.equal(G.validSave(bad),false);const id=cloneActiveSave(G.state);id.battlefields.run.battle.runId='yellow:999';assert.equal(G.validSave(id),false);G.save();G.init();assert.equal(G.state.battlefields.run.battle.mountProfile.speed,6);});
test('optional effects apply once and completed branches cannot grant duplicate rentals',()=>{const e=ready(),G=e.Game;begin(e,{militia:800});fight(e,'s1');finish(e);assert.equal(G.state.battlefields.run.pool+Object.values(G.state.battlefields.run.army).reduce((a,b)=>a+b,0)+Object.values(G.state.battlefields.run.wounded).reduce((a,b)=>a+b,0),3500);assert.ok(G.enterBattlefieldNode('s1'));assert.equal(G.validSave(G.state),true);});

test('forged frozen source troop stats and unknown technology are rejected',()=>{const e=ready(),G=e.Game;begin(e);const bad=cloneActiveSave(G.state);bad.battlefields.run.unitSnapshot.militia.atk=9999;assert.equal(G.validSave(bad),false);const tech=cloneActiveSave(G.state);tech.battlefields.run.techSnapshot.combat=99;assert.equal(G.validSave(tech),false);});
test('switching cities preserves campaign source tech while paused combat permits a different city defender',()=>{
 const e=ready(),G=e.Game,s=G.state;s.honors.noble=2;for(const k in s.res)s.res[k]=200000;
 let tile;for(let x=24;x<32&&!tile;x++)for(let y=24;y<32&&!tile;y++){const n=G.getWorldTile(x,y);if(n.wild&&n.type==='plain')tile=n;}
 s.conquered[tile.id]=true;s.landClaims[tile.id]={at:e.now(),level:tile.level};s.realm.wildOwners[tile.id]='capital';const q=G.foundCityQuote(tile.id,'边城');assert.equal(G.foundCity(tile.id,'边城',q.key),null);
 begin(e);s.tech.combat=5;const b=fight(e);assert.equal(b.player[0].stats.atk,50);const frozen=plain(b);s.warCare.defense.autoResolve=false;assert.equal(G.pauseBattlefieldBattle(),null);assert.equal(G.startCityDefense(true,'su',{}),null);assert.equal(typeof G.battlefieldRound(),'string');assert.equal(G.endDefenseDrill(),null);
 const id=G.cityList()[1].id;assert.equal(G.switchCity(id),null);assert.equal(G.state.battlefields.run.sourceCity,'capital');assert.deepEqual(plain(G.state.battlefields.run.battle),frozen);assert.equal(G.validSave(G.state),true);G.save();G.init();assert.equal(G.state.battlefields.run.sourceCity,'capital');assert.equal(G.battlefieldRound().round,1);
});
test('a rental campaign reserves a zero-loyalty recruited general between nodes, in combat and across offline reload',()=>{for(const inCombat of [false,true]){const e=ready(),G=e.Game,s=G.state;s.generals.push('yan');s.generalLevels.yan=5;s.generalXp.yan=0;s.realm.heroLocations.yan='capital';e.evaluate('HeroSystem.init(Game.state);GovernanceSystem.init(Game.state)');s.heroLoyalty.yan=5;s.res.gold=0;G.setTax(0);const q=G.battlefieldQuote('yan',{militia:800});assert.equal(q.reason,'');assert.equal(G.startBattlefield('yan',{militia:800},q.key),null);if(inCombat)assert.equal(G.enterBattlefieldNode('m1'),null);e.advance(3600000);assert.equal(G.state.generals.includes('yan'),true);assert.ok(G.state.heroService.pending.includes('yan'));assert.ok(G.state.heroService.owed.yan>0);assert.equal(G.validSave(G.state),true);G.save();G.init();assert.notEqual(G.saveSessionInfo().mode,'recovery');assert.equal(G.state.battlefields.run.general,'yan');e.offline(3600000);assert.equal(G.state.generals.includes('yan'),true);assert.equal(G.validSave(G.state),true);const id=G.state.battlefields.run.id;assert.equal(G.abandonBattlefield(id),null);e.advance(1);assert.equal(G.state.generals.includes('yan'),false);assert.equal(G.validSave(G.state),true);}});
