const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city}=require('./helpers/game.cjs');const copy=x=>JSON.parse(JSON.stringify(x));
// Prepared armies exercise capture and save contracts; they do not measure natural pacing.
function prepared(){const e=loadGame(723),g=e.Game;city(g,{hall:4,drill:1});g.state.honors.noble=2;g.state.army.archer=3000;for(const id of Object.keys(g.resources))g.state.res[id]=1000000;e.evaluate('Math.random=()=>.999999');return e;}
function fight(e,id,returnAfter){const g=e.Game;assert.equal(g.setTactic('archer','advance',''),null);assert.equal(g.dispatch(id,'lin',{archer:1000},'occupy',returnAfter),null);e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.startBattle(),null);assert.ok(g.state.battle.enemy.some(r=>r.hp>0));for(let i=0;i<30&&!g.state.battle.finished;i++)g.battleRound();assert.equal(g.state.battle.finished,true);const result=copy(g.state.battle.result);assert.equal(result.won,true);assert.equal(g.validSave(g.state),true);return result;}
function wait(e,id){const g=e.Game;const until=Math.max(g.state.expedition?.end||e.now(),g.state.cooldowns[id]||e.now());e.advance(Math.ceil(until-e.now())+1);}
function capture(e,id,returnAfter=false){let result;for(let i=0;i<3;i++){result=fight(e,id,i<2?true:returnAfter);assert.equal(result.moraleAfter,[65,30,-5][i]);assert.equal(result.claimed,i===2);if(i<2)wait(e,id);}return result;}
const cumulativeXp=(g,id)=>40*g.state.generalLevels[id]*(g.state.generalLevels[id]-1)+g.state.generalXp[id];

test('three real Yellow Turban occupation victories create an independent city and station the commander and survivors there',()=>{const e=prepared(),g=e.Game,r=capture(e,'yellow_qingshi'),id='city_yellow_qingshi',capital=g.citySummary('capital'),newCity=g.citySummary(id);assert.equal(r.stationed,true);assert.equal(r.returnAfterOccupy,false);assert.equal(g.state.expedition,null);assert.equal(g.heroCity('lin'),id);assert.equal(newCity.buildings.hall,1);assert.equal(newCity.governor,null);assert.equal(newCity.army.archer,r.back.archer);const wounded=g.getCityState('capital').warCare.wounded.archer;assert.equal(wounded,g.state.reports.reduce((sum,report)=>sum+report.wounded.archer,0));assert.ok(wounded>0);assert.equal(capital.army.archer+r.back.archer+wounded,3000-g.state.reports.reduce((sum,report)=>sum+report.lost.archer,0));assert.equal(g.getCityState(id).warCare.wounded.archer,0);assert.equal(g.getCityState(id).plots.every(p=>p.type===null&&p.level===0),true);assert.deepEqual(copy(newCity.res),{food:0,wood:0,stone:0,iron:0,gold:0});assert.equal(g.switchCity(id),null);g.state.res.wood=777;g.save();assert.equal(g.switchCity('capital'),null);assert.equal(g.state.res.wood,capital.res.wood);assert.equal(g.citySummary(id).res.wood,777);assert.equal(g.validSave(g.state),true);});

test('a real ordinary county capture honors the return checkbox and leaves its new city empty while the army returns to the source',()=>{const e=prepared(),g=e.Game;g.state.epic.legacyAccess=true;g.state.raided.mine=true;assert.equal(g.landmarkVisible('fort'),true);const r=capture(e,'fort',true),id='city_fort',s=g.citySummary(id);assert.equal(r.claimed,true);assert.equal(r.stationed,false);assert.equal(r.returnAfterOccupy,true);assert.equal(g.state.expedition.phase,'return');assert.equal(g.state.expedition.sourceCity,'capital');assert.equal(g.heroCity('lin'),'capital');assert.equal(Object.values(s.army).reduce((a,b)=>a+b,0),0);const army=g.state.army.archer,wounded=g.state.warCare.wounded.archer;assert.ok(wounded>0);assert.equal(r.woundedInHospital,true);wait(e,'fort');assert.equal(g.state.army.archer,army+r.back.archer);assert.equal(g.state.warCare.wounded.archer,wounded);assert.equal(g.state.expedition,null);assert.equal(g.citySummary(id).buildings.hall,1);e.offline(1);assert.equal(g.validSave(g.state),true);assert.equal(g.cityList().length,2);assert.equal(g.heroCity('lin'),'capital');});

test('rank city limits block occupation without charging supplies or removing troops; raising rank enables the same real target',()=>{const e=prepared(),g=e.Game;g.state.honors.noble=0;const army=copy(g.state.army),food=g.state.res.food;assert.match(g.attackBlocked('yellow_qingshi','occupy'),/城池名额已满/);assert.match(g.dispatch('yellow_qingshi','lin',{archer:1000},'occupy'),/城池名额已满/);assert.deepEqual(copy(g.state.army),army);assert.equal(g.state.res.food,food);assert.equal(g.state.expedition,null);g.state.honors.noble=1;assert.equal(g.attackBlocked('yellow_qingshi','occupy'),null);capture(e,'yellow_qingshi',true);assert.equal(g.cityList().length,2);assert.match(g.attackBlocked('yellow_baisha','occupy'),/城池名额已满/);assert.equal(g.attackBlocked('yellow_baisha','raid'),null);});

test('building completions in two cities reward their own governors once, even while the other city is selected',()=>{const e=prepared(),g=e.Game;capture(e,'yellow_qingshi');assert.equal(g.switchCity('city_yellow_qingshi'),null);assert.equal(g.setGovernor('lin'),null);for(const id of Object.keys(g.resources))g.state.res[id]=1000000;const linBefore=cumulativeXp(g,'lin'),suBefore=cumulativeXp(g,'su');assert.equal(g.queueBuilding(g.state.cityLayout.indexOf(null),'house'),null);const secondEnd=g.state.buildQueue[0].end;assert.equal(g.switchCity('capital'),null);assert.equal(g.queueBuilding(g.state.cityLayout.indexOf(null),'house'),null);const firstEnd=g.state.buildQueue[0].end;e.advance(Math.ceil(Math.max(firstEnd,secondEnd)-e.now())+1);assert.equal(cumulativeXp(g,'lin'),linBefore+10);assert.equal(cumulativeXp(g,'su'),suBefore+10);assert.equal(g.citySummary('capital').buildings.house,1);assert.equal(g.citySummary('city_yellow_qingshi').buildings.house,1);e.offline(1);assert.equal(cumulativeXp(g,'lin'),linBefore+10);assert.equal(cumulativeXp(g,'su'),suBefore+10);assert.equal(g.validSave(g.state),true);});

test('global high-tier gifts and progression remain valid and cannot be reclaimed after switching to a new hall-one city or reloading',()=>{const e=prepared(),g=e.Game;city(g,{hall:10});assert.equal(g.onboarding.claimAvailable(),null);assert.deepEqual(copy(g.state.onboarding.claims),[1,2,3,4,5,6,7,8,9,10]);capture(e,'yellow_qingshi');const claims=copy(g.state.onboarding.claims),inventory=copy(g.state.inventory),global=copy({epic:g.state.epic,warOrders:g.state.warOrders,missionClaims:g.state.missionClaims});assert.equal(g.switchCity('city_yellow_qingshi'),null);assert.equal(g.state.buildings.hall,1);assert.equal(g.validSave(g.state),true);assert.match(g.onboarding.claimAvailable(),/暂无|没有可领取/);assert.deepEqual(copy(g.state.onboarding.claims),claims);assert.deepEqual(copy(g.state.inventory),inventory);e.offline(1);assert.equal(g.validSave(g.state),true);assert.equal(g.currentCityId(),'city_yellow_qingshi');assert.equal(g.state.buildings.hall,1);assert.deepEqual(copy(g.state.onboarding.claims),claims);assert.deepEqual(copy({epic:g.state.epic,warOrders:g.state.warOrders,missionClaims:g.state.missionClaims}),global);});
