const {test}=require('node:test'),assert=require('node:assert/strict');
const {prepared,recruitWild,recruitGarrison}=require('./helpers/hero-fixtures.cjs');
const {cloneActiveSave}=require('./helpers/game.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
for(const [line,level,lead]of [['huaman',60,240],['baosanniang',60,250],['zhurong',65,270],['tadun',65,320],['menghuo',65,300]])test('recruit '+line+' ready for battle without inflating leadership',()=>{const e=prepared(),id=recruitWild(e,line),g=e.Game;assert.equal(g.general(id).level,level);assert.equal(g.general(id).lead,lead);assert.equal(g.validSave(cloneActiveSave(g.state)),true);});
for(const [node,level,lead]of [['named_jiangling',70,450],['named_xiaopei',70,400],['named_wancheng',65,350],['named_beihai',65,420],['named_xiapi',70,490]])test('manual city recruitment '+node+' uses starting tier',()=>{const e=prepared(),id=recruitGarrison(e,node),g=e.Game;assert.equal(g.general(id).level,level);assert.equal(g.general(id).lead,lead);assert.equal(g.validSave(cloneActiveSave(g.state)),true);});
test('migration keeps earned leadership, points and xp and cannot apply twice',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game,old=cloneActiveSave(g.state);delete old.famousStarts;old.generalLevels[id]=12;old.generalXp[id]=77;old.heroPoints[id].atk=9;g.importSave(old);assert.equal(g.general(id).level,60);assert.equal(g.general(id).lead,300);assert.equal(g.state.generalXp[id],77);assert.equal(g.state.heroPoints[id].atk,9);const raw=JSON.stringify(g.state);g.importSave(cloneActiveSave(g.state));assert.equal(g.general(id).lead,300);assert.equal(g.general(id).level,60);const before=JSON.stringify(g.state);g.general(id);g.getNode('field');e.evaluate('HeroSystem.init(Game.state)');assert.equal(JSON.stringify(g.state),before);assert.ok(raw);});
test('migration preserves higher level and its existing leadership growth',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game,old=cloneActiveSave(g.state);delete old.famousStarts;old.generalLevels[id]=100;g.importSave(old);assert.equal(g.general(id).level,100);assert.equal(g.general(id).lead,1180);e.evaluate(`HeroSystem.addXp(Game.state,'${id}',8000)`);assert.equal(g.general(id).level,101);assert.equal(g.general(id).lead,1190);});
test('same-name ordinary inn recruit never receives the famous tier',()=>{const e=prepared(),g=e.Game;assert.equal(g.refreshInn(),null);const c=g.state.innCandidates[0];c.name='关羽';assert.equal(g.recruit(c.id),null);assert.equal(g.general(c.id).level,c.level);assert.equal(g.state.famousStarts[c.id],undefined);});
test('old frozen expedition survives migration while returning general gains the tier',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game;g.state.army.archer=800;g.state.res.food=1e6;assert.equal(g.dispatch('field',id,{archer:800},'raid'),null);const old=cloneActiveSave(g.state);delete old.famousStarts;old.generalLevels[id]=12;Object.assign(old.expedition.generalSnapshot,{level:12,atk:131,def:111,lead:300});const frozen=copy(old.expedition.generalSnapshot);g.importSave(old);assert.equal(g.general(id).level,60);assert.deepEqual(copy(g.state.expedition.generalSnapshot),frozen);e.advance(g.state.expedition.end-e.now()+1);assert.equal(g.startBattle(),null);assert.deepEqual(copy(g.state.battle.generalSnapshot),frozen);assert.equal(g.validSave(cloneActiveSave(g.state)),true);});
test('starting ledger rejects malformed credit, extra fields and impostors',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game;for(const patch of [{level:61,leadGrowth:0},{level:60,leadGrowth:-10},{level:60,leadGrowth:1},{level:60,leadGrowth:550},{level:60,leadGrowth:0,extra:true}]){const d=cloneActiveSave(g.state);d.famousStarts[id]=patch;assert.equal(g.validSave(d),false);}const d=cloneActiveSave(g.state);d.famousStarts.lin={level:60,leadGrowth:0};assert.equal(g.validSave(d),false);});
test('departure removes the ledger and keeps the save legal',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game;assert.ok(g.state.famousStarts[id]);assert.equal(e.evaluate(`GovernanceSystem.removeHero(Game.state,'${id}')`),true);assert.equal(g.state.famousStarts[id],undefined);assert.equal(g.validSave(cloneActiveSave(g.state)),true);});

test('winning the final siege automatically recruits the seventy-level city general',()=>{const r=require('./balance/named-siege.cjs').run({id:'named_xiaopei',maxAssaults:10});assert.equal(r.captured,true);assert.equal(r.recruited,true);assert.equal(r.level,70);assert.equal(r.validSave,true);});
test('wild level previews use the joining tier and do not mutate the save',()=>{const e=prepared(),g=e.Game;const fs=require('node:fs'),path=require('node:path');e.evaluate("var previewHTML='',manualModalContext;function S(){return Game.state;}function num(n){return String(n);}function esc(n){return String(n);}function clock(){return '';}function btn(){return '';}function generalPortrait(){return '';}function showModal(title,html){previewHTML=html;}");e.evaluate(fs.readFileSync(path.join(__dirname,'../wild-general-ui.js'),'utf8'));const before=JSON.stringify(g.state);e.evaluate('wildGeneralsModal()');assert.match(e.evaluate('previewHTML'),/花鬘 <span class="label">入手 Lv.60/);assert.match(e.evaluate('previewHTML'),/蹋顿 <span class="label">入手 Lv.65/);assert.equal(JSON.stringify(g.state),before);});

test('new saves missing a single starting record are rejected instead of gaining leadership twice',()=>{const e=prepared(),id=recruitWild(e,'huaman'),g=e.Game,d=cloneActiveSave(g.state);delete d.famousStarts[id];assert.equal(g.validSave(d),false);assert.equal(g.validSave(g.migrateSave(d)),false);const before=JSON.stringify(g.state);assert.throws(()=>g.importSave(d));assert.equal(JSON.stringify(g.state),before);});
