const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city,cloneActiveSave}=require('./helpers/game.cjs');
const copy=x=>JSON.parse(JSON.stringify(x)),HOUR=3600000;
function fixture(){const e=loadGame(330),g=e.Game,s=g.state,G=e.evaluate('GovernanceSystem');return {e,g,s,G};}
function hero(f,id='yan'){f.s.generals.push(id);f.s.generalLevels[id]=1;f.s.generalXp[id]=0;f.s.realm.heroLocations[id]='capital';f.e.evaluate('HeroSystem.init(Game.state)');return id;}
function addCity(f){f.e.evaluate("Game.state.conquered.yellow_qingshi=true;Game.state.towns.yellow_qingshi.morale=-5;Game.state.realm.cities.city_yellow_qingshi=CitySystem.empty(Game.state,Game.getNode('yellow_qingshi'),Date.now());CitySystem.capture(Game.state);");return f.s.realm.cities.city_yellow_qingshi;}
test('legacy saves acquire fresh clocks and empty arrears without backcharging old playtime',()=>{const f=fixture(),d=cloneActiveSave(f.s);delete d.heroService;for(const c of Object.values(d.realm.cities))delete c.data.governance;delete d.governance;d.last-=30*HOUR;d.realm.cities.capital.data.last=d.last;assert.equal(f.g.importSave(d),undefined);assert.equal(f.g.state.heroService.lastPay,f.e.now());assert.deepEqual(copy(f.g.state.heroService.owed),{});assert.equal(f.g.validSave(f.g.state),true);});
test('migration uses a shared clock when milliseconds advance between top-level and city initialization',()=>{const f=fixture(),d=cloneActiveSave(f.s);delete d.heroService;delete d.governance;delete d.warCare;for(const c of Object.values(d.realm.cities)){delete c.data.governance;delete c.data.warCare;}f.e.evaluate('let migrationClock=Date.now();Date.now=()=>++migrationClock;');const migrated=f.g.migrateSave(d);assert.equal(migrated.governance.last,migrated.realm.cities.capital.data.governance.last);assert.equal(f.g.validSave(migrated),true);});
test('salaries are hourly, paid from each hero city and cannot repeat after reload',()=>{const f=fixture(),c=addCity(f);f.s.governor=null;f.s.generalLevels.lin=2;f.s.realm.heroLocations.su=c.id;f.s.res.gold=1000;c.data.res.gold=1000;f.G.tickHeroes(f.s,f.e.now()+HOUR-1);assert.equal(f.s.res.gold,1000);f.G.tickHeroes(f.s,f.e.now()+HOUR);assert.equal(f.s.res.gold,960);assert.equal(c.data.res.gold,980);const save=copy(f.s),before=copy(save);f.G.tickHeroes(save,f.e.now()+HOUR);assert.deepEqual(save,before);assert.equal(f.g.validSave(f.s),true);});
test('shortfalls accumulate; restoring gold pays arrears plus next salary exactly once',()=>{const f=fixture();f.s.res.gold=0;f.G.tickHeroes(f.s,f.e.now()+2*HOUR);assert.equal(f.s.heroService.owed.lin,40);assert.equal(f.s.heroService.owed.su,40);assert.equal(f.s.heroLoyalty.lin,70);f.s.res.gold=200;f.G.tickHeroes(f.s,f.e.now()+3*HOUR);assert.equal(f.s.res.gold,80);assert.deepEqual(copy(f.s.heroService.owed),{});assert.equal(f.s.heroLoyalty.lin,70);});
test('arrears previews reject stale bills atomically and successful repayment restores loyalty',()=>{const f=fixture();f.s.res.gold=0;f.G.tickHeroes(f.s,f.e.now()+HOUR);const q=f.G.salaryQuote(f.s);f.G.tickHeroes(f.s,f.e.now()+2*HOUR);f.s.res.gold=200;const before=copy(f.s);assert.match(f.G.payArrears(f.s,'all',q.key,f.e.now()),/变化/);assert.deepEqual(copy(f.s),before);const current=f.G.salaryQuote(f.s);assert.equal(f.G.payArrears(f.s,'all',current.key,f.e.now()),null);assert.equal(f.s.res.gold,120);assert.equal(f.s.heroLoyalty.lin,80);assert.match(f.G.payArrears(f.s,'all',current.key,f.e.now()),/变化/);});
test('busy zero-loyalty generals defer departure; returning idle clears appointments and keeps readable archives',()=>{const f=fixture(),id=hero(f);f.s.heroLoyalty[id]=0;f.s.cityRoles.commander=id;f.s.governor=id;f.G.tickHeroes(f.s,f.e.now(),{busy:x=>x===id});assert.equal(f.s.generals.includes(id),true);assert.deepEqual(copy(f.s.heroService.pending),[id]);f.G.tickHeroes(f.s,f.e.now(),{busy:()=>false});assert.equal(f.s.generals.includes(id),false);assert.equal(f.s.governor,null);assert.equal(f.s.cityRoles.commander,'');assert.equal(f.g.validSave(f.s),true);});
test('initial two generals remain at their documented loyalty floor and offline wages cap at eight hours',()=>{const f=fixture();f.s.res.gold=0;f.s.heroLoyalty.lin=21;f.s.heroLoyalty.su=21;f.G.tickHeroes(f.s,f.e.now()+100*HOUR);assert.equal(f.s.heroService.owed.lin,160);assert.equal(f.s.heroService.owed.su,160);assert.equal(f.s.heroLoyalty.lin,20);assert.equal(f.s.generals.length,2);assert.equal(f.g.validSave(f.s),true);});
test('real offline engine bills after city income and subsequent reload cannot double charge',()=>{const f=fixture();f.s.res.gold=1000000;f.g.save();f.e.offline(HOUR);assert.equal(f.g.state.heroService.lastPay,f.e.now());assert.equal(f.g.state.heroService.log.filter(r=>r.text.includes('领取薪俸')).length,2);const gold=f.g.state.res.gold;f.g.init();assert.equal(f.g.state.res.gold,gold);assert.equal(f.g.validSave(f.g.state),true);});
test('real 24-hour offline catchup shares one eight-hour window for production and hourly salaries',()=>{const f=fixture();f.s.governor=null;f.s.tax=0;f.s.res.food=0;f.s.res.gold=100000;const perHour=f.g.rates().food*60;f.g.save();f.e.offline(24*HOUR);assert.ok(Math.abs(f.g.state.res.food-perHour*8)<.001);assert.equal(f.g.state.res.gold,99680);assert.equal(f.g.state.heroService.log.filter(r=>r.text.includes('领取薪俸')).length,16);const before=copy(f.g.state.res);f.g.init();assert.deepEqual(copy(f.g.state.res),before);assert.equal(f.g.validSave(f.g.state),true);});
test('city loss captures only low-loyalty idle non-starter heroes; source roles clear and both saves stay valid',()=>{const a=fixture(),b=fixture(),id=hero(a);city(b.g,{tavern:4});a.s.heroLoyalty[id]=49;a.s.governor=id;a.s.cityRoles.commander=id;let r=a.G.captureDefeated(a.s,b.s,id,a.e.now(),{busyIds:[id]});assert.equal(r.status,'returned');assert.equal(a.s.generals.includes(id),true);r=a.G.captureDefeated(a.s,b.s,id,a.e.now());assert.equal(r.status,'captured');assert.equal(a.s.generals.includes(id),false);assert.equal(a.s.governor,null);assert.equal(a.s.cityRoles.commander,'');assert.equal(b.s.heroService.captives.length,1);assert.equal(a.g.validSave(a.s),true);assert.equal(b.g.validSave(b.s),true);assert.equal(a.G.captureDefeated(a.s,b.s,'lin',a.e.now()).status,'returned');});
test('recruiting a defeated general consumes gold once, uses a local city slot and survives reload',()=>{const a=fixture(),b=fixture(),id=hero(a);city(b.g,{tavern:4});a.s.heroLoyalty[id]=10;const r=a.G.captureDefeated(a.s,b.s,id,a.e.now());b.s.res.gold=20000;const q=b.g.defeatedHeroQuote(r.captiveId,'gold');assert.equal(q.reason,'');assert.equal(b.g.recruitDefeatedHero(r.captiveId,'gold',q.key),null);assert.equal(b.s.res.gold,14000);assert.equal(b.s.generals.includes(r.captiveId),true);assert.equal(b.s.heroLoyalty[r.captiveId],40);assert.equal(b.g.validSave(b.s),true);assert.match(b.g.recruitDefeatedHero(r.captiveId,'gold',q.key),/变化/);b.g.save();b.g.init();assert.equal(b.g.state.generals.includes(r.captiveId),true);assert.equal(b.g.validSave(b.g.state),true);});
test('full recruitment capacity releases defeated generals and captives expire at exactly 24 hours',()=>{const a=fixture(),b=fixture(),id=hero(a);a.s.heroLoyalty[id]=10;assert.equal(a.G.captureDefeated(a.s,b.s,id,a.e.now()).status,'released');const c=fixture();hero(c);c.s.heroLoyalty.yan=10;city(b.g,{tavern:4});const r=c.G.captureDefeated(c.s,b.s,'yan',c.e.now());b.G.tickHeroes(b.s,b.e.now()+24*HOUR-1);assert.equal(b.s.heroService.captives.length,1);b.G.tickHeroes(b.s,b.e.now()+24*HOUR);assert.equal(b.s.heroService.captives.length,0);assert.equal(b.G.captiveQuote(b.s,r.captiveId),null);assert.equal(b.g.validSave(b.s),true);});
test('unrest reduces the actual morale target and overflow itself leaves city morale unchanged',()=>{const f=fixture();f.s.tax=20;f.s.unrest=30;assert.equal(f.G.moraleTarget(f.s),50);f.s.res.food=1000000000;const morale=f.s.morale;f.G.tickCity(f.s,f.e.now()+1);assert.equal(f.s.morale,morale);assert.equal(f.s.unrest,30);assert.equal(f.s.governance.crisisSince,0);});
test('civil crisis has a one-hour grace period and recovery cancels the pending consequence',()=>{const f=fixture();f.s.population=1000;f.s.unrest=60;f.s.res.wood=1000;f.G.tickCity(f.s,f.e.now()+1);f.G.tickCity(f.s,f.e.now()+HOUR);assert.equal(f.s.population,1000);assert.equal(f.s.res.wood,1000);f.G.tickCity(f.s,f.e.now()+HOUR+1);assert.equal(f.s.population,950);assert.equal(f.s.res.wood,950);f.s.unrest=0;f.s.morale=80;f.G.tickCity(f.s,f.e.now()+HOUR+2);assert.equal(f.s.governance.crisisSince,0);f.G.tickCity(f.s,f.e.now()+3*HOUR);assert.equal(f.s.population,950);});
test('starvation loses only home troops after grace; transit and wounded stocks are preserved',()=>{const f=fixture();f.s.res.food=0;f.s.army.archer=200;f.s.army.militia=1;f.s.expeditions=[{army:{archer:1000}}];f.s.warCare.wounded.archer=10;f.G.tickCity(f.s,f.e.now()+1);f.G.tickCity(f.s,f.e.now()+HOUR);assert.equal(f.s.army.archer,200);f.G.tickCity(f.s,f.e.now()+HOUR+1);assert.equal(f.s.army.archer,198);assert.equal(f.s.army.militia,0);assert.equal(f.s.expeditions[0].army.archer,1000);assert.equal(f.s.warCare.wounded.archer,10);f.s.res.food=1;f.G.tickCity(f.s,f.e.now()+HOUR+2);assert.equal(f.s.governance.starvedSince,0);});
test('disasters require opt-in and sacrifice actually pays for a one-use ward and blessing',()=>{const f=fixture();f.s.population=100;f.s.res.food=10000;f.s.res.wood=10000;f.s.res.gold=10000;f.G.tickCity(f.s,f.e.now()+8*HOUR);assert.equal(f.s.res.wood,10000);assert.equal(f.s.res.food,10000);const at=f.e.now()+8*HOUR;assert.equal(f.G.setPolicy(f.s,'eventsEnabled',true,at),null);assert.equal(f.G.sacrifice(f.s,at),null);assert.equal(f.s.res.food,9900);assert.equal(f.s.res.gold,9900);assert.match(f.G.sacrifice(f.s,at+1),/冷却/);f.G.tickCity(f.s,at+4*HOUR);assert.equal(f.s.res.food,9900);assert.equal(f.s.governance.wardUntil,0);assert.equal(f.s.unrest,0);f.G.tickCity(f.s,at+8*HOUR);assert.equal(f.s.res.wood,9500);assert.equal(f.s.unrest,10);const late=at+8*HOUR+1;assert.equal(f.G.sacrifice(f.s,late),null);const before=f.s.res.food;f.G.tickCity(f.s,at+12*HOUR);assert.equal(f.s.res.food,before+1000);assert.equal(f.s.governance.blessingUntil,0);assert.equal(f.g.validSave(f.s),true);});
test('automatic relief cannot spend below its fixed cost and suppresses a funded crisis',()=>{const f=fixture();f.s.population=1000;f.s.morale=15;f.s.unrest=60;f.s.res.gold=999;f.G.setPolicy(f.s,'autoRelief',true,f.e.now());f.G.tickCity(f.s,f.e.now()+1);assert.equal(f.s.res.gold,999);assert.ok(f.s.governance.crisisSince);f.s.res.gold=1000;f.G.tickCity(f.s,f.e.now()+2);assert.equal(f.s.res.gold,0);assert.equal(f.s.morale,40);assert.equal(f.s.unrest,45);assert.equal(f.s.governance.crisisSince,0);});
test('corrupt salary and governance records are rejected safely instead of loading partial state',()=>{const f=fixture();for(const mutate of [s=>s.heroService.owed.fake=1,s=>s.heroService.lastPay=-1,s=>s.heroService.pending=['lin'],s=>s.governance.eventsEnabled='yes',s=>s.heroService.captives=[{id:'fake'}]]){const s=cloneActiveSave(f.s);mutate(s);s.realm.cities.capital.data.governance=s.governance;assert.doesNotThrow(()=>f.g.validSave(s));assert.equal(f.g.validSave(s),false);}});
