const {test}=require('node:test'),assert=require('node:assert/strict');
const {prepared,recruitWild,recruitGarrison}=require('./helpers/hero-fixtures.cjs');
const {cloneActiveSave}=require('./helpers/game.cjs');
const H=e=>e.evaluate('HeroSystem');
function ordinary(e){const g=e.Game;assert.equal(g.refreshInn(),null);const c=g.state.innCandidates[0];c.level=5;c.lead=50;assert.equal(g.recruit(c.id),null);return c.id;}
test('level twenty heroes have a fixed individual command advantage',()=>{for(const [source,want] of [['ordinary',200],['named_wancheng',900],['guanyu',1200],['zhouyu',1300]]){const e=prepared(),id=source==='ordinary'?ordinary(e):source.startsWith('named_')?recruitGarrison(e,source):recruitWild(e,source);e.Game.state.generalLevels[id]=20;assert.equal(e.Game.general(id).lead,want);}});
test('ordinary recruitment base gains ten leadership per later level without overwriting raw stats',()=>{const e=prepared(),id=ordinary(e),s=e.Game.state,before=JSON.stringify(s.customGenerals);s.generalLevels[id]=20;assert.equal(e.Game.general(id).lead,200);assert.equal(JSON.stringify(s.customGenerals),before);s.customGenerals.find(g=>g.id===id).lead=100;assert.equal(e.Game.general(id).lead,250);s.generalLevels[id]=10000;assert.equal(e.Game.general(id).lead,100050);});
test('zero and absent raw leadership keep the existing current-level fallback',()=>{const e=prepared(),id=ordinary(e),s=e.Game.state;s.generalLevels[id]=20;s.customGenerals.find(g=>g.id===id).lead=0;assert.equal(e.Game.general(id).lead,200);delete s.customGenerals.find(g=>g.id===id).lead;assert.equal(e.Game.general(id).lead,200);s.generalLevels.lin=20;assert.equal(e.Game.general('lin').lead,200);});
test('command table derives known individual additions and gives unknown identities no bonus',()=>{const e=prepared(),h=H(e);assert.equal(typeof h.initialLeadership,'function');for(const [key,want] of Object.entries({weiyan:85,xushu:80,zhaoyun:90,huangzhong:85,ganning:90,zhangliao:105,machao:90,xunyu:75,pangtong:90,zhouyu:110,guanyu:100,zhangfei:85,dianwei:70,lvbu:95,taishici:85,liubei:100,sunjian:100,gaoshun:95,chengong:85,lejin:85,yujin:95,zhanghe:100,xuhuang:100,zhugeliang:110,sunce:105,xuchu:70}))assert.equal(h.initialLeadership(key),want);for(const key of ['wanderer','lin','ordinary','unknown','__proto__'])assert.equal(h.initialLeadership(key),0);});
test('equipment and skill leadership are added once before technology and tiger buff',()=>{const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu'),s=g.state;s.generalLevels[id]=20;
 // Two tier-3 pieces: each lead 8 plus enhance-10 multiplier 2.5 = 20.
 s.equipment=[{id:1,slot:'weapon',tier:3,enhance:10,hero:id},{id:2,slot:'armor',tier:3,enhance:10,hero:id}];s.equipmentSeq=2;s.tech.leadership=2;s.buffs['tiger:'+id]={effect:'tiger',general:id,end:e.now()+100000};
 assert.equal(g.general(id).lead,2232); // (1200 + 40) * 1.2 * 1.5
 s.heroSkills[id]={route:'politics',level:1};assert.equal(g.general(id).lead,2235.6); // skill adds 2, before multipliers
});
test('same-name ordinary generals do not receive a reserved future hero bonus',()=>{const e=prepared(),g=e.Game,id=ordinary(e);g.state.customGenerals.find(g=>g.id===id).name='诸葛亮';g.state.generalLevels[id]=20;assert.equal(g.general(id).lead,200);});
test('old hero saves repeatedly migrate and import without accumulating initial command',()=>{const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu');g.state.generalLevels[id]=20;g.save();const old=cloneActiveSave(g.state),raw=JSON.stringify(old.customGenerals);for(let n=0;n<3;n++){g.importSave(g.migrateSave(cloneActiveSave(old)));assert.equal(g.validSave(g.state),true);assert.equal(g.general(id).lead,1200);assert.equal(JSON.stringify(g.state.customGenerals),raw);}const before=JSON.stringify(g.state);g.general(id);g.getCityState('capital');assert.equal(JSON.stringify(g.state),before);});
