const {test}=require('node:test'),assert=require('node:assert/strict');
const {prepared,recruitWild,recruitGarrison}=require('./helpers/hero-fixtures.cjs');
const {cloneActiveSave}=require('./helpers/game.cjs');
const H=e=>e.evaluate('HeroSystem');
function ordinary(e){const g=e.Game;assert.equal(g.refreshInn(),null);const c=g.state.innCandidates[0];c.level=5;c.lead=50;assert.equal(g.recruit(c.id),null);return c.id;}
test('level twenty heroes have a fixed individual command advantage',()=>{for(const [source,want] of [['ordinary',200],['named_wancheng',350],['guanyu',450],['zhouyu',500]]){const e=prepared(),id=source==='ordinary'?ordinary(e):source.startsWith('named_')?recruitGarrison(e,source):recruitWild(e,source);e.Game.state.generalLevels[id]=20;assert.equal(e.Game.general(id).lead,want);}});
test('ordinary recruitment base gains ten leadership per later level without overwriting raw stats',()=>{const e=prepared(),id=ordinary(e),s=e.Game.state,before=JSON.stringify(s.customGenerals);s.generalLevels[id]=20;assert.equal(e.Game.general(id).lead,200);assert.equal(JSON.stringify(s.customGenerals),before);s.customGenerals.find(g=>g.id===id).lead=100;assert.equal(e.Game.general(id).lead,250);s.generalLevels[id]=10000;assert.equal(e.Game.general(id).lead,100050);});
test('zero and absent raw leadership keep the existing current-level fallback',()=>{const e=prepared(),id=ordinary(e),s=e.Game.state;s.generalLevels[id]=20;s.customGenerals.find(g=>g.id===id).lead=0;assert.equal(e.Game.general(id).lead,200);delete s.customGenerals.find(g=>g.id===id).lead;assert.equal(e.Game.general(id).lead,200);s.generalLevels.lin=20;assert.equal(e.Game.general('lin').lead,200);});
test('command table derives known individual additions and gives unknown identities no bonus',()=>{const e=prepared(),h=H(e);assert.equal(typeof h.initialLeadership,'function');for(const [key,want] of Object.entries({weiyan:20,xushu:18,zhaoyun:23,huangzhong:20,ganning:21,zhangliao:28,machao:23,xunyu:16,pangtong:23,zhouyu:30,guanyu:25,zhangfei:20,dianwei:15,lvbu:24,taishici:20,liubei:25,sunjian:25,gaoshun:24,chengong:20,lejin:20,yujin:24,zhanghe:25,xuhuang:25,zhugeliang:30,sunce:28,xuchu:15}))assert.equal(h.initialLeadership(key),want);for(const key of ['wanderer','lin','ordinary','unknown','__proto__'])assert.equal(h.initialLeadership(key),0);});
test('equipment and skill leadership are added once before technology and tiger buff',()=>{const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu'),s=g.state;s.generalLevels[id]=20;
 // Two tier-3 pieces: each lead 8 plus enhance-10 multiplier 2.5 = 20.
 s.equipment=[{id:1,slot:'weapon',tier:3,enhance:10,hero:id},{id:2,slot:'armor',tier:3,enhance:10,hero:id}];s.equipmentSeq=2;s.tech.leadership=2;s.buffs['tiger:'+id]={effect:'tiger',general:id,end:e.now()+100000};
 assert.equal(g.general(id).lead,882); // (450 + 40) * 1.2 * 1.5
 s.heroSkills[id]={route:'politics',level:1};assert.ok(Math.abs(g.general(id).lead-885.6)<1e-9); // skill adds 2, before multipliers
});
test('same-name ordinary generals do not receive a reserved future hero bonus',()=>{const e=prepared(),g=e.Game,id=ordinary(e);g.state.customGenerals.find(g=>g.id===id).name='诸葛亮';g.state.generalLevels[id]=20;assert.equal(g.general(id).lead,200);});
test('old hero saves repeatedly migrate and import without accumulating initial command',()=>{const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu');g.state.generalLevels[id]=20;g.save();const old=cloneActiveSave(g.state),raw=JSON.stringify(old.customGenerals);for(let n=0;n<3;n++){g.importSave(g.migrateSave(cloneActiveSave(old)));assert.equal(g.validSave(g.state),true);assert.equal(g.general(id).lead,450);assert.equal(JSON.stringify(g.state.customGenerals),raw);}const before=JSON.stringify(g.state);g.general(id);g.getCityState('capital');assert.equal(JSON.stringify(g.state),before);});
test('initial command changes none of the other four hero attributes',()=>{const e=prepared(),id=recruitWild(e,'guanyu');e.Game.state.generalLevels[id]=20;const g=e.Game.general(id);assert.deepEqual({atk:g.atk,def:g.def,pol:g.pol,wis:g.wis},{atk:181,def:157,pol:66,wis:74});});
test('four-piece set leadership is not multiplied by the famous-hero addition',()=>{const e=prepared(),id=recruitWild(e,'guanyu'),s=e.Game.state;s.generalLevels[id]=20;s.equipment=['weapon','armor','helmet','accessory'].map((slot,i)=>({id:i+1,slot,tier:4,enhance:10,hero:id}));s.equipmentSeq=4;assert.equal(e.Game.general(id).lead,540);assert.equal(e.Game.validSave(cloneActiveSave(s)),true);});
