const {test}=require('node:test'),assert=require('node:assert/strict');
const {prepared,recruitWild}=require('./helpers/hero-fixtures.cjs');
const {cloneActiveSave,city}=require('./helpers/game.cjs');
function sent(count=300){const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu');g.state.generalLevels[id]=20;g.state.army.cavalry=count;g.state.res.food=1000000;g.setTactic('cavalry','advance','');assert.equal(g.dispatch('field',id,{cavalry:count},'raid'),null);return {e,g,id};}
function arrive(f){f.e.advance(Math.ceil(f.g.state.expedition.end-f.e.now())+1);assert.equal(f.g.startBattle(),null);}
test('new dispatch freezes initial command while imported old snapshots stay unchanged',()=>{const f=sent();assert.equal(f.g.state.expedition.generalSnapshot.lead,450);const d=cloneActiveSave(f.g.state);d.expedition.generalSnapshot.lead=120;f.g.importSave(d);arrive(f);assert.equal(f.g.state.battle.generalSnapshot.lead,120);const old=cloneActiveSave(f.g.state),snapshot=JSON.stringify(old.battle.generalSnapshot);f.g.importSave(old);f.g.battleRound();assert.equal(JSON.stringify(f.g.state.battle.generalSnapshot),snapshot);assert.equal(f.g.validSave(f.g.state),true);});
test('legacy marching armies without a snapshot start with the old command formula',()=>{const f=sent();const d=cloneActiveSave(f.g.state);delete d.expedition.generalSnapshot;assert.equal(f.g.validSave(d),true);f.g.importSave(d);arrive(f);assert.equal(f.g.state.battle.generalSnapshot.lead,120);});
test('legacy rules-two combat without snapshot matches an explicit old command snapshot',()=>{
 const f=sent(30000);arrive(f);const d=cloneActiveSave(f.g.state);d.battle.rules=2;delete d.battle.stratagem;delete d.battle.generalSnapshot;delete d.expedition.generalSnapshot;assert.equal(f.g.validSave(d),true);
 const old=cloneActiveSave(d);old.battle.generalSnapshot={...f.g.general(f.id),lead:120};const h=prepared();h.Game.importSave(old);f.g.importSave(d);
 for(let i=0;i<12&&!f.g.state.battle.finished;i++){f.g.battleRound();h.Game.battleRound();assert.deepEqual(JSON.parse(JSON.stringify(f.g.state.battle.player)),JSON.parse(JSON.stringify(h.Game.state.battle.player)));assert.deepEqual(JSON.parse(JSON.stringify(f.g.state.battle.enemy)),JSON.parse(JSON.stringify(h.Game.state.battle.enemy)));}
});
test('higher leadership does not bypass drill capacity or fourth-chapter troop limits',()=>{const f=sent();f.e.advance(Math.ceil(f.g.state.expedition.end-f.e.now())+1);f.g.startBattle();for(let n=0;n<30&&!f.g.state.battle.finished;n++)f.g.battleRound();f.e.advance(Math.ceil(f.g.state.expedition?.end-f.e.now())+1);f.g.dismissBattle();city(f.g,{drill:1});f.g.state.army.cavalry=20000;assert.match(f.g.dispatch('wild_31_32',f.id,{cavalry:20000}),/校场|上限|超过/);});

test('famous command cannot bypass Hulao six-thousand rule',()=>{const e=prepared(),g=e.Game,id=recruitWild(e,'guanyu');city(g,{hall:10,house:10,drill:10,barracks:10,academy:10});for(const n of [...e.Chapter.nodes,...e.Chapter.chapterThreeNodes])g.state.conquered[n.id]=true;g.state.conquered.c4_sishui=true;g.state.conquered.fort=true;g.state.conquered.camp=true;g.state.generalLevels[id]=20;g.state.army.cavalry=7000;g.state.res.food=1000000;assert.match(g.dispatch('c4_hulao',id,{cavalry:7000},'occupy'),/最多 6000/);});
