const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city,cloneActiveSave}=require('./helpers/game.cjs');
const view=e=>e.evaluate('JourneySystem.view(Game)');
test('journey is a pure five-stage projection with one construction target on a new save',()=>{const e=loadGame(),before=JSON.stringify(e.Game.state),v=view(e);assert.equal(v.steps.length,5);assert.equal(v.current.id,'build');assert.equal(JSON.stringify(e.Game.state),before);});
test('build prerequisites and capture versus recruited state drive the next target',()=>{const e=loadGame();city(e.Game,{hall:3,drill:1});e.Game.state.generalLevels.lin=5;assert.equal(view(e).current.id,'yellow');e.Game.state.battlefields.firstClears.yellow_turban=true;assert.equal(view(e).current.id,'hero');e.Game.state.realm.namedCities.garrisons.named_jiangling.captive=true;assert.equal(view(e).current.id,'hero');e.Game.state.realm.namedCities.garrisons.named_jiangling.recruited=true;assert.equal(view(e).steps.find(x=>x.id==='hero').complete,true);assert.match(view(e).steps.find(x=>x.id==='jiangling').status,/解雇|离队/);});
test('tracking is validated and persisted but cannot modify a readonly save',()=>{const e=loadGame(),g=e.Game;assert.equal(g.setJourneyTarget('yellow'),null);assert.equal(view(e).current.id,'yellow');assert.ok(g.setJourneyTarget('forged'));g.save();g.init();assert.equal(g.state.journey.tracked,'yellow');g.releaseSaveSession();const before=JSON.stringify(g.state);assert.ok(g.setJourneyTarget('build'));assert.equal(JSON.stringify(g.state),before);});
test('legacy saves migrate tracking once and forged fields fail strict validation',()=>{const e=loadGame(),g=e.Game,d=cloneActiveSave(g.state);delete d.journey;const migrated=g.migrateSave(d);assert.equal(migrated.journey.tracked,'');assert.equal(g.validSave(migrated),true);for(const bad of [{version:2,tracked:''},{version:1,tracked:'bad'},{version:1,tracked:'',extra:1},null]){const x=cloneActiveSave(g.state);x.journey=bad;assert.equal(g.validSave(x),false);}});
test('a recruited city general is shown as present and only then becomes dismissed',()=>{const e=loadGame(),g=e.Game,id=e.evaluate("NamedGarrison.hero('named_jiangling').id");g.state.realm.namedCities.garrisons.named_jiangling.recruited=true;g.state.generals.push(id);assert.match(view(e).steps.find(x=>x.id==='jiangling').status,/已归顺/);g.state.generals=g.state.generals.filter(x=>x!==id);assert.match(view(e).steps.find(x=>x.id==='jiangling').status,/解雇或离队/);});
test('owned second city is current ownership and main-city construction does not regress after switching',()=>{const e=loadGame();city(e.Game,{hall:3,drill:1});e.Game.state.generalLevels.lin=5;e.evaluate(`var journeyReal=Game;var journeyRows=Game.cityList();var journeyFake=Object.create(Game);journeyFake.cityList=()=>[...journeyRows,{id:'other',capital:false,buildings:{hall:1,drill:0}}];journeyFake.requirementLevel=()=>0;`);const v=e.evaluate('JourneySystem.view(journeyFake)');assert.equal(v.steps[0].complete,true);assert.equal(v.steps.find(x=>x.id==='cities').complete,true);assert.equal(view(e).steps.find(x=>x.id==='cities').complete,false);});
test('journey destinations call existing modal entrypoints rather than missing functions',()=>{const e=loadGame(),fs=require('node:fs');e.evaluate(`var journeyCalls=[];function guideGo(){journeyCalls.push('build')}function battlefieldModal(){journeyCalls.push('yellow')}function heroCodexModal(){journeyCalls.push('hero')}function citySwitchListModal(){journeyCalls.push('cities')}function namedCityOverviewModal(){journeyCalls.push('locked')}function worldNodeModal(id){journeyCalls.push(id)}`);e.evaluate(fs.readFileSync('journey-ui.js','utf8'));e.evaluate("['yellow','hero','cities','jiangling'].forEach(journeyGo)");assert.deepEqual(Array.from(e.evaluate('journeyCalls')),['yellow','hero','cities','locked']);});
test('a dismissed historical wild general keeps its milestone while a legacy ordinary wild general never completes it',()=>{const {prepared,recruitWild}=require('./helpers/hero-fixtures.cjs'),e=prepared(),id=recruitWild(e,'huaman');assert.equal(view(e).steps.find(x=>x.id==='hero').complete,true);assert.equal(e.Game.dismissGeneral(id),null);assert.equal(view(e).steps.find(x=>x.id==='hero').complete,true);});

test('legacy ordinary wild recruitment never completes the famous general milestone',()=>{const {prepared,recruitWild}=require('./helpers/hero-fixtures.cjs'),e=prepared();recruitWild(e,'wanderer');assert.equal(view(e).steps.find(x=>x.id==='hero').complete,false);});
test('main-city build destination switches away from a secondary city and opens the actual hall gap',()=>{const e=loadGame(),fs=require('node:fs');e.evaluate(`Game.state.conquered.yellow_qingshi=true;var c=CitySystem.empty(Game.state,Game.getNode('yellow_qingshi'),Date.now());Game.state.realm.cities[c.id]=c;CitySystem.capture(Game.state);Game.switchCity(c.id);var calls=[],page='city',cityArea='inner';function S(){return Game.state}var modal={close(){}};function render(){}function actResult(error){return !error}function manualBuildingModal(id){calls.push(id)}function guideGo(){calls.push('wrong-current-city-guide')}`);e.evaluate(fs.readFileSync('journey-ui.js','utf8'));e.evaluate("journeyGo('build')");assert.equal(e.Game.currentCityId(),'capital');assert.match(e.evaluate('calls[0]'),/^site:/);});
test('an uncompleted second-city goal leads to promotion before territory rather than its owned city list',()=>{const e=loadGame(),fs=require('node:fs');e.evaluate(`var calls=[];function heritageHonorModal(){calls.push('promotion')}function namedCityOverviewModal(){calls.push('territory')}function classicMissionModal(){calls.push('epic')}var taskTab='';`);e.evaluate(fs.readFileSync('journey-ui.js','utf8'));const step=view(e).steps.find(x=>x.id==='cities');assert.equal(step.action,'expand');e.evaluate("journeyGo('expand')");assert.equal(e.evaluate('calls[0]'),'promotion');});
test('explicitly tracked milestone takes the home objective slot while claimable rewards remain in tasks',()=>{const e=loadGame(),fs=require('node:fs');e.evaluate(`function S(){return Game.state}function num(v){return String(v)}function mainlineModel(){return {current:null}}`);e.evaluate(fs.readFileSync('classic-ui.js','utf8'));assert.equal(e.Game.setJourneyTarget('hero'),null);assert.equal(e.evaluate('currentObjectiveModel().action'),'journeyGo');assert.equal(e.evaluate('currentObjectiveModel().arg'),'hero');});
