const {test}=require('node:test'),assert=require('node:assert/strict');const {nanReady,beginNan}=require('./helpers/nanman.cjs');
function ui(){const e=nanReady();e.evaluate(`function S(){return Game.state;}function esc(x){return String(x);}function num(x){return String(x);}function btn(t,a,id='',style='',disabled=false){return '<button data-action="'+a+'" data-id="'+id+'"'+(disabled?' disabled':'')+'>'+t+'</button>';}globalThis.dialogHTML='';globalThis.dialogTitle='';globalThis.messages=[];function showModal(t,b,f){dialogTitle=t;dialogHTML=b+(f||'');}function toast(x){messages.push(x);}globalThis.form={'battlefield-general':{value:'lin'},'battlefield-start-militia':{value:'800'}};document.getElementById=id=>form[id]||null;`);return e;}
test('two campaign cards and selected nanman map expose independent daily box status without writing saves',()=>{const e=ui(),G=e.Game,before=JSON.stringify(G.state);e.evaluate('battlefieldModal()');assert.match(e.evaluate('dialogHTML'),/南蛮入侵/);e.evaluate("handleBattlefieldAction('battlefieldCampaign','nanman')");assert.match(e.evaluate('dialogTitle'),/南蛮/);assert.match(e.evaluate('dialogHTML'),/孟获/);assert.match(e.evaluate('dialogHTML'),/10级/);assert.match(e.evaluate('dialogHTML'),/蛮族箱/);assert.equal((e.evaluate('dialogHTML').match(/data-battlefield-node=/g)||[]).length,15);assert.equal(JSON.stringify(G.state),before);
 e.evaluate("handleBattlefieldAction('battlefieldStartAsk','');handleBattlefieldAction('battlefieldStart','')");assert.equal(G.state.battlefields.run.campaign,'nanman');e.evaluate("handleBattlefieldAction('battlefieldCampaign','yellow_turban')");assert.match(e.evaluate('dialogTitle'),/南蛮/);
});
test('changing campaign invalidates pending start confirmation instead of consuming another campaign token',()=>{const e=ui(),G=e.Game;const before=JSON.stringify(G.state);e.evaluate("handleBattlefieldAction('battlefieldStartAsk','');handleBattlefieldAction('battlefieldCampaign','nanman');handleBattlefieldAction('battlefieldStart','')");assert.equal(JSON.stringify(G.state),before);assert.equal(G.state.battlefields.run,null);});
test('opening a barbarian box gives one random item without selecting or confirming a duplicate slot',()=>{const e=ui(),G=e.Game;G.state.inventory.barbarianEquipmentBox=2;e.evaluate('Math.random=()=>0');e.evaluate("handleBattlefieldAction('battlefieldCampaign','nanman');handleBattlefieldAction('battlefieldBox','nanman')");assert.equal(G.state.inventory.barbarianEquipmentBox,1);assert.equal(G.state.equipment.at(-1).slot,'weapon');e.evaluate("handleBattlefieldAction('battlefieldBox','nanman')");assert.equal(G.state.inventory.barbarianEquipmentBox,0);assert.equal(G.state.equipment.filter(x=>x.setId==='nanman').length,2);assert.doesNotMatch(e.evaluate('dialogHTML'),/data-action="battlefieldBoxConfirm"/);});
test('mask equipment description explains its attribute-free and once-per-node use',()=>{const e=ui();e.evaluate(require('node:fs').readFileSync(require('node:path').join(__dirname,'../hero-ui.js'),'utf8'));assert.match(e.evaluate("heroEquipmentStatsHTML({slot:'accessory',relic:'mask',tier:1,enhance:0})"),/无属性.*每轮/);});
test('resuming an active nanman run retains its selected campaign after the run ends',()=>{const e=ui();beginNan(e);e.evaluate('battlefieldModal()');assert.match(e.evaluate('dialogTitle'),/南蛮/);e.Game.abandonBattlefield(e.Game.state.battlefields.run.id);e.evaluate('battlefieldModal()');assert.match(e.evaluate('dialogTitle'),/南蛮/);});
test('more menu presents both campaigns through a neutral battlefield entry',()=>{const e=ui();e.evaluate('let webAudioEnabled=false;let manualModalContext=null;');e.evaluate(require('node:fs').readFileSync(require('node:path').join(__dirname,'../layout-ui.js'),'utf8'));e.evaluate('layoutMoreModal()');assert.match(e.evaluate('dialogHTML'),/data-action="battlefieldOpen"/);});

test('opening an absent random box reports the error without crashing',()=>{const e=ui();e.Game.state.equipment=[];e.Game.state.inventory.barbarianEquipmentBox=0;assert.doesNotThrow(()=>e.evaluate("handleBattlefieldAction('battlefieldBox','nanman')"));assert.match(e.evaluate('messages.at(-1)'),/没有/);});
