const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city}=require('./helpers/game.cjs');
const {run}=require('./balance/archer-onboarding.cjs');
test('ten gifts enforce hall level and each tier pays once, even above capacity',()=>{
 const e=loadGame(),g=e.Game,before=g.state.res.food,gold=g.state.res.gold;assert.equal(g.starterGiftReward.gold,10000);assert.equal(g.starterGiftRemaining().gold,10000);assert.match(g.onboarding.claim(2),/官府 2/);assert.equal(g.state.res.food,before);assert.equal(g.onboarding.claim(1),null);assert.equal(g.state.res.food,before+40000);assert.equal(g.state.res.gold,gold+10000);assert.ok(g.state.res.food>g.capacity('food'));const snapshot=JSON.stringify(g.state);assert.match(g.onboarding.claim(1),/已领取/);assert.equal(JSON.stringify(g.state),snapshot);
 city(g,{hall:10});for(let n=2;n<=10;n++)assert.equal(g.onboarding.claim(n),null);assert.equal(g.state.res.gold,gold+1000000);assert.equal(g.state.onboarding.claims.length,10);assert.equal(g.state.inventory.starterJewelBox,8);assert.equal(g.state.inventory.starterEquipmentBasic,1);assert.equal(g.state.inventory.starterEquipmentFine,2);assert.equal(g.validSave(g.state),true);assert.equal(g.starterGiftPending(),false);e.offline(1);assert.match(g.onboarding.claim(10),/已领取/);
});
test('legacy gifts retain paid gold and only receive nonnegative remaining resources and new items',()=>{
 // Legacy single-city saves predate realm; retaining a new city's mirrored resources would make this fixture internally inconsistent.
 for(const version of [undefined,1,2]){const e=loadGame(),g=e.Game,s=JSON.parse(JSON.stringify(g.state));delete s.onboarding;delete s.realm;s.starterGiftClaimed=true;s.starterGiftVersion=version;s.res.gold+=version===2?60000:20000;const migrated=g.migrateSave(s);assert.equal(g.validSave(migrated),true);assert.equal(g.importSave(migrated),undefined);const before={...g.state.res};assert.equal(g.starterGiftRemaining().gold,0);assert.deepEqual(g.starterGiftRemaining(),g.onboarding.quote(g.state,1).resources);assert.equal(g.claimStarterGift(),null);for(const id of Object.keys(before))assert.equal(g.state.res[id]-before[id],version===2||id==='gold'?0:20000);assert.equal(g.state.inventory.speed_build_15m,6);e.offline(1);assert.match(g.claimStarterGift(),/已领取/);}
});
test('batch gift claim skips claimed tiers and locks, and remains paid after reload',()=>{
 const e=loadGame(),g=e.Game;city(g,{hall:5});g.onboarding.claim(3);const ready=g.onboarding.available(g.state).map(q=>g.onboarding.quote(g.state,q.level)),before={...g.state.res},items={...g.state.inventory};assert.equal(g.onboarding.claimAvailable(),null);
 for(const id of Object.keys(before))assert.equal(g.state.res[id]-before[id],ready.reduce((n,q)=>n+(q.resources[id]||0),0));for(const id of new Set(ready.flatMap(q=>Object.keys(q.items))))assert.equal(g.state.inventory[id]-(items[id]||0),ready.reduce((n,q)=>n+(q.items[id]||0),0));assert.deepEqual([...g.state.onboarding.claims].sort(),[1,2,3,4,5]);assert.equal(g.validSave(g.state),true);e.offline(1);const snapshot=JSON.stringify(g.state);assert.match(g.onboarding.claimAvailable(),/没有可领取/);assert.equal(JSON.stringify(g.state),snapshot);city(g,{hall:6});assert.equal(g.onboarding.claimAvailable(),null);assert.equal(g.state.onboarding.claims.at(-1),6);
});
test('batch gift claim preserves both legacy resource deductions and new items',()=>{
 for(const version of [1,2]){const e=loadGame(),g=e.Game;city(g,{hall:3});const old=JSON.parse(JSON.stringify(g.state));delete old.onboarding;old.starterGiftVersion=version;old.starterGiftClaimed=true;g.importSave(old);const before={...g.state.res};assert.equal(g.onboarding.claimAvailable(),null);for(const id of Object.keys(before))assert.equal(g.state.res[id]-before[id],g.onboarding.quote(g.state,2).resources[id]+g.onboarding.quote(g.state,3).resources[id]+(version===2||id==='gold'?0:20000));assert.equal(g.state.inventory.speed_build_15m,6);assert.equal(g.state.starterGiftVersion,2);assert.equal(g.validSave(g.state),true);}
});
test('retuning keeps gold already paid by ten-tier gifts across import and reload, and does not repay claimed tiers',()=>{
 const e=loadGame(),g=e.Game;city(g,{hall:3});const old=JSON.parse(JSON.stringify(g.state));delete old.realm;old.onboarding.claims=[1,2,3];old.starterGiftVersion=2;old.starterGiftClaimed=true;old.res.gold=345000;assert.equal(g.importSave(old),undefined);assert.equal(g.state.res.gold,345000);e.offline(1);assert.equal(g.state.res.gold,345000);assert.match(g.onboarding.claimAvailable(),/没有可领取/);assert.equal(g.state.res.gold,345000);city(g,{hall:4});assert.equal(g.onboarding.claimAvailable(),null);assert.equal(g.state.res.gold,385000);assert.deepEqual([...g.state.onboarding.claims],[1,2,3,4]);assert.equal(g.validSave(g.state),true);
});
test('invalid claims, hidden flags and opening receipts are rejected on import',()=>{
 const e=loadGame(),g=e.Game;for(const mutate of [s=>s.onboarding.claims=[2],s=>s.onboarding.claims=[1,1],s=>s.onboarding.claims=[1.5],s=>s.onboarding.hidden='yes',s=>s.onboarding.lastOpen={kind:'jewel',id:'pearl',count:99},s=>s.onboarding.lastOpen={kind:'equipment',id:999}]){const s=JSON.parse(JSON.stringify(g.state));mutate(s);assert.equal(g.validSave(s),false);}
});
test('jewel boxes roll disclosed bounds, persist the receipt, and cannot be bought or rerolled without a box',()=>{
 const e=loadGame(),g=e.Game,s=g.state;assert.equal(e.evaluate('Object.values(OnboardingData.jewels.weights).reduce((a,b)=>a+b,0)'),100);city(g,{hall:5});assert.equal(g.onboarding.claim(5),null);e.evaluate('Math.random=()=>0');assert.equal(g.useItem('starterJewelBox'),null);assert.equal(s.jewels.pearl,2);assert.equal(s.inventory.starterJewelBox,0);assert.match(g.useItem('starterJewelBox'),/没有/);assert.match(g.buyItem('starterJewelBox'),/不能购买/);assert.equal(g.validSave(s),true);e.offline(1);assert.equal(g.state.onboarding.lastOpen.count,2);city(g,{hall:6});g.onboarding.claim(6);e.evaluate('Math.random=()=>0.999999');assert.equal(g.useItem('starterJewelBox'),null);assert.equal(g.state.jewels.nightPearl,5);assert.equal(g.state.honors.office,0);
});
test('equipment boxes require a valid slot, respect full storage and existing level gates',()=>{
 const e=loadGame(),g=e.Game,s=g.state;city(g,{hall:8});g.onboarding.claim(8);assert.match(g.useItem('starterEquipmentFine','','unknown'),/部位/);assert.equal(s.inventory.starterEquipmentFine,1);for(let i=0;i<s.equipmentCapacity;i++)e.evaluate("HeroSystem.addEquipment(Game.state,'weapon',1)");assert.match(g.useItem('starterEquipmentFine','','armor'),/已满/);assert.equal(s.inventory.starterEquipmentFine,1);s.equipment.pop();assert.equal(g.useItem('starterEquipmentFine','','armor'),null);const item=s.equipment.at(-1);assert.equal(item.tier,2);assert.equal(item.slot,'armor');assert.equal(s.inventory.starterEquipmentFine,0);assert.match(e.evaluate(`HeroSystem.equip(${item.id},'lin')`),/5 级/);assert.equal(g.validSave(s),true);e.offline(1);assert.equal(g.state.equipment.at(-1).id,item.id);
});
test('guide follows actual prerequisites and training, preserves state when viewed, and can stay collapsed',()=>{
 const e=loadGame(),g=e.Game,guide=e.evaluate('GrowthGuide');assert.equal(guide.model(g).kind,'gift');g.claimStarterGift();let before=JSON.stringify(g.state);assert.equal(guide.model(g).id,'house');assert.equal(JSON.stringify(g.state),before);city(g,{hall:2,house:2,barracks:4,drill:1,academy:4});g.state.plots[0]={type:'farm',level:1};g.state.plots[1]={type:'lumber',level:2};g.state.plots[2]={type:'quarry',level:2};g.state.plots[3]={type:'mine',level:3};g.onboarding.claim(2);assert.equal(guide.model(g).id,'smith');g.onboarding.hide(true);e.offline(1);assert.equal(g.state.onboarding.hidden,true);g.onboarding.hide(false);g.state.activityMetrics.train_archer=30;assert.equal(guide.model(g).phase,'battle');assert.notEqual(guide.model(g).id,'hall');
});
test('resource estimate uses real net output, detects caps and does not change stocks',()=>{
 const e=loadGame(),g=e.Game,guide=e.evaluate('GrowthGuide'),before=JSON.stringify(g.state);const q=guide.resources(g,{wood:6000});assert.equal(q.seconds,Math.ceil(1000/g.rates().wood*60));assert.equal(guide.resources(g,{wood:g.capacity('wood')+1}).seconds,null);assert.equal(JSON.stringify(g.state),before);g.state.army.archer=100;assert.equal(guide.resources(g,{food:6000}).seconds,null);
});
test('fresh normal APIs reach thirty archers with earned gifts and speedups under the 90-minute target',()=>{
 const baseline=run(123,false);for(const seed of [123,456]){const actual=run(seed,true);assert.equal(actual.archers,30);assert.equal(actual.validSave,true);assert.ok(actual.minutes<90);assert.ok(actual.minutes<baseline.minutes);assert.ok(actual.spent.gold>20000);assert.ok(actual.used.speed_research_1h>0);assert.ok(actual.log.some(x=>x.target.includes('铁匠铺')));}
});
test('after the archer milestone all ten hall gifts are reachable through actual prerequisites, earned supplies and market purchases',()=>{
 for(const seed of [123,456]){const actual=run(seed,true,'ten-gifts');assert.equal(actual.hall,10);assert.equal(actual.gifts,10);assert.equal(actual.validSave,true);assert.equal(actual.victories,1);assert.equal(actual.firstBattle,'complete');assert.equal(actual.office,1);assert.ok(actual.log.some(x=>x.target.includes('市场')));assert.ok(actual.log.some(x=>x.target.includes('购买')));assert.ok(actual.used.speed_build_15_30h>0);}
});
