const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city,cloneActiveSave}=require('./helpers/game.cjs');
function prepared(){const e=loadGame(),g=e.Game;city(g,{hall:5,house:5,barracks:3,drill:3});g.state.governor=null;g.state.population=g.maxPop();for(const k of Object.keys(g.resources))g.state.res[k]=100000;return e;}
const template=(army={militia:100})=>({hero:'lin',tactic:'advance',army});
function store(g,t=template()){const q=g.siegePreparationQuote('capital','named_jiangling');assert.equal(g.saveSiegePreparation('capital','named_jiangling',t,q.key),null);return g.siegePreparationQuote('capital','named_jiangling');}
test('pure template quote subtracts available and queued troops, never marching troops',()=>{const e=prepared(),g=e.Game;g.state.army.militia=30;assert.equal(g.train('militia',20),null);const q=store(g),before=JSON.stringify(g.state);assert.equal(q.deficits.militia,50);assert.equal(q.orders[0].count,50);g.siegePreparationQuote('capital','named_jiangling');assert.equal(JSON.stringify(g.state),before);});
test('refill confirms one quote once, charging exactly ordinary training cost and population',()=>{const e=prepared(),g=e.Game,q=store(g),before={...g.state.res},pop=g.state.population,cost=g.trainCost('militia',100);assert.equal(g.fillSiegePreparation('capital','named_jiangling',q.key),null);assert.equal(g.state.trainQueue.length,1);assert.equal(g.state.population,pop-100*(g.units.militia.people||1));for(const k of Object.keys(cost))assert.equal(g.state.res[k],before[k]-cost[k]);const after=JSON.stringify(g.state);assert.ok(g.fillSiegePreparation('capital','named_jiangling',q.key));assert.equal(JSON.stringify(g.state),after);});
test('limited funds preview partial orders and full queues charge nothing',()=>{const e=prepared(),g=e.Game;g.state.res.food=g.units.militia.cost.food*3;const q=store(g);assert.equal(q.orders[0].count,3);assert.equal(q.remaining.militia,97);g.state.trainQueue=Array.from({length:g.trainingLimit()},(_,i)=>({id:'militia',count:1,start:e.now()+i*1000,end:e.now()+(i+1)*1000}));const full=g.siegePreparationQuote('capital','named_jiangling'),before=JSON.stringify(g.state);assert.equal(full.orders.length,0);assert.ok(g.fillSiegePreparation('capital','named_jiangling',full.key));assert.equal(JSON.stringify(g.state),before);});
test('invalid targets, templates and stale or readonly confirmations are rejected without mutation',()=>{const e=prepared(),g=e.Game,q=store(g);for(const t of [template({fake:1}),template({militia:100001}),{...template(),hero:'missing'}, {...template(),tactic:'magic'}]){const before=JSON.stringify(g.state);assert.ok(g.saveSiegePreparation('capital','named_jiangling',t,q.key));assert.equal(JSON.stringify(g.state),before);}g.state.army.militia++;assert.ok(g.fillSiegePreparation('capital','named_jiangling',q.key));g.releaseSaveSession();const before=JSON.stringify(g.state);assert.ok(g.fillSiegePreparation('capital','named_jiangling',g.siegePreparationQuote('capital','named_jiangling').key));assert.equal(JSON.stringify(g.state),before);});
test('legacy preparation migrates empty and strict validation rejects unknown cities and forged fields',()=>{const e=prepared(),g=e.Game,d=cloneActiveSave(g.state);delete d.siegePreparation;const migrated=g.migrateSave(d);assert.equal(g.validSave(migrated),true);assert.equal(Object.keys(migrated.siegePreparation.templates).length,0);for(const bad of [{version:2,templates:{}},{version:1,templates:{fake:{named_jiangling:template()}}},{version:1,templates:{capital:{bad:template()}}},{version:1,templates:{},extra:1}]){const x=cloneActiveSave(g.state);x.siegePreparation=bad;assert.equal(g.validSave(x),false);}});
test('storage failure rolls back the entire refill rather than leaving a partial settlement',()=>{const e=prepared(),g=e.Game,q=store(g),res=JSON.stringify(g.state.res),pop=g.state.population,queue=JSON.stringify(g.state.trainQueue);e.evaluate("localStorage.setItem=()=>{throw Error('full')}");assert.ok(g.fillSiegePreparation('capital','named_jiangling',q.key));assert.equal(JSON.stringify(g.state.res),res);assert.equal(g.state.population,pop);assert.equal(JSON.stringify(g.state.trainQueue),queue);});

test('another-city quote is pure and a confirmation after switching cities rejects the old key',()=>{const e=prepared(),g=e.Game,q=store(g);e.evaluate("Game.state.conquered.yellow_qingshi=true;var c=CitySystem.empty(Game.state,Game.getNode('yellow_qingshi'),Date.now());Game.state.realm.cities[c.id]=c;CitySystem.capture(Game.state)");const before=JSON.stringify(g.state);g.siegePreparationQuote('city_yellow_qingshi','named_jiangling');assert.equal(JSON.stringify(g.state),before);assert.equal(g.switchCity('city_yellow_qingshi'),null);assert.ok(g.fillSiegePreparation('capital','named_jiangling',q.key));});
test('pressure notice is session-only, once per deadline and hidden by a supply cut',()=>{const e=prepared(),fs=require('node:fs');e.evaluate('function S(){return Game.state}');e.evaluate(fs.readFileSync('named-city-ui.js','utf8'));e.Game.state.realm.namedCities.garrisons.named_jiangling.pressureAt=e.now()-61*3600000;const before=JSON.stringify(e.Game.state);assert.match(e.evaluate('siegePressureNotice()'),/江陵/);assert.equal(e.evaluate('siegePressureNotice()'),'');assert.equal(JSON.stringify(e.Game.state),before);e.evaluate('Game.garrisonStatus=()=>({abandonAt:Date.now()+3600000,supplyCut:1})');assert.equal(e.evaluate('siegePressureNotice()'),'');});

test('explicit dispatch can copy a template command into its frozen orders without changing default tactics',()=>{const e=prepared(),g=e.Game;g.state.army.militia=10;const node=g.getWorldTile(33,32),before=JSON.stringify(g.state.tactics);assert.equal(g.dispatch(node.id,'lin',{militia:10},'raid',false,'hold'),null);assert.equal(g.state.expedition.orders.militia.command,'hold');assert.equal(JSON.stringify(g.state.tactics),before);});

test('routine half-second income keeps a full-cost quote usable, but actual order changes invalidate it',()=>{const e=prepared(),g=e.Game,q=store(g);e.advance(500);assert.equal(g.siegePreparationQuote('capital','named_jiangling').key,q.key);assert.equal(g.fillSiegePreparation('capital','named_jiangling',q.key),null);});
test('all existing builtin generals, including recruited Yan, can be saved in preparation',()=>{const e=prepared(),g=e.Game;g.state.generals.push('yan');g.state.generalLevels.yan=1;g.state.generalXp.yan=0;g.state.realm.heroLocations.yan='capital';city(g,{tavern:3});e.evaluate('HeroSystem.init(Game.state);HeritageSystem.init(Game.state);GovernanceSystem.init(Game.state)');const q=g.siegePreparationQuote('capital','named_jiangling');assert.equal(g.saveSiegePreparation('capital','named_jiangling',{...template(),hero:'yan'},q.key),null);assert.equal(g.validSave(g.state),true);});
test('quote includes cumulative completion after existing training and copied dispatch remains a draft',()=>{const e=prepared(),g=e.Game,q=store(g);assert.equal(q.completionAt,e.now()+q.orders.reduce((n,o)=>n+o.seconds*1000,0));const fs=require('node:fs');e.evaluate(`var modalBody={querySelectorAll(){return [{dataset:{armyNumber:'militia'},value:'12'}]},dataset:{siegeCommand:'hold'}};document.getElementById=()=>({value:'lin'});`);e.evaluate(fs.readFileSync('named-city-ui.js','utf8'));const before=JSON.stringify(g.state),t=e.evaluate('siegeCurrentDispatchDraft()');assert.equal(t.hero,'lin');assert.equal(t.army.militia,12);assert.equal(t.tactic,'hold');assert.equal(JSON.stringify(g.state),before);});
