const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city}=require('./helpers/game.cjs');
function setup(node='luo_gate',army={shield:350,spear:500,archer:1100,ram:5,catapult:2}){const env=loadGame(),{Game}=env;city(Game,{hall:4,drill:3,house:10});Game.state.conquered.fort=true;for(const n of env.evaluate('ChapterData.allNodes()')){if(n.id===node)break;Game.state.conquered[n.id]=true;}Object.assign(Game.state.army,army);Game.state.res.food=1000000;for(const id of Object.keys(army))Game.setTactic(id,'advance','');assert.equal(Game.dispatch(node,'lin',army,'occupy'),null);env.advance(Game.state.expedition.end-env.now()+1);assert.equal(Game.startBattle(),null);return env;}
test('third chapter requires the completed second campaign, and raids have no siege',()=>{const {Game,Chapter}=loadGame();Game.state.conquered.fort=true;assert.ok(Game.attackBlocked('luo_outpost','raid'));for(const n of Chapter.nodes)Game.state.conquered[n.id]=true;assert.equal(Game.attackBlocked('luo_outpost','raid'),null);assert.equal(Game.attackInfo('luo_gate','raid').siege,false);assert.equal(Game.attackInfo('luo_gate','occupy').siege,true);});
test('trial equipment rewards are claimed once and remain behind stage completion',()=>{const {Game,Chapter}=loadGame();assert.equal(Game.claimMission('chapter3_luo_outpost'),'目标尚未达成');Object.assign(Game.state.conquered,{fort:true,luo_outpost:true});for(const n of Chapter.nodes)Game.state.conquered[n.id]=true;assert.equal(Game.claimMission('chapter3_luo_outpost'),null);assert.equal(Game.state.army.ram,5);assert.equal(Game.claimMission('chapter3_luo_outpost'),'该任务奖励已领取');assert.equal(Game.state.army.ram,5);Game.init();assert.equal(Game.state.army.ram,5);assert.ok(Game.unitRequirements('ram'));});
test('gate damage gives siege equipment real advantages over equal-number ordinary troops',()=>{const env=loadGame();const damages=env.evaluate(`Object.fromEntries(['shield','archer','ram','catapult'].map(id=>[id,SiegeSystem.damage({id,hp:10*ManualData.units[id].hp,stats:ManualData.units[id]})]))`);assert.ok(damages.ram>damages.shield*50);assert.ok(damages.catapult>damages.archer*100);});
test('a siege target can be ordered, takes actual damage, and persists through reload',()=>{const env=setup(),{Game}=env,b=Game.state.battle;assert.equal(Game.setBattleOrder('catapult',undefined,'gate'),null);for(let i=0;i<5&&b.gate.hp===b.gate.maxHp;i++)Game.battleRound();assert.ok(b.gate.hp<b.gate.maxHp);assert.equal(Game.validSave(Game.state),true);const hp=b.gate.hp;Game.init();assert.equal(Game.state.battle.gate.hp,hp);const bad=JSON.parse(JSON.stringify(Game.state));bad.battle.gate.hp=bad.battle.gate.maxHp+1;assert.equal(Game.validSave(bad),false);});
test('gate remains a victory condition after defending troops are eliminated',()=>{const env=setup(),{Game}=env,b=Game.state.battle;for(const row of b.enemy)row.hp=0;for(const row of b.player)row.pos=0;Game.battleRound();assert.equal(b.finished,false);assert.ok(b.gate.hp>0);assert.equal(Game.state.conquered.luo_gate,undefined);});
test('broken gate removes protection and tower threat, then allows occupation victory',()=>{const env=setup(),{Game}=env,b=Game.state.battle;b.gate.hp=1;for(const row of b.player)row.pos=b.length;Game.setBattleOrder('ram',undefined,'gate');Game.battleRound();assert.equal(b.gate.hp,0);assert.ok(b.log.some(t=>t.includes('箭楼停止')));for(const row of b.enemy)row.hp=0;Game.battleRound();assert.equal(b.result.won,true);assert.equal(Game.state.conquered.luo_gate,true);});
test('commanders and defensive layouts produce distinct real battle plans',()=>{const {Game}=loadGame();const gate=Game.getNode('luo_gate'),camp=Game.getNode('luo_cavalry'),wall=Game.getNode('luo_wall');assert.equal(gate.commander.order,'hold');assert.equal(camp.commander.order,'advance');assert.ok(camp.commander.attack>gate.commander.attack);assert.ok(wall.fortification.hp>gate.fortification.hp);assert.ok(wall.fortification.range>gate.fortification.range);});
