const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {loadGame}=require('./helpers/game.cjs');
function ui(){const e=loadGame(),g=e.Game;g.state.res.gold=100000;e.evaluate(`function S(){return Game.state;}function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');}function num(v){return String(v);}function btn(label,action,id,cls,disabled){return '<button data-action="'+action+'" data-id="'+id+'" '+(disabled?'disabled':'')+'>'+label+'</button>';}`);e.evaluate(fs.readFileSync('named-city-ui.js','utf8'));return e;}
const html=e=>e.evaluate("namedGarrisonHTML('named_jiangling')");
test('short siege card makes pressure and both actions visible while rules stay collapsed and viewing is pure',()=>{const e=ui(),before=JSON.stringify(e.Game.state),h=html(e);assert.match(h,/garrison-status-card/);assert.match(h,/未开始/);assert.match(h,/围城说明/);assert.match(h,/<details[^>]*>/);assert.doesNotMatch(h,/<details[^>]*\bopen/);assert.match(h,/data-action="garrisonPersuade"/);assert.match(h,/data-action="garrisonSow"/);assert.equal(JSON.stringify(e.Game.state),before);});
test('a real letter starts a projected reset countdown and exposes its daily disabled state',()=>{const e=ui(),g=e.Game;assert.equal(g.persuadeGarrison('named_jiangling'),null);let h=html(e);assert.match(h,/72小时/);assert.match(h,/今日已用/);assert.match(h,/data-action="garrisonPersuade"[^>]*disabled/);e.advance(3600000);const before=JSON.stringify(g.state);h=html(e);assert.match(h,/71小时/);assert.equal(JSON.stringify(g.state),before);});
test('supply cut pressure has no misleading reset countdown and reports net daily loyalty change',()=>{const e=ui(),g=e.Game,n=g.getNode('named_jiangling');for(let i=0;i<3;i++){const id=`wild_${n.x+i-1}_${n.y+1}`;g.state.conquered[id]=true;g.state.landClaims[id]={at:e.now(),level:1};}const before=JSON.stringify(g.state),h=html(e);assert.match(h,/持续施压/);assert.match(h,/每天 −4/);assert.doesNotMatch(h,/\d+小时后重置/);assert.equal(JSON.stringify(g.state),before);});
test('capture readiness is strictly below 30 and still requires a won occupation battle',()=>{const e=ui(),r=e.Game.state.realm.namedCities.garrisons.named_jiangling;r.loyalty=30;assert.doesNotMatch(html(e),/下次占领战胜利可俘获/);r.loyalty=29;assert.match(html(e),/下次占领战胜利可俘获/);});
test('advisor absence and a real cooldown remain distinct and readonly',()=>{const e=ui(),g=e.Game;assert.match(html(e),/需任命军师/);assert.equal(e.evaluate("HeritageSystem.assign('lin','','su')"),null);assert.equal(g.sowGarrison('named_jiangling'),null);const before=JSON.stringify(g.state),h=html(e);assert.match(h,/冷却/);assert.match(h,/data-action="garrisonSow"[^>]*disabled/);assert.equal(JSON.stringify(g.state),before);});
test('after a pressure lapse the displayed countdown returns to not-started rather than zero',()=>{const e=ui(),g=e.Game;g.persuadeGarrison('named_jiangling');e.advance(73*3600000);const h=html(e);assert.match(h,/未开始/);assert.doesNotMatch(h,/0小时后重置/);});
test('minute refresh preserves expanded rules and keyboard focus on their summary',()=>{const e=ui();e.evaluate(`var refreshed=0,focusRestored=0;var summary={dataset:{},matches:s=>s==='summary'};var oldDetails={open:true},newDetails={open:false};var next={querySelector:s=>s==='details'?newDetails:s==='summary'?{focus:opts=>{if(opts.preventScroll)focusRestored++;}}:null};var card={isConnected:true,dataset:{garrisonCard:'named_jiangling',garrisonKey:'expired'},contains:el=>el===summary,querySelector:()=>oldDetails,replaceWith:()=>refreshed++};document.activeElement=summary;document.querySelectorAll=()=>[card];document.createElement=()=>({content:{firstElementChild:next},set innerHTML(value){}});refreshNamedGarrisonUI();`);assert.equal(e.evaluate('refreshed'),1);assert.equal(e.evaluate('newDetails.open'),true);assert.equal(e.evaluate('focusRestored'),1);});
