const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city,battle}=require('./helpers/game.cjs');
function setup(seed=123){const e=loadGame(seed),g=e.Game;city(g,{hall:8,drill:10,house:10,barracks:10,academy:8,smith:8});Object.assign(g.state.conquered,{fort:true,north_keep:true});Object.assign(g.state.army,{shield:350,spear:500,archer:1100,cavalry:150,ram:10,catapult:5});g.state.res.food=1000000;return e;}
test('order interfaces enforce chapter, sequential tiers, real siege mode and route concurrency',()=>{
 const e=loadGame(),g=e.Game;city(g,{drill:10});g.state.army.archer=2500;g.state.res.food=1000000;assert.match(g.dispatch('order_field_1','lin',{archer:100},'occupy'),/北境大营/);assert.match(g.warOrders.exchange('starterJewelBox'),/北境大营/);g.state.conquered.north_keep=true;assert.match(g.dispatch('order_field_2','lin',{archer:100},'occupy'),/第 1 阶/);assert.match(g.dispatch('order_siege_1','lin',{archer:100},'raid'),/讨伐/);assert.equal(g.dispatch('order_field_1','lin',{archer:100},'occupy'),null);assert.match(g.attackBlocked('order_field_1','occupy'),/已有部队/);assert.equal(g.attackBlocked('order_elite_1','occupy'),null);assert.equal(g.getNode('__proto__'),null);assert.equal(g.getNode('order_field_11'),null);
});
test('actual victories award first and repeat merit once, without creating territory or weakening loot',()=>{
 const e=setup(),g=e.Game;const r=battle(e,'order_field_1','occupy',{shield:350,spear:500,archer:1100,cavalry:150});assert.equal(r.won,true);assert.equal(r.warOrder.points,32);assert.equal(r.warOrder.first,true);assert.equal(g.state.warOrders.merit,32);assert.equal(g.state.conquered.order_field_1,undefined);assert.equal(g.state.raided.order_field_1,undefined);assert.equal(g.attackInfo('order_field_1','occupy').loot.food,2500);g.battleRound();assert.equal(g.state.warOrders.merit,32);assert.match(g.attackBlocked('order_field_2','occupy'),/整军/);assert.equal(g.validSave(g.state),true);g.init();assert.equal(g.state.reports[0].warOrder.points,32);e.advance(g.warOrders.RECOVERY+1);g.dismissBattle();assert.equal(g.warOrders.maxTier(g.state,'field'),2);const repeat=battle(e,'order_field_1','occupy',{...g.state.army});assert.equal(repeat.won,true);assert.equal(repeat.warOrder.first,false);assert.equal(repeat.warOrder.points,16);assert.equal(g.state.warOrders.earned,48);assert.equal(g.state.warOrders.cleared.field,1);assert.equal(g.validSave(g.state),true);
});
test('defeat gives no merit or progress and rest expires offline without rewards',()=>{
 const e=setup(),g=e.Game;const r=battle(e,'order_elite_1','occupy',{archer:1});assert.equal(r.won,false);assert.equal(r.warOrder,null);assert.equal(g.state.warOrders.merit,0);assert.equal(g.state.warOrders.cleared.elite,0);assert.match(g.attackBlocked('order_elite_1','occupy'),/整军/);e.offline(5*3600000);assert.equal(g.state.warOrders.merit,0);assert.equal(g.state.warOrders.wins.elite,0);assert.equal(g.attackBlocked('order_elite_1','occupy'),null);assert.equal(g.validSave(g.state),true);
});
test('order siege uses the real gate and a mixed army wins only after its destruction',()=>{
 const e=setup(),g=e.Game;assert.equal(g.attackInfo('order_siege_1','occupy').siege,true);const r=battle(e,'order_siege_1','occupy',{shield:350,spear:500,archer:1100,ram:10,catapult:5});assert.equal(r.won,true);assert.equal(g.state.battle.gate.hp,0);assert.ok(g.state.battle.log.some(line=>line.includes('城防已破')));assert.equal(r.warOrder.points,40);assert.equal(r.claimed,false);assert.equal(g.state.warOrders.cleared.siege,1);assert.equal(g.validSave(g.state),true);
});
test('exchanges debit the separate ledger and persist an unopened item, with no partial payment',()=>{
 const e=setup(),g=e.Game;assert.match(g.warOrders.exchange('starterJewelBox'),/不足/);battle(e,'order_field_1','occupy',{...g.state.army});const before=g.state.warOrders.merit;assert.match(g.warOrders.exchange('unknown'),/不存在/);assert.equal(g.state.warOrders.merit,before);assert.equal(g.warOrders.exchange('speed_train_1h'),null);assert.equal(g.state.warOrders.merit,12);assert.equal(g.state.warOrders.spent,20);assert.equal(g.state.inventory.speed_train_1h,1);assert.match(g.warOrders.exchange('speed_train_1h'),/不足/);assert.equal(g.state.inventory.speed_train_1h,1);e.offline(5*3600000);assert.equal(g.state.warOrders.merit,12);assert.equal(g.state.inventory.speed_train_1h,1);assert.equal(g.validSave(g.state),true);
});
test('old saves receive only an empty order ledger, and malformed ledgers and reports are rejected',()=>{
 const e=setup(),g=e.Game;const old=JSON.parse(JSON.stringify(g.state));delete old.warOrders;g.importSave(old);assert.equal(g.state.warOrders.merit,0);assert.equal(g.state.warOrders.cleared.field,0);assert.equal(g.validSave(g.state),true);
 for(const change of [s=>s.warOrders.merit=-1,s=>s.warOrders.earned=5,s=>s.warOrders.cleared.field=11,s=>s.warOrders.wins.field=1.5,s=>s.warOrders.nextAt.field=-1,s=>s.warOrders.last={node:'order_field_1',route:'field',tier:1,first:true,points:999}]){const s=JSON.parse(JSON.stringify(g.state));change(s);assert.equal(g.validSave(s),false);assert.throws(()=>g.importSave(s),/Invalid save/);}
 battle(e,'order_field_1','occupy',{...g.state.army});const bad=JSON.parse(JSON.stringify(g.state));bad.reports[0].warOrder.points=999;assert.equal(g.validSave(bad),false);
});
test('five offline hours finish return and queues without replaying merit or starting a battle',()=>{
 const e=setup(),g=e.Game;g.state.tech.training=4;g.state.tech.shooting=1;g.state.population=1000;for(const id of Object.keys(g.state.res))g.state.res[id]=1000000;assert.equal(g.train('archer',20),null);const r=battle(e,'order_field_1','occupy',{shield:350,spear:500,archer:1000});const back=r.back.archer,merit=g.state.warOrders.merit;e.offline(5*3600000);assert.equal(g.state.army.archer,100+back+20);assert.equal(g.state.trainQueue.length,0);assert.equal(g.state.expedition,null);assert.equal(g.state.warOrders.merit,merit);assert.equal(g.validSave(g.state),true);g.dismissBattle();assert.equal(g.dispatch('order_elite_1','lin',{archer:100},'occupy'),null);e.offline(5*3600000);assert.equal(g.state.expedition.phase,'march');assert.equal(g.state.battle,null);assert.equal(g.state.warOrders.merit,merit);assert.equal(g.validSave(g.state),true);
});
test('all thirty order tiers can advance sequentially, persist, and retain repeat access after the finale',()=>{
 const e=setup(),g=e.Game;let earned=0;for(const route of Object.keys(g.warOrders.routes))for(let tier=1;tier<=10;tier++){Object.assign(g.state.army,{shield:350,spear:500,archer:1100,cavalry:150,ram:10,catapult:5});const r=battle(e,`order_${route}_${tier}`,'occupy',{...g.state.army});assert.equal(r.won,true,route+' '+tier);assert.equal(r.warOrder.first,true);earned+=r.warOrder.points;assert.equal(g.state.warOrders.cleared[route],tier);e.advance(g.warOrders.RECOVERY+1);g.dismissBattle();assert.equal(g.validSave(g.state),true);g.init();}
 assert.equal(g.state.warOrders.earned,earned);for(const route of Object.keys(g.warOrders.routes)){assert.equal(g.warOrders.maxTier(g.state,route),10);assert.equal(g.attackBlocked(`order_${route}_10`,'occupy'),null);}const saved=g.state.warOrders.earned;e.offline(5*3600000);assert.equal(g.state.warOrders.earned,saved);
});
test('final siege punishes an all-archer formation while a protected force can complete the gate objective',()=>{
 const {encounter}=require('./balance/war-orders.cjs');for(const seed of [123,456]){const arrows=encounter(seed,'siege',10,{archer:1100});assert.equal(arrows.won,false);assert.ok(arrows.gateRemaining>0);assert.equal(arrows.merit,0);const protectedForce=encounter(seed,'siege',10,{shield:350,spear:500,archer:1100,cavalry:150,ram:10,catapult:5});assert.equal(protectedForce.won,true);assert.equal(protectedForce.gateRemaining,0);assert.equal(protectedForce.merit,112);assert.equal(protectedForce.validSave,true);}
});
