const {loadCompactUI}=require('./helpers/compact-ui.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {loadGame,city,cloneActiveSave}=require('./helpers/game.cjs');
const ids=['order_encounter_field_5_screen','order_encounter_elite_7_lure','order_encounter_siege_10_fire'];
const copy=x=>JSON.parse(JSON.stringify(x));
function setup(id=ids[0],seed=123){const e=loadGame(seed),g=e.Game;city(g,{hall:8,drill:10,house:10,barracks:10,academy:8,smith:8});g.state.conquered.north_keep=true;Object.assign(g.state.army,{archer:1200,shield:300,spear:400,cavalry:200});g.state.res.food=1000000;const n=g.getNode(id);g.state.warOrders.cleared[n.orderRoute]=n.orderTier;g.state.warOrders.wins[n.orderRoute]=n.orderTier;return e;}
function evidence(values={}){return {round:8,machineGateAttacks:0,army:{archer:80,shield:20},lost:{archer:10,shield:10},alive:{archer:70,shield:10},...values};}
function ui(e){loadCompactUI(e);e.evaluate(`globalThis.S=()=>Game.state;globalThis.esc=s=>String(s);globalThis.num=n=>Number(n).toLocaleString('zh-CN');globalThis.duration=n=>String(n);globalThis.btn=(label,action,id='',cls='',disabled=false)=>'<button data-action="'+action+'" data-id="'+id+'"'+(disabled?' disabled':'')+'>'+label+'</button>';globalThis.siegeIntelHTML=()=>'';`);e.evaluate(fs.readFileSync(path.join(__dirname,'..','war-orders-ui.js'),'utf8'));return e.evaluate('warEncounterCardsHTML()');}
function start(e,id,army={archer:1200,shield:300,spear:400,cavalry:200},hero='lin'){const g=e.Game;for(const unit of Object.keys(army))assert.equal(g.setTactic(unit,'advance',''),null);assert.equal(g.dispatch(id,hero,army,'occupy'),null);e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.startBattle(),null);return g.state.battle;}
function recruitedStrategist(e){const g=e.Game,wild=e.evaluate('HeroSystem.wild');city(g,{inn:2,tavern:6});g.state.honors.noble=2;g.state.army.archer=5000;for(const id of Object.keys(g.resources))g.state.res[id]=1000000;e.evaluate('Math.random=()=>.999999');assert.equal(wild.discover(),null);const rumor=g.state.wildGenerals.rumors.find(r=>r.line==='strategist'),portrait=wild.portraitQuote(g.state,'strategist');assert.ok(rumor);assert.equal(wild.buyPortrait('strategist',portrait.key),null);assert.equal(g.setTactic('archer','advance'),null);assert.equal(g.dispatch(rumor.node,'lin',{archer:1500},'raid'),null);e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.startBattle(),null);for(let i=0;i<30&&!g.state.battle.finished;i++)g.battleRound();assert.equal(g.state.battle.result.wildGeneral.status,'captured');e.advance(Math.ceil(g.state.expedition.end-e.now())+1);const q=wild.recruitQuote(g.state,rumor.id,'gold');assert.equal(q.reason,'');assert.equal(wild.recruit(rumor.id,'gold',q.key),null);g.dismissBattle();assert.equal(g.validSave(g.state),true);return rumor.id;}

test('three immutable mixed encounters keep existing ten-tier routes and five challenges intact',()=>{
 const e=loadGame(),g=e.Game,w=g.warOrders;assert.equal(w.challenges.length,8);assert.equal(w.encounters.length,3);assert.equal(w.challenges.filter(c=>!c.encounter).length,5);
 for(const id of ids){const n=g.getNode(id),c=w.challenge(id),config=w.encounterConfig(id);assert.equal(n.encounter,config);assert.equal(c.config,config);assert.equal(n.challengeId,id);assert.equal(config.deployment,'line');assert.ok([2600,3000].includes(config.length));assert.equal(Object.keys(n.army).length,3);assert.equal(n.fortification,undefined);assert.equal(n.wild,false);assert.equal(n.commander.wildLine,undefined);assert.equal(n.wildLine,undefined);assert.equal(n.encounter.playerPositions,undefined);assert.deepEqual(Object.keys(config.enemyPositions).sort(),Object.keys(n.army).sort());assert.deepEqual(Object.keys(config.enemyOrders).sort(),Object.keys(n.army).sort());for(const pos of Object.values(config.enemyPositions))assert.ok(pos>0&&pos<config.length);assert.equal(Object.isFrozen(n),true);assert.equal(Object.isFrozen(config),true);assert.equal(Object.isFrozen(config.plans[0].action),true);const original=config.plans[0].action.type;config.plans[0].action.type='forged';assert.equal(config.plans[0].action.type,original);}
 assert.equal(w.encounterConfig('order_field_5'),null);assert.equal(w.encounterConfig('__proto__'),null);assert.equal(w.encounterConfig('missing'),null);
 for(const route of ['field','siege','elite'])for(let tier=1;tier<=10;tier++){const n=g.getNode(`order_${route}_${tier}`);assert.equal(n.orderTier,tier);assert.equal(n.encounter,undefined);}
});

test('encounters open only after their ordinary checkpoints and share real route recovery and expedition gates',()=>{
 for(const id of ids){const e=setup(id),g=e.Game,n=g.getNode(id);g.state.conquered.north_keep=false;assert.match(g.attackBlocked(id,'occupy'),/北境大营/);g.state.conquered.north_keep=true;g.state.warOrders.cleared[n.orderRoute]--;g.state.warOrders.wins[n.orderRoute]--;assert.match(g.attackBlocked(id,'occupy'),new RegExp('普通第 '+n.orderTier+' 阶'));assert.match(g.dispatch(id,'lin',{archer:100},'occupy'),/普通第/);g.state.warOrders.cleared[n.orderRoute]++;g.state.warOrders.wins[n.orderRoute]++;assert.equal(g.attackBlocked(id,'occupy'),null);assert.match(g.attackBlocked(id,'raid'),/讨伐/);g.state.warOrders.nextAt[n.orderRoute]=e.now()+600000;assert.match(g.attackBlocked(id,'occupy'),/整军/);e.advance(600001);assert.equal(g.dispatch(`order_${n.orderRoute}_${n.orderTier}`,'lin',{archer:100},'occupy'),null);assert.match(g.attackBlocked(id,'occupy'),/已有部队/);}
});

test('encounter cards reveal only reached scenarios and never expose hidden fire coordinates',()=>{
 const e=loadGame(),g=e.Game,before=JSON.stringify(g.state);let html=ui(e);assert.equal(JSON.stringify(g.state),before);for(const id of ids)assert.ok(!html.includes(id));assert.match(html,/平定北境/);
 g.state.conquered.north_keep=true;html=e.evaluate('warEncounterCardsHTML()');for(const id of ids)assert.ok(!html.includes(id));assert.match(html,/普通第 5 阶/);
 g.state.warOrders.cleared.field=5;g.state.warOrders.wins.field=5;html=e.evaluate('warEncounterCardsHTML()');assert.ok(html.includes(ids[0]));assert.ok(!html.includes(ids[1]));assert.ok(!html.includes(ids[2]));assert.match(html,/普通第 7 阶/);assert.match(html,/察伏/);assert.match(html,/data-ui-disclosure="war-encounter-/);
 g.state.warOrders.cleared.elite=7;g.state.warOrders.wins.elite=7;html=e.evaluate('warEncounterCardsHTML()');assert.ok(html.includes(ids[1]));assert.ok(!html.includes(ids[2]));assert.match(html,/坚守或后退/);
 g.state.warOrders.cleared.siege=10;g.state.warOrders.wins.siege=10;html=e.evaluate('warEncounterCardsHTML()');assert.ok(html.includes(ids[2]));assert.match(html,/12 回合/);assert.match(html,/普通将/);assert.match(html,/没有门墙/);assert.doesNotMatch(html,/1400|1500/);assert.doesNotMatch(html,/下一场遭遇需/);for(const id of Object.keys(g.getNode(ids[2]).army))assert.ok(html.includes(g.units[id].name));
});

test('loss and round boundaries reward ordinary wins and first tactical bonus once without advancing normal routes',()=>{
 for(const id of ids){const e=setup(id),g=e.Game,n=g.getNode(id),c=g.warOrders.challenge(id),pass=evidence({round:c.maxRound||8,lost:{archer:c.limit,shield:0},alive:{archer:80-c.limit,shield:20}}),fail=evidence({round:c.maxRound||8,lost:{archer:c.limit+1,shield:0},alive:{archer:79-c.limit,shield:20}}),ordinary=g.warOrders.settle(g.state,n,true,e.now(),fail);assert.equal(ordinary.challenge.met,false);assert.equal(ordinary.points,g.warOrders.points(n));assert.equal(g.state.warOrders.challenges.earned,0);assert.equal(g.state.warOrders.cleared[n.orderRoute],n.orderTier);assert.equal(g.validSave(g.state),true);
  const first=g.warOrders.settle(g.state,n,true,e.now(),pass);assert.equal(first.challenge.met,true);assert.equal(first.challenge.first,true);assert.equal(first.challenge.bonus,c.bonus);assert.equal(first.points,first.basePoints+c.bonus);const repeated=g.warOrders.settle(g.state,n,true,e.now(),pass);assert.equal(repeated.challenge.first,false);assert.equal(repeated.challenge.bonus,0);assert.equal(g.state.warOrders.challenges.earned,c.bonus);assert.equal(g.validSave(g.state),true);g.importSave(copy(g.state));assert.equal(g.state.warOrders.challenges.completed[id],true);assert.equal(g.state.warOrders.challenges.earned,c.bonus);assert.equal(g.warOrders.settle(g.state,n,false,e.now(),pass),null);assert.equal(g.state.warOrders.challenges.lastAttempts[id].met,false);assert.equal(g.validSave(g.state),true);
  if(c.maxRound){const tooLate=g.warOrders.settle(g.state,n,true,e.now(),{...pass,round:c.maxRound+1});assert.equal(tooLate.challenge.met,false);assert.equal(tooLate.points,g.warOrders.points(n));}
 }
});

test('new encounter receipts cannot masquerade as legacy challenges or forge checkpoint and first-bonus ledgers',()=>{
 const e=setup(ids[0]),g=e.Game,n=g.getNode(ids[0]);g.warOrders.settle(g.state,n,true,e.now(),evidence());assert.equal(g.validSave(g.state),true);
 for(const mutate of [s=>{delete s.warOrders.last.challenge.rulesVersion;delete s.warOrders.last.challenge.machineGateAttacks;},s=>s.warOrders.last.challenge.bonus++,s=>delete s.warOrders.challenges.completed[n.id],s=>s.warOrders.cleared.field=4,s=>s.warOrders.challenges.completed.unknown_encounter=true,s=>s.warOrders.last.challenge.lost=21]){const invalid=copy(g.state);mutate(invalid);assert.equal(g.validSave(invalid),false);assert.throws(()=>g.importSave(invalid),/Invalid save/);}
 const old=setup(ids[0]);delete old.Game.state.warOrders.challenges;old.Game.importSave(copy(old.Game.state));assert.equal(old.Game.validSave(old.Game.state),true);assert.deepEqual(copy(old.Game.state.warOrders.challenges.completed),{});
});

test('real marching encounters use fixed field geometry and scoped enemy tactics through valid reloads',()=>{
 for(const [id,type] of ids.map((id,i)=>[id,['huangzhong','weiyan','fire'][i]])){const e=setup(id),g=e.Game,b=start(e,id),cfg=g.warOrders.encounterConfig(id);assert.equal(b.lesson,undefined);assert.equal(b.gate,null);assert.equal(b.length,cfg.length);assert.ok(b.player.every(r=>r.pos===0));for(const row of b.enemy)assert.equal(row.pos,cfg.enemyPositions[row.id]);assert.equal(b.enemyGeneralSnapshot.wildLine,'');assert.equal(b.enemyGeneralSnapshot.encounterIdentity,cfg.enemyIdentity);assert.equal(b.stratagem.plans.filter(p=>p.side==='enemy').length,1);assert.equal(b.stratagem.plans[0].type,type);assert.equal(b.stratagem.plans[0].round,1);assert.equal(b.stratagem.plans[0].readyRound,2);assert.equal(g.validSave(g.state),true);const original=cloneActiveSave(g.state);g.importSave(original);assert.deepEqual(copy(g.state.battle.stratagem.plans),copy(b.stratagem.plans));assert.equal(g.validSave(g.state),true);
  for(const mutate of [s=>delete s.battle.enemyGeneralSnapshot.encounterIdentity,s=>s.battle.enemyGeneralSnapshot.encounterIdentity='xushu',s=>s.battle.enemyGeneralSnapshot.wildLine='strategist',s=>s.battle.enemyGeneralSnapshot.id='enemy_field',s=>{s.battle.rules=2;delete s.battle.stratagem;delete s.battle.enemyGeneralSnapshot;delete s.battle.enemyOrders;},s=>{const st=s.battle.stratagem;st.version=1;st.seq=0;st.plans=[];st.reservations=[];st.spent=[];st.events=[];st.identities.enemy='';st.points.enemy=3;st.submitted.enemy=0;st.identityUsed.enemy=false;},s=>s.battle.length=4000]){const bad=cloneActiveSave(g.state);mutate(bad);assert.equal(g.validSave(bad),false,id);assert.throws(()=>g.importSave(bad),/Invalid save/);}
 }
});

test('shared authority rejects new encounter dispatch and pre-existing offline encounter marches without consuming troops or creating an old-rules battle',async()=>{
 for(const id of ids){const e=setup(id),g=e.Game;assert.equal(g.setTactic('archer','advance',''),null);assert.equal(g.dispatch(id,'lin',{archer:100},'occupy'),null);e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.state.expedition.phase,'march');g.save();const localSave=g.exportStoredRaw();assert.equal(g.enterOnlineSession(cloneActiveSave(g.state)),null);assert.equal(g.authorityActive(),true);const before=JSON.stringify(g.state);assert.match(g.attackBlocked(id,'occupy'),/单机/);assert.match(g.dispatch(id,'su',{archer:100},'occupy'),/单机/);assert.match(g.startBattle(),/单机/);assert.equal(JSON.stringify(g.state),before);assert.equal(g.state.battle,null);assert.equal(g.state.expedition.phase,'march');assert.equal(g.exportStoredRaw(),localSave);await g.leaveOnlineSession();assert.equal(g.authorityActive(),false);assert.equal(g.startBattle(),null);assert.equal(g.state.battle.rules,3);assert.ok(g.state.battle.stratagem);assert.equal(g.validSave(g.state),true);}
});

test('ordinary commanders can cancel shield-screen prefire with public watch while untreated entry triggers it',()=>{
 for(const counter of [false,true]){const e=setup(ids[0]),g=e.Game;start(e,ids[0]);assert.equal(g.battleTacticsView().identity.id,'');g.battleRound();const preparation=g.battleTacticsView().preparations.find(p=>p.side==='enemy'&&p.type==='huangzhong');assert.ok(preparation);if(counter){const q=g.battleTacticQuote('watch',{planId:preparation.id});assert.equal(q.ok,true);assert.equal(g.submitBattleTactic('watch',{planId:preparation.id},q.key).ok,true);}g.battleRound();const events=g.battleTacticsView().events;assert.equal(events.some(x=>x.type==='trigger'&&x.side==='enemy'),!counter);assert.equal(events.some(x=>x.type==='watch'&&x.side==='player'),counter);assert.equal(g.state.battle.stratagem.points.player,counter?2:3);assert.equal(g.validSave(g.state),true);g.importSave(cloneActiveSave(g.state));assert.equal(g.validSave(g.state),true);}
});

test('real cavalry lure retreats before response and hold prevents the chase without a named hero',()=>{
 for(const hold of [false,true]){const e=setup(ids[1]),g=e.Game,b=start(e,ids[1]);g.battleRound();const p=b.stratagem.plans.find(p=>p.type==='weiyan');assert.ok(p.retreated);assert.ok(b.enemy.find(r=>r.id==='cavalry').pos>1600);assert.equal(g.battleTacticsView().plans.find(x=>x.id===p.id).hidden,true);if(hold)assert.equal(g.setBattleOrders('hold'),null);g.battleRound();assert.equal(g.battleTacticsView().events.some(x=>x.type==='chase'&&x.side==='enemy'),!hold);if(hold){assert.equal(p.status,'cancelled');assert.match(p.reason,/没有追击/);}assert.equal(g.validSave(g.state),true);}
 const ranged=setup(ids[1]);start(ranged,ids[1],{archer:1200});assert.equal(ranged.Game.state.battle.stratagem.plans.length,0,'without a legal melee target no free lure is fabricated');assert.equal(ranged.Game.validSave(ranged.Game.state),true);
});

test('fire preview hides the interval, ordinary troops can wait for publication, and legitimately recruited Xu Shu reveals early',()=>{
 const ordinary=setup(ids[2]),g=ordinary.Game;start(ordinary,ids[2]);let fire=g.battleTacticsView().plans.find(p=>p.type==='fire');assert.equal(fire.hidden,true);assert.equal(fire.left,undefined);assert.equal(fire.right,undefined);assert.equal(g.battleTacticQuote('xushu',{planId:fire.id}).ok,false);assert.equal(g.setBattleOrders('hold'),null);g.battleRound();assert.equal(g.battleTacticsView().plans.find(p=>p.id===fire.id).hidden,true);g.battleRound();fire=g.battleTacticsView().plans.find(p=>p.id===fire.id);assert.equal(fire.hidden,false);assert.equal(fire.left,1400);assert.equal(fire.right,1500);assert.ok(g.battleTacticsView().events.some(e=>e.type==='fire'));assert.equal(g.setBattleOrders('advance'),null);assert.equal(g.validSave(g.state),true);
 const e=setup(ids[2]),hero=recruitedStrategist(e),owned=e.Game;Object.assign(owned.state.army,{archer:1200,shield:300,spear:400,cavalry:200});start(e,ids[2],undefined,hero);assert.equal(owned.battleTacticsView().identity.id,'xushu');const plan=owned.battleTacticsView().plans.find(p=>p.type==='fire'),q=owned.battleTacticQuote('xushu',{planId:plan.id});assert.equal(q.ok,true);assert.equal(owned.submitBattleTactic('xushu',{planId:plan.id},q.key).ok,true);const revealed=owned.battleTacticsView().plans.find(p=>p.id===plan.id);assert.equal(revealed.hidden,false);assert.equal(revealed.left,1400);assert.equal(revealed.public,false);assert.equal(owned.state.battle.round,0);assert.equal(owned.validSave(owned.state),true);owned.importSave(cloneActiveSave(owned.state));assert.equal(owned.battleTacticsView().plans.find(p=>p.id===plan.id).left,1400);assert.equal(owned.validSave(owned.state),true);
});

test('actual strong prepared armies win all scenarios, return ordinary cargo, and never recapture a scenario commander or repeat a first bonus',()=>{
 // Prepared checkpoint and high troop counts verify integration and accounting, not natural pacing or balance.
 for(const id of ids){const e=setup(id),g=e.Game,army={archer:2000,shield:600,spear:800,cavalry:300};Object.assign(g.state.army,army);start(e,id,army);for(let round=0;round<30&&!g.state.battle.finished;round++)g.battleRound();const result=g.state.battle.result;assert.equal(result.won,true,id);assert.equal(result.wildGeneral,null);assert.equal(result.warOrder.challenge.met,true,id);assert.equal(result.warOrder.challenge.first,true);assert.ok(result.cargoLoaded>0);assert.equal(g.state.conquered[id],undefined);assert.equal(g.validSave(g.state),true);const earned=g.state.warOrders.earned,bonus=g.state.warOrders.challenges.earned;g.battleRound();assert.equal(g.state.warOrders.earned,earned);g.importSave(cloneActiveSave(g.state));assert.equal(g.state.warOrders.earned,earned);const duplicate=cloneActiveSave(g.state);duplicate.reports.push(copy(duplicate.reports[0]));assert.equal(g.validSave(duplicate),false);e.offline(g.warOrders.RECOVERY+60000);assert.equal(g.state.expedition,null);assert.equal(g.state.warOrders.earned,earned);g.dismissBattle();Object.assign(g.state.army,army);g.state.res.food=1000000;start(e,id,army);for(let round=0;round<30&&!g.state.battle.finished;round++)g.battleRound();assert.equal(g.state.battle.result.won,true);assert.equal(g.state.battle.result.warOrder.challenge.first,false);assert.equal(g.state.battle.result.warOrder.challenge.bonus,0);assert.equal(g.state.warOrders.challenges.earned,bonus);assert.equal(g.validSave(g.state),true);}
});
