const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city}=require('./helpers/game.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
// Fast interaction fixtures, not economy/pacing evidence. Battles still use normal dispatch/round APIs.
function prepare(){const e=loadGame(123),g=e.Game;city(g,{inn:1,tavern:3,drill:1});g.state.res.food=100000;g.state.res.gold=100000;g.state.army.cavalry=30;const wild=e.evaluate('HeroSystem.wild');assert.equal(wild.discover(),null);return {e,g,wild};}
function first(g){return g.state.wildGenerals.rumors.find(r=>r.line==='wanderer');}
function fight(e,node,mode='raid'){
 const g=e.Game;assert.equal(g.setTactic('cavalry','advance',''),null);assert.equal(g.dispatch(node,'lin',{cavalry:30},mode,true),null);
 e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.startBattle(),null);for(let i=0;i<30&&!g.state.battle.finished;i++)g.battleRound();assert.equal(g.state.battle.finished,true);assert.equal(g.state.battle.result.won,true);return copy(g.state.battle.result);
}
test('portrait quotes are readonly; named permanent purchases use gems once and revalidate funds, clues and writer access',()=>{
 const fresh=loadGame(),w=fresh.evaluate('HeroSystem.wild'),g0=fresh.Game;assert.deepEqual(copy(g0.state.wildGenerals.portraits),[]);assert.equal(w.portraitQuote(g0.state,'unknown'),null);assert.match(w.portraitQuote(g0.state,'wanderer').reason,/先.*打听/);assert.match(w.buyPortrait('wanderer',w.portraitQuote(g0.state,'wanderer').key),/先.*打听/);
 const {e,g,wild}=prepare(),before=JSON.stringify(g.state),q=wild.portraitQuote(g.state,'wanderer');assert.deepEqual(Object.keys(q),['line','name','price','owned','reason','key']);assert.equal(q.price,10);assert.equal(q.owned,false);assert.equal(q.reason,'');assert.equal(JSON.stringify(g.state),before);
 assert.deepEqual(copy(wild.definitions.map(d=>d.portraitPrice)),[10,30,50]);g.state.gems=9;assert.match(wild.buyPortrait(q.line,q.key),/元宝不足/);assert.equal(g.state.gems,9);assert.deepEqual(copy(g.state.wildGenerals.portraits),[]);
 g.state.gems=1000;assert.match(wild.buyPortrait('unknown',q.key),/报价或线索/);assert.match(wild.buyPortrait(q.line,q.key+'stale'),/报价或线索/);assert.equal(g.state.gems,1000);assert.equal(wild.buyPortrait(q.line,q.key),null);assert.equal(g.state.gems,990);assert.equal(wild.portraitOwned(g.state,'wanderer'),true);
 assert.match(wild.buyPortrait(q.line,q.key),/变化/);assert.match(wild.buyPortrait(q.line,wild.portraitQuote(g.state,q.line).key),/已永久拥有/);assert.equal(g.state.gems,990);assert.deepEqual(copy(g.state.wildGenerals.portraits),['wanderer']);g.save();e.offline(1);assert.equal(wild.portraitOwned(g.state,'wanderer'),true);assert.equal(g.validSave(g.state),true);
 for(const malformed of [null,'wanderer',['unknown'],['wanderer','wanderer']]){const d=copy(g.state);d.wildGenerals.portraits=malformed;assert.equal(g.validSave(d),false);}
 const blocked=wild.portraitQuote(g.state,'warrior'),funds=g.state.gems;g.releaseSaveSession();assert.ok(wild.buyPortrait('warrior',blocked.key));assert.equal(g.state.gems,funds);assert.equal(wild.portraitOwned(g.state,'warrior'),false);
});
test('a real victory without a portrait keeps loot and returns troops; buying enables capture and remains after release',()=>{
 const {e,g,wild}=prepare(),rumor=copy(first(g)),missing=fight(e,rumor.node);assert.equal(missing.wildGeneral.status,'portrait_required');assert.match(missing.wildGeneral.reason,/尚未拥有.*画像/);assert.equal(Object.values(missing.loot).reduce((a,b)=>a+b,0)>0,true);assert.equal(g.state.expedition.phase,'return');assert.equal(wild.heldCaptives(g.state),0);assert.equal(first(g).status,'active');assert.equal(wild.roomUsed(g.state),2);assert.equal(g.validSave(g.state),true);
 const q=wild.portraitQuote(g.state,'wanderer');assert.equal(wild.buyPortrait(q.line,q.key),null);const gems=g.state.gems;e.advance(90001);const captured=fight(e,rumor.node);assert.equal(captured.wildGeneral.status,'captured');assert.equal(wild.heldCaptives(g.state),1);assert.equal(g.state.gems,gems);assert.equal(wild.portraitOwned(g.state,'wanderer'),true);assert.equal(g.validSave(g.state),true);
 assert.equal(wild.settle(g.state,g.getNode(rumor.node),{mode:'raid',finished:false,enemy:[{hp:1}]},true),null);assert.equal(wild.settle(g.state,g.getNode(rumor.node),{mode:'raid',finished:false,enemy:[{hp:0}]},false),null);assert.equal(g.state.gems,gems);
 const release=wild.releaseQuote(g.state,rumor.id);assert.equal(wild.release(rumor.id,release.key),null);assert.equal(wild.discover(),null);assert.notEqual(first(g).id,rumor.id);assert.equal(wild.portraitOwned(g.state,'wanderer'),true);assert.equal(g.state.gems,gems);assert.equal(wild.validReceipt(missing.wildGeneral,g.state),true);assert.equal(wild.validReceipt(captured.wildGeneral,g.state),true);assert.equal(g.validSave(g.state),true);
});
test('a portraitless occupied clue can relocate without rerolling or IDs; legacy captives and owners need no back payment',()=>{
 const {e,g,wild}=prepare(),old=copy(first(g)),others=copy(g.state.wildGenerals.rumors.filter(r=>r.line!=='wanderer')),seq=g.state.wildGenerals.seq;
 const missing=fight(e,old.node,'occupy');assert.equal(missing.wildGeneral.status,'portrait_required');assert.equal(g.state.conquered[old.node],true);assert.equal(first(g).status,'active');const q=wild.portraitQuote(g.state,'wanderer');assert.equal(wild.buyPortrait(q.line,q.key),null);assert.equal(wild.discover(),null);const next=copy(first(g));assert.notEqual(next.node,old.node);assert.equal(next.id,old.id);assert.equal(g.state.wildGenerals.seq,seq);assert.equal(g.getNode(next.node).level,g.getNode(old.node).level);assert.deepEqual(copy(g.state.wildGenerals.rumors.filter(r=>r.line!=='wanderer')),others);assert.equal(wild.portraitOwned(g.state,'wanderer'),true);
 const stable=copy(g.state.wildGenerals);assert.equal(wild.discover(),null);assert.deepEqual(copy(g.state.wildGenerals),stable);e.advance(Math.ceil(g.state.expedition.end-e.now())+1);const captured=fight(e,next.node);assert.equal(captured.wildGeneral.status,'captured');assert.equal(g.validSave(g.state),true);
 const legacy=copy(g.state);delete legacy.wildGenerals.portraits;g.importSave(legacy);assert.deepEqual(copy(g.state.wildGenerals.portraits),[]);assert.equal(wild.heldCaptives(g.state),1);assert.equal(g.validSave(g.state),true);const quote=wild.recruitQuote(g.state,old.id,'gold'),gold=g.state.res.gold,gems=g.state.gems;assert.equal(quote.reason,'');assert.equal(wild.recruit(old.id,'gold',quote.key),null);assert.equal(g.state.res.gold,gold-6000);assert.equal(g.state.gems,gems);assert.equal(wild.loyalty(g.state,old.id),40);
 const owned=copy(g.state);delete owned.wildGenerals.portraits;const migrated=g.migrateSave(owned);assert.deepEqual(copy(migrated.wildGenerals.portraits),[]);assert.equal(migrated.wildGenerals.recruited.includes(old.id),true);assert.equal(g.validSave(migrated),true);g.importSave(migrated);assert.match(wild.portraitQuote(g.state,'wanderer').reason,/已经归顺/);
});
