const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadGame,city,cloneActiveSave}=require('./helpers/game.cjs');
const lines=['menghuo','zhurong','tadun','huaman','baosanniang'];
function ready(){const e=loadGame(123),g=e.Game,w=e.evaluate('HeroSystem.wild');city(g,{inn:5,tavern:10,drill:3});g.state.honors.noble=7;g.state.gems=2000;g.state.res.gold=2000000;return {e,g,w};}
function capture(x,line){const {g,w,e}=x;const r=g.state.wildGenerals.rumors.find(r=>r.line===line);assert.ok(r);if(!w.portraitOwned(g.state,line)){const q=w.portraitQuote(g.state,line);assert.equal(w.buyPortrait(line,q.key),null);}const receipt=w.settle(g.state,g.getNode(r.node),{mode:'raid',finished:false,enemy:[{hp:0}]},true,e.now());return {r,receipt};}
test('fresh inquiries expose only five new famous generals and do not generate retired leads',()=>{const {g,w}=ready();assert.deepEqual(JSON.parse(JSON.stringify(w.codex(g.state).map(d=>d.line))),lines);assert.equal(w.discover(),null);assert.equal(g.state.wildGenerals.rumors.length,5);assert.ok(g.state.wildGenerals.rumors.every(r=>lines.includes(r.line)));const before=JSON.stringify(g.state);w.codex(g.state);assert.equal(JSON.stringify(g.state),before);assert.equal(g.validSave(g.state),true);});
test('each famous general grants one box on capture, not on repeated settlement or released recapture',()=>{const x=ready(),{g,w,e}=x;assert.equal(w.discover(),null);for(const line of lines){const {r,receipt}=capture(x,line);assert.equal(receipt.status,'captured');assert.equal(w.settle(g.state,g.getNode(r.node),{mode:'raid',finished:false,enemy:[{hp:0}]},true),null);const q=w.releaseQuote(g.state,r.id);assert.equal(w.release(r.id,q.key),null);assert.equal(w.discover(),null);assert.equal(capture(x,line).receipt.status,'captured');assert.equal(w.release(g.state.wildGenerals.rumors.find(r=>r.line===line).id,w.releaseQuote(g.state,g.state.wildGenerals.rumors.find(r=>r.line===line).id).key),null);}assert.equal(g.state.inventory.barbarianEquipmentBox,5);g.save();e.offline(1);assert.equal(g.state.inventory.barbarianEquipmentBox,5);assert.equal(g.validSave(g.state),true);});
test('capture rewards require victory, portrait and room; recruitment has trusted famous identity and stronger command',()=>{const x=ready(),{g,w,e}=x;w.discover();const r=g.state.wildGenerals.rumors.find(r=>r.line==='menghuo'),n=g.getNode(r.node),b={mode:'raid',finished:false,enemy:[{hp:0}]};assert.equal(w.settle(g.state,n,b,false),null);assert.equal(w.settle(g.state,n,b,true).status,'portrait_required');assert.equal(g.state.inventory.barbarianEquipmentBox||0,0);const q=w.portraitQuote(g.state,r.line);w.buyPortrait(r.line,q.key);city(g,{tavern:1});assert.equal(w.settle(g.state,n,b,true).status,'released');assert.equal(g.state.inventory.barbarianEquipmentBox||0,0);city(g,{tavern:10});w.discover();const caught=capture(x,'menghuo');const rq=w.recruitQuote(g.state,caught.r.id);assert.equal(w.recruit(caught.r.id,'gold',rq.key),null);assert.equal(e.evaluate('HeroIdentity').key(g.state,caught.r.id),'menghuo');assert.ok(g.general(caught.r.id).lead>=g.general(caught.r.id).level*10+180);w.discover();assert.equal(g.state.wildGenerals.rumors.filter(r=>r.line==='menghuo').length,1);assert.equal(g.state.inventory.barbarianEquipmentBox,1);assert.equal(g.validSave(g.state),true);});
test('old saves migrate the first-capture ledger; malformed ledgers cannot load',()=>{const {g,w}=ready();const old=cloneActiveSave(g.state);delete old.wildGenerals.firstCaptureRewards;const migrated=g.migrateSave(old);assert.equal(g.validSave(migrated),true);g.importSave(migrated);assert.deepEqual(Array.from(g.state.wildGenerals.firstCaptureRewards),[]);assert.equal(g.validSave(migrated),true);for(const value of [null,{},['unknown'],['wanderer'],['menghuo','menghuo']]){const bad=cloneActiveSave(migrated);bad.wildGenerals.firstCaptureRewards=value;assert.equal(g.validSave(bad),false);}assert.equal(w.portraitQuote(g.state,'wanderer').reason.includes('下架'),true);});
test('all five recruits keep trusted identity and their command advantage across save reload',()=>{const x=ready(),{g,w,e}=x;w.discover();for(const line of lines){const {r}=capture(x,line),q=w.recruitQuote(g.state,r.id);assert.equal(w.recruit(r.id,'gold',q.key),null);assert.equal(e.evaluate('HeroIdentity').key(g.state,r.id),line);g.state.generalLevels[r.id]=20;assert.ok(g.general(r.id).lead>=380);assert.ok(g.general(r.id).lead<=430);}const before=JSON.stringify(g.state);g.getCityState('capital');w.codex(g.state);assert.equal(JSON.stringify(g.state),before);g.save();e.offline(1);assert.equal(g.state.inventory.barbarianEquipmentBox,5);assert.equal(g.validSave(g.state),true);for(const hero of g.state.customGenerals.filter(g=>lines.includes(g.wildLine)))assert.equal(e.evaluate('HeroIdentity').key(g.state,hero.id),hero.wildLine);});
test('a full equipment library keeps the capture box, and a passive writer cannot spend or discover',()=>{const x=ready(),{g,w}=x;w.discover();const {r}=capture(x,'huaman');const before=g.state.inventory.barbarianEquipmentBox;const h=x.e.evaluate('HeroSystem');for(let i=0;i<g.state.equipmentCapacity;i++)h.addEquipment(g.state,'weapon',1);assert.match(g.openBattlefieldBox('nanman'),/已满/);assert.equal(g.state.inventory.barbarianEquipmentBox,before);g.releaseSaveSession();const state=JSON.stringify(g.state);assert.ok(w.discover());assert.ok(w.recruit(r.id,'gold',w.recruitQuote(g.state,r.id).key));assert.equal(JSON.stringify(g.state),state);});
test('the retired Guanyu remains reachable only for the existing Qinglong awakening quest',()=>{const x=ready(),{g,w,e}=x;w.discover();assert.equal(g.state.wildGenerals.rumors.some(r=>r.line==='guanyu'),false);g.state.legendary={qinglong:{stage:'awaken',site:'',siteUntil:0,meteor:0,refined:0,refinedDay:-1,refinedToday:0,lastTry:0,obtainedAt:0,announced:false}};assert.equal(w.discover(),null);assert.equal(w.codex(g.state).some(d=>d.line==='guanyu'),false);const {r,receipt}=capture(x,'guanyu');assert.equal(receipt.status,'captured');assert.equal(g.state.inventory.barbarianEquipmentBox||0,0);const q=w.recruitQuote(g.state,r.id);assert.equal(w.recruit(r.id,'gold',q.key),null);assert.equal(e.evaluate('LegendaryWeapons').awakenBlocked(g.state,e.now(),r.id),'');assert.equal(e.evaluate('HeroIdentity').key(g.state,r.id),'guanyu');assert.equal(g.validSave(g.state),true);});
test('a same-name ordinary recruit cannot block finding or capturing the real named general',()=>{const x=ready(),{g,w,e}=x;assert.equal(g.refreshInn(),null);const c=g.state.innCandidates[0];c.name='孟获';assert.equal(g.recruit(c.id),null);assert.equal(e.evaluate('HeroIdentity').key(g.state,c.id),'');assert.equal(g.validSave(g.state),true);w.discover();const {receipt}=capture(x,'menghuo');assert.equal(receipt.status,'captured');assert.equal(g.state.inventory.barbarianEquipmentBox,1);});
