'use strict';
const assert=require('node:assert/strict'),{normal}=require('./yellow-campaign.cjs'),{normalNan}=require('./nanman-campaign.cjs'),{loadGame}=require('../helpers/game.cjs');
const plain=x=>JSON.parse(JSON.stringify(x)),total=a=>Object.values(a).reduce((n,x)=>n+x,0);
function route(c,kind){const out=[];for(let i=1;i<=9;i++){if([1,4,7].includes(i)&&kind!=='main'){const arc=Math.floor((i-1)/3);if(kind==='all'||c.rescue.includes(c.sideIds[arc*2]))out.push(c.sideIds[arc*2]);if(kind==='all')out.push(c.sideIds[arc*2+1]);}out.push(c.mainIds[i-1]);}return out;}
function run(seed,campaign){const entry=campaign==='yellow_turban'?normal(seed):normalNan(seed),reports=[];for(const kind of ['main','rescue','all']){const e=loadGame(seed),g=e.Game;g.importSave(entry.state);e.advance(entry.state.last-e.now());const c=e.evaluate(`BattlefieldData.config('${campaign}')`),q=g.battlefieldQuote('lin',{militia:800},campaign);assert.equal(q.reason,'');assert.equal(g.startBattlefield('lin',{militia:800},q.key,campaign),null);const battles=[];let error='',pool=0;
 for(const id of route(c,kind)){const r=g.state.battlefields.run;pool=r.pool;const missing=800-r.army.militia;if(missing){error=g.reinforceBattlefield({militia:missing})||'';if(error)break;}error=g.enterBattlefieldNode(id)||'';if(error)break;if(!r.battle)continue;const b=r.battle;while(!b.finished)g.battlefieldRound();battles.push({id,rounds:b.round,lost:total(b.result.lost),guards:total(Object.fromEntries(b.enemy.map(x=>[x.id,x.initial]))),pool:g.state.battlefields.run?.pool??null});if(!b.result.won){error=id+' failed';break;}assert.equal(g.validSave(g.state),true,id);}
 reports.push({kind,route:route(c,kind),error,completed:!g.state.battlefields.run,rounds:battles.reduce((n,b)=>n+b.rounds,0),losses:battles.reduce((n,b)=>n+b.lost,0),lastPool:pool,battles,receipt:plain(g.state.battlefields.lastReceipt),validSave:g.validSave(g.state)});}
 const main=reports[0],all=reports[2];if(main.completed&&all.completed)assert.ok(all.rounds>main.rounds,'all branches spend additional rounds');return {seed,campaign,fixture:'normal economy entry; public rental combat, no grants',entryMinutes:entry.openMinutes??entry.openingMinutes,cultivationDays:entry.cultivationDays??0,reports};}
if(require.main===module)console.log(JSON.stringify([1,7,19].flatMap(seed=>['yellow_turban','nanman'].map(c=>run(seed,c))),null,2));module.exports={run};
