'use strict';
// Prepared acquisition comparison: validates battle/capture/fees, not a complete opening-economy route.
const assert=require('node:assert/strict'),{loadGame,city,cloneActiveSave}=require('../helpers/game.cjs');
function run(seed){const e=loadGame(seed),g=e.Game,w=e.evaluate('HeroSystem.wild');city(g,{hall:10,inn:5,tavern:10,drill:5,barracks:10,academy:10});g.state.honors.noble=7;g.state.gems=2000;g.state.res.gold=2000000;g.state.res.food=2000000;g.state.generalLevels.lin=20;g.state.tech.combat=5;g.state.tech.shooting=5;g.state.tech.protection=5;assert.equal(w.discover(),null);const reports=[];
for(const d of w.activeDefinitions()){
 const r=g.state.wildGenerals.rumors.find(r=>r.line===d.line),n=g.getNode(r.node);g.state.army.archer=4000;g.setTactic('archer','advance','');const q=w.portraitQuote(g.state,d.line);assert.equal(w.buyPortrait(d.line,q.key),null);assert.equal(g.dispatch(n.id,'lin',{archer:3000},'raid'),null);const marchMinutes=(g.state.expedition.end-e.now())/60000;e.advance(Math.ceil(g.state.expedition.end-e.now())+1);assert.equal(g.startBattle(),null);for(let i=0;i<30&&!g.state.battle.finished;i++)g.battleRound();const b=g.state.battle;assert.equal(b.result.won,true,d.name);assert.equal(b.result.wildGeneral.status,'captured',d.name);const lost=Object.values(b.result.lost).reduce((a,b)=>a+b,0);e.advance(Math.ceil(Math.max(g.state.expedition?.end||e.now(),...Object.values(g.state.cooldowns))-e.now())+1);g.dismissBattle();const rq=w.recruitQuote(g.state,r.id);assert.equal(w.recruit(r.id,'gold',rq.key),null);g.state.generalLevels[r.id]=20;reports.push({name:d.name,fieldLevel:n.level,enemy:Object.values(n.army).reduce((a,b)=>a+b,0),archers:3000,marchMinutes,rounds:b.round,lost,portraitGems:d.portraitPrice,recruitGold:d.gold,level20Lead:g.general(r.id).lead,ordinaryLevel20Lead:200});assert.equal(g.validSave(cloneActiveSave(g.state)),true);
}
assert.equal(g.state.inventory.barbarianEquipmentBox,5);return {seed,prepared:true,reports,boxes:5};}
if(require.main===module)console.log(JSON.stringify([1,7,19].map(run),null,2));module.exports={run};
